<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Chapter 12 – Stats Textbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter13.html" rel="next">
<link href="./chapter11.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f2c6d6e2b784ddc5de38779acc06f37d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter12.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 12</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Stats Textbook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Chapter 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 4</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 5</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 6</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 7</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 8</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 9</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 10</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 11</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter12.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 12</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 13</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 14</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#predicting-an-outcome" id="toc-predicting-an-outcome" class="nav-link active" data-scroll-target="#predicting-an-outcome">Predicting an Outcome</a>
  <ul class="collapse">
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">12.1</span> Introduction</a></li>
  <li><a href="#fundamentals-of-linear-regression" id="toc-fundamentals-of-linear-regression" class="nav-link" data-scroll-target="#fundamentals-of-linear-regression"><span class="header-section-number">12.2</span> Fundamentals of Linear Regression  </a>
  <ul class="collapse">
  <li><a href="#what-makes-the-regression-line-the-best-fitting-line" id="toc-what-makes-the-regression-line-the-best-fitting-line" class="nav-link" data-scroll-target="#what-makes-the-regression-line-the-best-fitting-line"><span class="header-section-number">12.2.1</span> What Makes the Regression Line the Best-Fitting Line?  </a></li>
  </ul></li>
  </ul></li>
  <li><a href="#predicting-an-outcome-in-r" id="toc-predicting-an-outcome-in-r" class="nav-link" data-scroll-target="#predicting-an-outcome-in-r">Predicting an Outcome in R</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">1 Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#fit-simple-linear-regression" id="toc-fit-simple-linear-regression" class="nav-link" data-scroll-target="#fit-simple-linear-regression">1.1 Fit Simple Linear Regression</a></li>
  <li><a href="#assumptions-checking" id="toc-assumptions-checking" class="nav-link" data-scroll-target="#assumptions-checking">1.2 Assumptions Checking</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">2 Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#fit-multiple-linear-regression" id="toc-fit-multiple-linear-regression" class="nav-link" data-scroll-target="#fit-multiple-linear-regression">2.1 Fit Multiple Linear Regression</a></li>
  <li><a href="#multicollinearity-assumptions-checking" id="toc-multicollinearity-assumptions-checking" class="nav-link" data-scroll-target="#multicollinearity-assumptions-checking">2.2 Multicollinearity &amp; Assumptions Checking</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">3 Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#prepare-outcome-variable" id="toc-prepare-outcome-variable" class="nav-link" data-scroll-target="#prepare-outcome-variable">3.1 Prepare Outcome Variable</a></li>
  <li><a href="#fit-logistic-regression" id="toc-fit-logistic-regression" class="nav-link" data-scroll-target="#fit-logistic-regression">3.2 Fit Logistic Regression</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#predicting-the-outcomes-in-spss" id="toc-predicting-the-outcomes-in-spss" class="nav-link" data-scroll-target="#predicting-the-outcomes-in-spss">Predicting the outcomes in SPSS</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression-1" id="toc-simple-linear-regression-1" class="nav-link" data-scroll-target="#simple-linear-regression-1">1 Simple Linear Regression</a></li>
  <li><a href="#fit-simple-linear-regression-1" id="toc-fit-simple-linear-regression-1" class="nav-link" data-scroll-target="#fit-simple-linear-regression-1"><span class="header-section-number">12.3</span> 1.1 Fit Simple Linear Regression</a></li>
  <li><a href="#assumptions-checking-1" id="toc-assumptions-checking-1" class="nav-link" data-scroll-target="#assumptions-checking-1">1.2 Assumptions Checking</a></li>
  <li><a href="#multiple-linear-regression-1" id="toc-multiple-linear-regression-1" class="nav-link" data-scroll-target="#multiple-linear-regression-1">2 Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#fit-multiple-linear-regression-1" id="toc-fit-multiple-linear-regression-1" class="nav-link" data-scroll-target="#fit-multiple-linear-regression-1">2.1 Fit Multiple Linear Regression</a></li>
  <li><a href="#multicollinearity-assumptions-checking-1" id="toc-multicollinearity-assumptions-checking-1" class="nav-link" data-scroll-target="#multicollinearity-assumptions-checking-1">2.2 Multicollinearity &amp; Assumptions Checking</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 12</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="predicting-an-outcome" class="level1 unnumbered">
<h1 class="unnumbered">Predicting an Outcome</h1>
<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li><p>Explain the concepts of predictor and criterion variables, derive the equation of a regression line using the method of least squares, and interpret the slope and intercept within the context of data analysis.</p></li>
<li><p>Identify and assess the key assumptions for multiple regression, including linearity, homoscedasticity, independence of errors, multicollinearity, and model specification, ensuring valid and reliable results in regression analyses.</p></li>
<li><p>Compute and interpret diagnostic measures such as Variance Inflation Factors (VIF), tolerance, and the coefficient of determination (<span class="math inline">\(R^2\)</span>), and assess model fit to draw meaningful conclusions from regression analyses.</p></li>
</ul>
<p> </p>
</section>
<section id="introduction" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">12.1</span> Introduction</h2>
<p>In the last chapter, we reviewed the procedures to compute a correlation coefficient that indicates the extent to which two variables (<span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>) are related to each other. The value of r indicates the direction and strength of the relationship. Two variables change in opposite directions when r is negative, and two variables change in the same direction when r is positive. The closer r is to +1 or -1, the stronger the correlation and the more closely the two variables are related.  </p>
<p>The strength of a correlation reflects how closely a set of data points fits a line of best fit on a scatterplot. This line is also called a regression line. We will now learn how to use the value of r to compute the equation of a regression line. We will then use this equation to predict values of one variable given known values of a second variable in a population, before incorporating additional variables into our predictions.</p>
<p> </p>
</section>
<section id="fundamentals-of-linear-regression" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="fundamentals-of-linear-regression"><span class="header-section-number">12.2</span> Fundamentals of Linear Regression  </h2>
<p>Linear regression is a statistical method used to determine the equation of a regression line for a set of data points and to assess how well this equation can predict values of one variable based on known values of another variable. In linear regression, we identify two types of variables:</p>
<ul>
<li><p><strong>Predictor variable</strong>, or known variable (X), is the variable with values that are known and can be used to predict values of another variable. We also call this variable an independent variable (IV).  </p></li>
<li><p><strong>Criterion variable</strong>, or to-be-predicted variable (Y), is the variable with unknown values that can be predicted or estimated, given known values of the predictor variable. We sometimes call this variable a dependent variable (DV) or an outcome variable.    </p></li>
</ul>
<p>As always, it is important to consider the data assumptions that must be met before performing any analysis. We will provide more details on some of these assumptions later, but the conditions that indicate data are a good fit for regression analysis include:  </p>
<ul>
<li><p><em>Linearity of the X-Y relationship</em>: The relationship between the predictor and criterion variable should be linear.</p></li>
<li><p><em>No range restriction</em>: The range of data should not be artificially limited, as it can affect the correlation and regression results.</p></li>
<li><p><em>Homoscedasticity</em>: The variance of the residuals (errors) should be consistent across all values of the predictor variable.</p></li>
<li><p><em>No significant outliers</em>: Outliers can disproportionately influence the regression line and distort results.</p></li>
<li><p><em>Sufficient sample size</em>: The sample should be large enough to ensure that estimates of the correlation coefficient (<span class="math inline">\(r\)</span>) and regression coefficients (<span class="math inline">\(b\)</span>) are stable and reliable.</p></li>
</ul>
<p>Linear regression allows us to find the equation of a line that best describes a set of data points, and test whether predictions made from this equation are statistically significant. Before we work through an example to answer these questions, let us first explain what the regression line is. Specially, we want you to know what it means to say that a straight line has the best fit to the data.</p>
<section id="what-makes-the-regression-line-the-best-fitting-line" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="what-makes-the-regression-line-the-best-fitting-line"><span class="header-section-number">12.2.1</span> What Makes the Regression Line the Best-Fitting Line?  </h3>
<p>Once we have determined that there is a linear pattern in a set of data points using a scatterplot, we want to find a regression line, or a straight line that has the best fit. The criterion used to determine the regression line is sum of squares (<span class="math inline">\(SS\)</span>), or the sum of the squared distances of data points from a straight line. The line, associated with the smallest total value for SS, is the best-fitting straight line, called the regression line. Remember, we don’t square the distances just to be complicated, it’s so all the values are positive, even if the actual value is below the expected value. Otherwise, one point that was very far above the line would cancel out a point that was equally far below. Instead, we want them to both count as being quite far away from the line, so we square the distance. </p>
<p>Suppose that we measure two variables, one predictor or independent variable plotted on the X-axis, and one criterion or dependent variable plotted on the Y-axis. Figure 12.1 shows a scatterplot with five data points (A, B, C, D, and E) along with the line of best fit. The arrow from each data point to the line represents the distance from each data point to the best-fitting line. As you see, all data points deviate from the line to some extent. Data point D (below the line) has the largest deviation from the line and A (above the line) has the smallest. To quantify these deviations, we square each distance to ensure all values are positive. The sum of squares (SS) in this example is the total of these squared deviations across all five data points. The regression line is defined as the one that minimizes this sum, providing the best possible fit to the data.</p>
</section>
</section>
</section>
<section id="predicting-an-outcome-in-r" class="level1 unnumbered">
<h1 class="unnumbered">Predicting an Outcome in R</h1>
<p>In this section, we will demonstrate how to conduct and interpret simple linear regression, multiple linear regression, and logistic regression using educational data. The examples use the following variables from the PISA dataset:</p>
<ul>
<li><p><strong>PV1MATH</strong>: Math achievement score (continuous, outcome variable for linear regression)</p></li>
<li><p><strong>MATHPERS</strong>: Effort and Persistence in Mathematics (continuous, predictor for simple and multiple regression)</p></li>
<li><p><strong>GROSAGR</strong>: Growth Mindset (continuous, additional predictor for multiple regression)</p></li>
<li><p><strong>MATHEASE</strong>: Perception of Mathematics as easier than other subjects (binary (0=No/1-Yes), outcome for logistic regression)</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required package </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)       <span class="co"># For reading SPSS files </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)         <span class="co"># For VIF and diagnostics </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)       <span class="co"># For tidy model summaries </span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)       <span class="co"># For describe </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co"># For diagnostics </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection) <span class="co"># For logistic regression goodness-of-fit </span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset </span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">"chapter12/chapter12data.sav"</span>) </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean/select variables </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(PV1MATH, MATHPERS, GROSAGR, MATHEASE) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="simple-linear-regression" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="simple-linear-regression">1 Simple Linear Regression</h2>
<p><strong>Research Question</strong>: Does effort and persistence in mathematics (MATHPERS) predict math achievement (PV1MATH)?</p>
<section id="fit-simple-linear-regression" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fit-simple-linear-regression">1.1 Fit Simple Linear Regression</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>simple_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1MATH <span class="sc">~</span> MATHPERS, <span class="at">data =</span> data) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PV1MATH ~ MATHPERS, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-310.37  -68.50   -3.61   65.64  344.16 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   463.62       1.55  299.18   &lt;2e-16 ***
MATHPERS       16.13       1.52   10.61   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 94.06 on 3948 degrees of freedom
  (602 observations deleted due to missingness)
Multiple R-squared:  0.02773,   Adjusted R-squared:  0.02749 
F-statistic: 112.6 on 1 and 3948 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<p>The regression analysis found a significant positive relationship: for each one point increase in effort and persistence, math achievement scores increased by approximately 16.13 points (<span class="math inline">\(b=16.13,SE=1.52,t=10.61,p&lt;.01\)</span>).The model explained about 2.8% of the variance in math achievement (<span class="math inline">\(R^2 = .028\)</span>). The residual standard error was 94.06, indicating that, on average, students’ actual math scores deviated from the predicted scores by about 94 points. Although the effect size is modest, the result suggests that students who put in more effort and persist in mathematics tend to score higher on the PISA math achievement test.</p>
</section>
<section id="assumptions-checking" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="assumptions-checking">1.2 Assumptions Checking</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linearity, Homoscedasticity, Normality, Outliers </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simple_lm) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter12_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)) </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Additional: Independence is typically assumed in survey data </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Interpretation</strong>:</p>
<ul>
<li><p><strong>Linearity &amp; Homoscedasticity</strong>: The Residuals vs Fitted (upper left) and Scale-Location (lower left) plots show that residuals are roughly evenly spread around zero across fitted values, without clear patterns or fanning, suggesting linearity and constant variance (homoscedasticity).</p></li>
<li><p><strong>Normality</strong>: The Q-Q plot of residuals displays points closely following the diagonal line, indicating that residuals are approximately normally distributed.</p></li>
<li><p><strong>Influential Points</strong>: The Residuals vs Leverage plot shows that most points have low leverage, with no point deviating significantly from the rest, suggesting no influential outliers.</p></li>
</ul>
</section>
</section>
<section id="multiple-linear-regression" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="multiple-linear-regression">2 Multiple Linear Regression</h2>
<p>For the multiple linear regression, we will include both effort and persistence and growth mindset as predictors of math achievement.</p>
<p><strong>Research Question</strong>: Do effort and persistence (MATHPERS) and growth mindset (GROSAGR) jointly predict math achievement (PV1MATH)?</p>
<section id="fit-multiple-linear-regression" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fit-multiple-linear-regression">2.1 Fit Multiple Linear Regression</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>multi_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1MATH <span class="sc">~</span> MATHPERS <span class="sc">+</span> GROSAGR, <span class="at">data =</span> data) </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multi_lm) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PV1MATH ~ MATHPERS + GROSAGR, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-278.82  -65.05   -2.72   63.29  329.67 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  459.327      1.563 293.820   &lt;2e-16 ***
MATHPERS      13.740      1.506   9.121   &lt;2e-16 ***
GROSAGR       23.645      1.831  12.917   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 92.17 on 3929 degrees of freedom
  (620 observations deleted due to missingness)
Multiple R-squared:  0.06738,   Adjusted R-squared:  0.0669 
F-statistic: 141.9 on 2 and 3929 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<p>(Check section Reporting Results of a Multiple Regression Analysis for APA-style sample write-up)</p>
<p>The multiple linear regression show that both predictors have significant positive effects on math achievement: for each one point increase in effort and persistence, math scores increased by about 13.74 points (<span class="math inline">\(b=13.74,SE=1.51,p&lt;.01\)</span>), and for each one standard deviation increase in growth mindset, scores increased by about 23.65 points ($b=23.65,SE=1.83,p&lt;.01 <span class="math inline">\(). The model explained approximately 6.7% of the variance in math achievement scores (\)</span>R^2=.067$), with a residual standard error of 92.17.</p>
<p>Compared to the previous simple regression model that included only effort and persistence, adding growth mindset as a second predictor increased the proportion of explained variance from 2.8% to 6.7%. This suggests that considering both effort and growth mindset provides a better prediction of students’ math achievement.</p>
</section>
<section id="multicollinearity-assumptions-checking" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="multicollinearity-assumptions-checking">2.2 Multicollinearity &amp; Assumptions Checking</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(multi_lm) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>MATHPERS  GROSAGR 
1.015794 1.015794 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(multi_lm) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter12_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Interpretation</strong>:</p>
<p>VIFs for both predictors are approximately 1.02, which is well below the common threshold of 5. This indicates that multicollinearity is not a concern in this model, and the two predictors are not highly correlated with each other.</p>
<p>The diagnostic plots (as those for the simple linear regression) indicate that the assumptions of linearity, homoscedasticity, normality of residuals, and the absence of influential outliers are generally met for this multiple linear regression model.</p>
</section>
</section>
<section id="logistic-regression" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="logistic-regression">3 Logistic Regression</h2>
<p><strong>Research Question</strong>: Does math achievement (PV1MATH) predict whether a student perceives mathematics as easier than other subjects (MATHEASE)?</p>
<section id="prepare-outcome-variable" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="prepare-outcome-variable">3.1 Prepare Outcome Variable</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>MATHEASE <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>MATHEASE, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)) </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>MATHEASE <span class="sc">|&gt;</span> <span class="fu">table</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  No  Yes 
3497  501 </code></pre>
</div>
</div>
<p>Among the student sample, 3497 perceived mathematics as easier than other subjects, while 501 did not.</p>
</section>
<section id="fit-logistic-regression" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fit-logistic-regression">3.2 Fit Logistic Regression</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>logit_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(MATHEASE <span class="sc">~</span> PV1MATH, <span class="at">data =</span> data, <span class="at">family =</span> <span class="st">"binomial"</span>) </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_model)  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = MATHEASE ~ PV1MATH, family = "binomial", data = data)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -3.5726468  0.2505450 -14.260  &lt; 2e-16 ***
PV1MATH      0.0034039  0.0005017   6.785 1.16e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3017.5  on 3997  degrees of freedom
Residual deviance: 2971.0  on 3996  degrees of freedom
  (554 observations deleted due to missingness)
AIC: 2975

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Interpretation:</p>
<p>A logistic regression was conducted to examine whether students’ math scores predict the likelihood that they perceive mathematics as easier than other subjects. The results show a significant positive effect of math score (<span class="math inline">\(b=0.0034, SE=0.0005,z=6.79,p&lt;.01\)</span>). This means that for each point increase in the math score, the odds of perceiving math as easier increase by 0.34% (odds ratio: <span class="math inline">\(e^{0.0034} = 1.0034\)</span>). In other words, higher math achievement is associated with a slightly higher probability of perceiving math as easier than other subjects.</p>
</section>
</section>
</section>
<section id="predicting-the-outcomes-in-spss" class="level1 unnumbered">
<h1 class="unnumbered">Predicting the outcomes in SPSS</h1>
<p>In this section, we will demonstrate how to conduct and interpret simple linear regression, multiple linear regression, and logistic regression using educational data. The examples use the following variables from the PISA dataset:</p>
<ul>
<li><p><strong>PV1MATH</strong>: Math achievement score (continuous, outcome variable for linear regression)</p></li>
<li><p><strong>MATHPERS</strong>: Effort and Persistence in Mathematics (continuous, predictor for simple and multiple regression)</p></li>
<li><p><strong>GROSAGR</strong>: Growth Mindset (continuous, additional predictor for multiple regression)</p></li>
<li><p><strong>MATHEASE</strong>: Perception of Mathematics as easier than other subjects (binary (0=No/1-Yes), outcome for logistic regression)</p></li>
</ul>
<section id="simple-linear-regression-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="simple-linear-regression-1">1 Simple Linear Regression</h2>
<p><strong>Research Question</strong>: Does effort and persistence in mathematics (MATHPERS) predict math achievement (PV1MATH)?</p>
</section>
<section id="fit-simple-linear-regression-1" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="fit-simple-linear-regression-1"><span class="header-section-number">12.3</span> 1.1 Fit Simple Linear Regression</h2>
<p>To fit a simple linear regression model in SPSS, follow these steps:</p>
<ol type="1">
<li><p>Click Analyze &gt; Regression &gt; Linear…</p></li>
<li><p>Move PV1MATH to the Dependent box.</p></li>
<li><p>Move MATHPERS to the Independent(s) box.</p></li>
<li><p>Click Statistics… and check Estimates, Confidence intervals, Model fit, R squared change, and Descriptives.</p></li>
<li><p>Click Continue, then OK.</p></li>
</ol>
<p>Then you will get the following results:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-8.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 12.8</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-9.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 12.9</figcaption>
</figure>
</div>
<p><strong>Interpretation</strong>: The regression analysis found a significant positive relationship: for each one point increase in effort and persistence, math achievement scores increased by approximately 16.13 points (<span class="math inline">\(b=16.13, \,SE=1.52,\, t=10.61,\, p&lt;.05,\, 95\% \, CI [13.15, 19.11]\)</span>).The model explained about 2.8% of the variance in math achievement ( <span class="math inline">\(R^2 = .028\)</span>). The residual standard error was 94.06, indicating that, on average, students’ actual math scores deviated from the predicted scores by about 94 points. Although the effect size is modest, the result suggests that students who put in more effort and persist in mathematics tend to score higher on the PISA math achievement test.</p>
</section>
<section id="assumptions-checking-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="assumptions-checking-1">1.2 Assumptions Checking</h2>
<p>To check the regression assumptions in SPSS:</p>
<ol type="1">
<li><p>Go back to the Linear Regression dialog we used in</p></li>
<li><p>Click Plots…</p>
<p>Move *ZRESID (standardized residuals) to the Y box.</p>
<p>Move *ZPRED (standardized predicted values) to the X box.</p>
<p>Check Histogram and Normal probability plot.</p>
<p>Click Continue.</p></li>
<li><p>Click OK to generate the diagnostic plots.</p></li>
</ol>
<p>SPSS will produce the following plots:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-10.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 12.10</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-11.png" class="img-fluid figure-img" style="width:40.0%"></p>
<figcaption>Fig 12.11</figcaption>
</figure>
</div>
<p><img src="chapter12/fig12-12.png" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%" alt="Fig 12.12"> <strong>Interpretation</strong>:</p>
<p>The above figures separately suggest:</p>
<p>The <em>Histogram of Standardized Residuals</em> shows an approximately bell-shaped distribution centered at 0, supporting normality.</p>
<p>In the <em>Normal P-P Plot</em>, points follow the diagonal closely, confirming residuals are roughly <strong>normal</strong>. We can also see Standardized residuals all fall within <span class="math inline">\(\pm3\)</span>, suggesting no highly influential <strong>outliers</strong>.</p>
<p>In the <em>Scatterplot of Standardized Residuals vs.&nbsp;Predicted Values</em>, residuals are randomly scattered without a clear funnel pattern, suggesting <strong>linearity</strong> and <strong>homoscedasticity</strong>.</p>
<p>Overall, the model meets the assumptions of linearity, homoscedasticity, and normality of residuals, with no problematic outliers. The regression results can be interpreted with confidence.</p>
</section>
<section id="multiple-linear-regression-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="multiple-linear-regression-1">2 Multiple Linear Regression</h2>
<p>For the multiple linear regression, we will include both effort and persistence and growth mindset as predictors of math achievement.</p>
<p><strong>Research Question</strong>: Do effort and persistence (MATHPERS) and growth mindset (GROSAGR) jointly predict math achievement (PV1MATH)?</p>
<section id="fit-multiple-linear-regression-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fit-multiple-linear-regression-1">2.1 Fit Multiple Linear Regression</h3>
<p>To fit a multiple linear regression model in SPSS, follow the steps below:</p>
<ol type="1">
<li><p>Click Analyze &gt; Regression &gt; Linear…</p></li>
<li><p>Move PV1MATH to Dependent.</p></li>
<li><p>Move MATHPERS and GROSAGR to Independent(s).</p></li>
<li><p>Click Statistics… and check Estimates, Confidence intervals, Model fit, R squared change, Descriptives.</p></li>
<li><p>Click Continue and OK.</p></li>
</ol>
<p>Then you will get the following results:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-13.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 12.13</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-14.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 12.14</figcaption>
</figure>
</div>
<p><strong>Interpretation</strong>:</p>
<p>(Check section Reporting Results of a Multiple Regression Analysis for APA-style sample write-up)</p>
<p>The multiple linear regression show that both predictors have significant positive effects on math achievement: for each one point increase in effort and persistence, math scores increased by about 13.74 points ($b=13.74, ,SE=1.51, ,p&lt;.01 <span class="math inline">\(), and for each one standard deviation increase in growth mindset, scores increased by about 23.65 points (\)</span>b=23.65,, SE=1.83,, p&lt;.01<span class="math inline">\(). The model explained approximately 6.7% of the variance in math achievement scores (\)</span>R^2=.067$), with a residual standard error of 92.17.</p>
<p>Compared to the previous simple regression model that included only effort and persistence, adding growth mindset as a second predictor increased the proportion of explained variance from 2.8% to 6.7%. This suggests that considering both effort and growth mindset provides a better prediction of students’ math achievement.</p>
</section>
<section id="multicollinearity-assumptions-checking-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="multicollinearity-assumptions-checking-1">2.2 Multicollinearity &amp; Assumptions Checking</h3>
<p>To check the regression assumptions in SPSS:</p>
<ol type="1">
<li><p>Go back to the Linear Regression dialog used in 2.1.</p></li>
<li><p>Click Statistics… and make sure Collinearity diagnostics is checked.</p></li>
<li><p>Click Plots…</p>
<p>Move *ZRESID (standardized residuals) to the Y box.</p>
<p>Move *ZPRED (standardized predicted values) to the X box.</p>
<p>Check Histogram and Normal probability plot.</p>
<p>Click Continue.</p></li>
<li><p>Check Partial plots to see the linear relationship for each predictor controlling for the other.</p></li>
<li><p>Click OK to generate the diagnostic plots and the collinearity diagnostics table.</p></li>
</ol>
<p>SPSS will produce the following plots:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-15.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 12.15</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-16.png" class="img-fluid figure-img" style="width:40.0%"></p>
<figcaption>Fig 12.16</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-17.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 12.17</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-18.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 12.18</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-19.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 12.19</figcaption>
</figure>
</div>
<p><strong>Interpretation</strong>:</p>
<p>The above figures separately suggest:</p>
<p>The <em>Histogram of Standardized Residuals</em> shows an approximately bell-shaped distribution centered at 0, supporting the <strong>normality</strong> assumption.</p>
<p>The <em>Normal P-P Plot</em> shows points closely following the diagonal line, confirming that residuals are roughly <strong>normal</strong>.</p>
<p>In the <em>Scatterplot of Standardized Residuals vs.&nbsp;Predicted Values</em>, the residuals are randomly scattered without a clear funnel pattern, suggesting that the assumptions of <strong>linearity</strong> and <strong>homoscedasticity</strong> are basically satisfied.</p>
<p>The <em>partial regression plots</em> indicate that each predictor has an approximately <strong>linear</strong> relationship with the outcome after controlling for the other predictor. Standardized residuals all fall within <span class="math inline">\(\pm3\)</span>, suggesting no highly influential <strong>outliers</strong>.</p>
<p>In addition, the <em>Collinearity Diagnostics table</em> shows VIF values near 1, below common threshold of 5, indicating no concern for <strong>multicollinearity</strong>.</p>
<p>Overall, the multiple regression model meets the assumptions of linearity, homoscedasticity, and normality of residuals, with no problematic outliers or multicollinearity concerns. The regression results can be interpreted with confidence.</p>
<p>3 Logistic Regression</p>
<p><strong>Research Question</strong>: Does math achievement (PV1MATH) predict whether a student perceives mathematics as easier than other subjects (MATHEASE)?</p>
<p>To fit a logistic regression model in SPSS, follow the steps below:</p>
<ol type="1">
<li><p>Click Analyze &gt; Regression &gt; Binary Logistic…</p></li>
<li><p>Move MATHEASE to Dependent.</p></li>
<li><p>Move PV1MATH to Covariates.</p></li>
<li><p>Click Options… to select CI for exp(B) and Hosmer-Lemeshow goodness-of-fit.</p></li>
<li><p>Click Continue and OK.</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter12/fig12-20.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 12.20</figcaption>
</figure>
</div>
<p><strong>Interpretation</strong>:</p>
<p>A logistic regression was conducted to examine whether students’ math scores predict the likelihood that they perceive mathematics as easier than other subjects. The results show a significant positive effect of math score (<span class="math inline">\(b=0.003, \, SE=0.001, \, Wald \, \eta^2²=46.036, \,p&lt;.01\)</span>). This means that for each point increase in the math score, the odds of perceiving math as easier increase by 0.3% (odds ratio: <span class="math inline">\(e^{0.003} = 1.003\)</span>). In other words, higher math achievement is associated with a slightly higher probability of perceiving math as easier than other subjects.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter11.html" class="pagination-link" aria-label="Chapter 11">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 11</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter13.html" class="pagination-link" aria-label="Chapter 13">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 13</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>