<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Chapter 9 – Stats Textbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter10.html" rel="next">
<link href="./chapter8.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f2c6d6e2b784ddc5de38779acc06f37d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter9.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 9</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Stats Textbook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Chapter 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 4</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 5</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 6</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 7</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 8</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter9.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 9</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 10</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 11</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 12</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 13</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 14</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#analyzing-differences-between-two-groups" id="toc-analyzing-differences-between-two-groups" class="nav-link active" data-scroll-target="#analyzing-differences-between-two-groups">Analyzing Differences Between Two Groups </a>
  <ul class="collapse">
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#types-of-t-tests" id="toc-types-of-t-tests" class="nav-link" data-scroll-target="#types-of-t-tests"><span class="header-section-number">9.1</span> Types of <span class="math inline">\(t\)</span> Tests</a>
  <ul class="collapse">
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test"><span class="header-section-number">9.1.1</span> One-sample t test</a></li>
  <li><a href="#two-independent-samples-t-test" id="toc-two-independent-samples-t-test" class="nav-link" data-scroll-target="#two-independent-samples-t-test"><span class="header-section-number">9.1.2</span> Two-independent-samples t test</a></li>
  <li><a href="#related-samples-t-test" id="toc-related-samples-t-test" class="nav-link" data-scroll-target="#related-samples-t-test"><span class="header-section-number">9.1.3</span> Related-samples t test</a></li>
  </ul></li>
  <li><a href="#overview-of-the-two-independent-samples-t-test" id="toc-overview-of-the-two-independent-samples-t-test" class="nav-link" data-scroll-target="#overview-of-the-two-independent-samples-t-test"><span class="header-section-number">9.2</span> Overview of the Two-Independent-Samples t Test</a>
  <ul class="collapse">
  <li><a href="#step-1-determine-the-null-and-alternative-hypotheses." id="toc-step-1-determine-the-null-and-alternative-hypotheses." class="nav-link" data-scroll-target="#step-1-determine-the-null-and-alternative-hypotheses.">Step 1: Determine the null and alternative hypotheses.</a></li>
  <li><a href="#step-2-set-the-criteria-for-a-decision." id="toc-step-2-set-the-criteria-for-a-decision." class="nav-link" data-scroll-target="#step-2-set-the-criteria-for-a-decision.">Step 2: Set the criteria for a decision.</a></li>
  <li><a href="#step-3-check-assumptions-and-compute-the-test-statistic." id="toc-step-3-check-assumptions-and-compute-the-test-statistic." class="nav-link" data-scroll-target="#step-3-check-assumptions-and-compute-the-test-statistic.">Step 3: Check assumptions and compute the test statistic. </a></li>
  <li><a href="#step-4a-find-the-p-value." id="toc-step-4a-find-the-p-value." class="nav-link" data-scroll-target="#step-4a-find-the-p-value.">Step 4a: Find the p value. </a></li>
  <li><a href="#step-4b-draw-a-conclusion-and-report-your-conclusion." id="toc-step-4b-draw-a-conclusion-and-report-your-conclusion." class="nav-link" data-scroll-target="#step-4b-draw-a-conclusion-and-report-your-conclusion.">Step 4b: Draw a conclusion and report your conclusion.  </a></li>
  </ul></li>
  <li><a href="#effect-size-for-the-independent-samples-t-test" id="toc-effect-size-for-the-independent-samples-t-test" class="nav-link" data-scroll-target="#effect-size-for-the-independent-samples-t-test"><span class="header-section-number">9.3</span> Effect Size for the Independent-Samples <span class="math inline">\(t\)</span> Test</a></li>
  <li><a href="#overview-of-the-related-samples-t-test" id="toc-overview-of-the-related-samples-t-test" class="nav-link" data-scroll-target="#overview-of-the-related-samples-t-test"><span class="header-section-number">9.4</span> Overview of the Related-Samples <span class="math inline">\(t\)</span> Test</a>
  <ul class="collapse">
  <li><a href="#step-1-determine-the-null-and-alternative-hypotheses.-1" id="toc-step-1-determine-the-null-and-alternative-hypotheses.-1" class="nav-link" data-scroll-target="#step-1-determine-the-null-and-alternative-hypotheses.-1">Step 1: Determine the null and alternative hypotheses.</a></li>
  <li><a href="#step-2-set-the-criteria-for-a-decision.-1" id="toc-step-2-set-the-criteria-for-a-decision.-1" class="nav-link" data-scroll-target="#step-2-set-the-criteria-for-a-decision.-1">Step 2: Set the criteria for a decision.</a></li>
  <li><a href="#step-3-check-assumptions-and-compute-the-test-statistic.-1" id="toc-step-3-check-assumptions-and-compute-the-test-statistic.-1" class="nav-link" data-scroll-target="#step-3-check-assumptions-and-compute-the-test-statistic.-1">Step 3: Check assumptions and compute the test statistic. </a></li>
  <li><a href="#step-4a-find-the-p-value.-1" id="toc-step-4a-find-the-p-value.-1" class="nav-link" data-scroll-target="#step-4a-find-the-p-value.-1">Step 4a: Find the p value.</a></li>
  <li><a href="#step-4b-draw-a-conclusion-and-report-your-conclusion.-1" id="toc-step-4b-draw-a-conclusion-and-report-your-conclusion.-1" class="nav-link" data-scroll-target="#step-4b-draw-a-conclusion-and-report-your-conclusion.-1">Step 4b: Draw a conclusion and report your conclusion.  </a></li>
  </ul></li>
  <li><a href="#effect-size-for-related-samples-t-tests" id="toc-effect-size-for-related-samples-t-tests" class="nav-link" data-scroll-target="#effect-size-for-related-samples-t-tests"><span class="header-section-number">9.5</span> Effect Size for Related-Samples <span class="math inline">\(t\)</span> Tests</a></li>
  <li><a href="#comparing-two-groups-with-ordinal-data-nonparametric-tests" id="toc-comparing-two-groups-with-ordinal-data-nonparametric-tests" class="nav-link" data-scroll-target="#comparing-two-groups-with-ordinal-data-nonparametric-tests"><span class="header-section-number">9.6</span> Comparing Two Groups with Ordinal Data: Nonparametric Tests</a></li>
  <li><a href="#choosing-between-parametric-and-nonparametric-tests" id="toc-choosing-between-parametric-and-nonparametric-tests" class="nav-link" data-scroll-target="#choosing-between-parametric-and-nonparametric-tests"><span class="header-section-number">9.7</span> Choosing between Parametric and Nonparametric Tests</a></li>
  <li><a href="#two-independent-sample-mann-whitney-u-test" id="toc-two-independent-sample-mann-whitney-u-test" class="nav-link" data-scroll-target="#two-independent-sample-mann-whitney-u-test"><span class="header-section-number">9.8</span> Two Independent-Sample Mann-Whitney <span class="math inline">\(U\)</span> Test</a></li>
  <li><a href="#wilcoxons-matched-pairs-signed-ranks-test" id="toc-wilcoxons-matched-pairs-signed-ranks-test" class="nav-link" data-scroll-target="#wilcoxons-matched-pairs-signed-ranks-test"><span class="header-section-number">9.9</span> Wilcoxon’s Matched-Pairs Signed-Ranks Test</a></li>
  </ul></li>
  <li><a href="#analyzing-differences-between-two-groups-in-r" id="toc-analyzing-differences-between-two-groups-in-r" class="nav-link" data-scroll-target="#analyzing-differences-between-two-groups-in-r">Analyzing Differences Between Two Groups in R</a>
  <ul class="collapse">
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">1 Data Exploration</a></li>
  <li><a href="#two-independent-sample-t-test" id="toc-two-independent-sample-t-test" class="nav-link" data-scroll-target="#two-independent-sample-t-test">2 Two Independent-Sample t Test</a>
  <ul class="collapse">
  <li><a href="#define-hypothesis" id="toc-define-hypothesis" class="nav-link" data-scroll-target="#define-hypothesis">2.1 Define Hypothesis</a></li>
  <li><a href="#conduct-the-test" id="toc-conduct-the-test" class="nav-link" data-scroll-target="#conduct-the-test">2.2 Conduct the Test</a></li>
  <li><a href="#effect-size-cohens-d" id="toc-effect-size-cohens-d" class="nav-link" data-scroll-target="#effect-size-cohens-d">2.3 Effect Size (Cohen’s <span class="math inline">\(d\)</span>)</a></li>
  </ul></li>
  <li><a href="#two-independent-sample-mann-whitney-u-test-1" id="toc-two-independent-sample-mann-whitney-u-test-1" class="nav-link" data-scroll-target="#two-independent-sample-mann-whitney-u-test-1">3 Two Independent-Sample Mann-Whitney U Test</a></li>
  </ul></li>
  <li><a href="#analyzing-differences-between-two-groups-in-spss" id="toc-analyzing-differences-between-two-groups-in-spss" class="nav-link" data-scroll-target="#analyzing-differences-between-two-groups-in-spss">Analyzing Differences Between Two Groups in SPSS</a>
  <ul class="collapse">
  <li><a href="#data-exploration-1" id="toc-data-exploration-1" class="nav-link" data-scroll-target="#data-exploration-1">1 Data Exploration</a></li>
  <li><a href="#two-independent-sample-t-test-1" id="toc-two-independent-sample-t-test-1" class="nav-link" data-scroll-target="#two-independent-sample-t-test-1">2 Two Independent-Sample t Test</a>
  <ul class="collapse">
  <li><a href="#define-hypothesis-1" id="toc-define-hypothesis-1" class="nav-link" data-scroll-target="#define-hypothesis-1">2.1 Define Hypothesis</a></li>
  <li><a href="#conduct-the-test-1" id="toc-conduct-the-test-1" class="nav-link" data-scroll-target="#conduct-the-test-1">2.2 Conduct the Test</a></li>
  </ul></li>
  <li><a href="#two-independent-sample-mann-whitney-u-test-2" id="toc-two-independent-sample-mann-whitney-u-test-2" class="nav-link" data-scroll-target="#two-independent-sample-mann-whitney-u-test-2">3 Two Independent-Sample Mann-Whitney U Test</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#key-takeaways-for-educational-researchers-from-chapter-9" id="toc-key-takeaways-for-educational-researchers-from-chapter-9" class="nav-link" data-scroll-target="#key-takeaways-for-educational-researchers-from-chapter-9">Key Takeaways for Educational Researchers from Chapter 9</a></li>
  <li><a href="#key-definitions-from-chapter-9" id="toc-key-definitions-from-chapter-9" class="nav-link" data-scroll-target="#key-definitions-from-chapter-9">Key Definitions from Chapter 9</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding">Check Your Understanding</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 9</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="analyzing-differences-between-two-groups" class="level1 unnumbered">
<h1 class="unnumbered">Analyzing Differences Between Two Groups </h1>
<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li><p>Identify and differentiate between different types of tests to compare two groups, understanding their appropriate applications based on the nature of the data and comparisons being made.</p></li>
<li><p>Understand differences between parametric and nonparametric tests.</p></li>
<li><p>Explain the logic behind conducting independent - and related-samples t tests on continuous variables, including verifying assumptions, calculating the test statistic, and interpreting results within the context of hypothesis testing.</p></li>
<li><p>Apply the Mann-Whitney <span class="math inline">\(U\)</span> test and Wilcoxon’s Matched-Pairs Signed-Ranks Test, demonstrating an understanding of their logic, appropriate use cases, and result interpretation.</p></li>
<li><p>Evaluate the practical significance of statistical results using measures such as Cohen’s <span class="math inline">\(d\)</span> and eta-squared, providing context for the findings of t test analyses.</p></li>
</ul>
<p>In the previous chapter, we explored the one-sample <span class="math inline">\(t\)</span> test, a method used to compare a single group’s mean to a known population mean. This gave us the foundation for understanding how <span class="math inline">\(t\)</span> tests work and their role in hypothesis testing. Now, we are moving on to explore additional types of <span class="math inline">\(t\)</span> tests to compare two groups. Before diving into the details of the independent-samples <span class="math inline">\(t\)</span> test, which is commonly used in educational research, let’s take a brief look at three types of <span class="math inline">\(t\)</span> tests. These include the one-sample <span class="math inline">\(t\)</span> test (covered in chapter 8), two independent-samples <span class="math inline">\(t\)</span> test, and two related-samples <span class="math inline">\(t\)</span> test, each tailored to different types of comparisons. Understanding the distinctions between these tests will help clarify when and how to use them effectively.</p>
</section>
<section id="types-of-t-tests" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="types-of-t-tests"><span class="header-section-number">9.1</span> Types of <span class="math inline">\(t\)</span> Tests</h2>
<p>All three types of t tests involve comparing the values of a variable from one group of individuals to something else – and that <em>something else</em> tells you what kind of t test you should use. To explain the three tests, imagine that you have a class of third grade students, and you have a list of each student’s reading achievement scores. The following table explains how you might analyze those scores with each type of t test, depending on what you’re comparing them to.</p>
<div class="formula-table">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>What to Compare</th>
<th>T-Test Used</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>One single number</strong></td>
<td>One-sample <em>t</em> test</td>
<td>You want to see if this group’s scores are, on average, significantly different from the state average for reading achievement scores.</td>
</tr>
<tr class="even">
<td><strong>A different group’s scores on the same variable</strong></td>
<td>Two-independent-samples <em>t</em> test</td>
<td>You want to compare this group’s reading achievement scores to those from another third-grade class.</td>
</tr>
<tr class="odd">
<td><strong>The same group’s scores on a different variable<br>or at a different time</strong></td>
<td>Two related-samples <em>t</em> test</td>
<td>You want to compare this group’s reading scores to their math achievement scores, to see if their achievement levels are different across the two subjects.<br><br><strong>OR</strong><br><br>You want to compare this group’s reading scores after third grade to the same group’s reading scores after fourth grade, to see if they change over time.</td>
</tr>
</tbody>
</table>
</div>
<p>Now, we will provide a very brief overview of each type.</p>
<section id="one-sample-t-test" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="one-sample-t-test"><span class="header-section-number">9.1.1</span> One-sample t test</h3>
<p>This should be very familiar since we just learned it in the last chapter. You use this t test if you know the population mean (<span class="math inline">\(\mu\)</span>), but you do not know the population standard deviation (<span class="math inline">\(\sigma\)</span>). You are trying to find out if your sample mean (<span class="math inline">\(\bar{X}\)</span>) is significantly different from a known population mean. To run this analysis, we will use only one continuous variable or column of data – each individual in the group has one value or score for the variable of interest.</p>
</section>
<section id="two-independent-samples-t-test" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="two-independent-samples-t-test"><span class="header-section-number">9.1.2</span> Two-independent-samples t test</h3>
<p>Commonly in practice, you do not know a population mean to use as a comparison point. You are instead comparing sets of numbers obtained from two separate groups in order to draw inferences about their populations. Maybe you have two groups of students, one of which received some kind of intervention, and you want to compare end-of-year achievement scores between them. You might want to know if female college students have higher GPAs than male students. This time, your dataset will need two columns to run the test: one to indicate which group the individual is in, and one with their value for the dependent variable.</p>
</section>
<section id="related-samples-t-test" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="related-samples-t-test"><span class="header-section-number">9.1.3</span> Related-samples t test</h3>
<p>You are still comparing two sets of numbers, but this time both sets belong to the same people or two groups that are somewhat related. For example, you might be comparing achievement scores at the beginning and end of a year to see if a class improved. You might also compare outcomes under two different conditions, such as how many times students were absent when class met in-person compared to the number of absences for the same students when the school shifted to remote learning. Instead of having the same group of people, you sometimes have a matched group (e.g., siblings or a set of individuals who have been matched based on their scores on other variables). Either way, your dataset will look different yet again. Like with the one-sample t test, you only have a single list of individuals or a single set of matched pairs. However, this time they each have two columns of information (e.g., pre-test and post-test scores, or English scores and math scores).</p>
<p>We hope this helps you avoid getting confused about the three different types of t tests. The details for how to conduct each analysis are similar but there are important differences. The names are actually pretty good clues:</p>
<ul>
<li><p><em>One</em>-sample: you only have one set of data (e.g., a set of reading scores from a sample of third graders), so you need a population value (e.g., the national average of reading score) for comparison.</p></li>
<li><p>Two <em>independent</em>-samples: you have two distinct groups that are not related or connected in any way – one might even say they are two independent groups. Membership in a group is mutually exclusive, meaning that no individual or case can belong to both groups simultaneously.</p></li>
<li><p>Two <em>related</em>-samples (also known as paired-sample or repeated-measures test): here you have two sets of numbers that are connected – either the same people at different times or different conditions, or people who are paired together.</p></li>
</ul>
<p>And now we will dive into the details of the independent-samples t test. This is probably one of the most used methods to compare two groups in educational research.</p>
</section>
</section>
<section id="overview-of-the-two-independent-samples-t-test" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="overview-of-the-two-independent-samples-t-test"><span class="header-section-number">9.2</span> Overview of the Two-Independent-Samples t Test</h2>
<p>As we did when learning about the one-sample t test, let’s again walk through an example from educational research. Similar to the previous example, the teacher is now concerned if her class average of English Language Arts (ELA) scores (<span class="math inline">\(\bar{X} = 425.26, SD = 44.99\)</span>) is significantly different from another class of third graders whose teacher joined the pilot implementation of a new reading intervention. When the result was returned the class average of the fellow teacher was 440 with a SD of 35. Are these two averages significantly different? Let’s find out.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9.1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter9_files/figure-html/fig-9.1-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Figure 9.1. Overlapping histograms of ELA scores for two third-grade classes
</figcaption>
</figure>
</div>
</div>
</div>
<p>Similar to the previous one-sample t test example, we will complete four steps of hypothesis testing.</p>
<section id="step-1-determine-the-null-and-alternative-hypotheses." class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-1-determine-the-null-and-alternative-hypotheses.">Step 1: Determine the null and alternative hypotheses.</h3>
<p>With a one-sample test, the null hypothesis states there is no difference between the sample mean and the population mean. We are now comparing the means of two independent samples, to determine statistically if their population means are identical or different. So, the null hypothesis about population means is that there is no difference between the population means of the two groups. The way we indicate is that one population mean (<span class="math inline">\(\mu_1\)</span> for Group 1) minus the other (<span class="math inline">\(\mu_2\)</span> for Group 2) is zero.</p>
<p><span class="math display">\[
H_0: \mu_1− \mu_2=0
\]</span></p>
<p>Therefore, the alternative hypothesis is that there is a difference between the two groups:</p>
<p><span class="math display">\[
H_A: \mu_1− \mu_2\ne 0
\]</span></p>
<p>Note that this is the alternative hypothesis for a two-sided or two-tailed test. We are not assuming that one mean is larger than the other, just that they are different. If you had reason to believe that one group mean would be larger than the other, your alternative hypothesis would be:</p>
<p><span class="math display">\[
H_A: \mu_1 &gt; \mu_2
\]</span></p>
<p>or</p>
<p><span class="math display">\[
H_A: \mu_1 &lt; \mu_2
\]</span></p>
</section>
<section id="step-2-set-the-criteria-for-a-decision." class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-2-set-the-criteria-for-a-decision.">Step 2: Set the criteria for a decision.</h3>
<p>The next step in testing the null hypothesis is to set the criteria for a decision: how much of a difference is significant enough that we can conclude it is not only due to random chance? We decide that <span class="math inline">\(\alpha = 0.05\)</span> as usual, but the degrees of freedom are slightly different for an independent-samples t test compared to a one-sample t test. This time, we must subtract one from each group, so <span class="math inline">\(df = (n_1 − 1)+(n_2 − 1) = n_1 + n_2−2 = N - 2\)</span>, where <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> refer to the sample size of Group 1 and Group 2, respectively, and <span class="math inline">\(N\)</span> refers to the total number of subjects in both groups combined.</p>
<p>Flip to the Critical Values of <span class="math inline">\(t\)</span> Distribution Table at the back of the book like before, looking for the intersection between your alpha level and your degrees of freedom to find the critical value. For our example, both groups have a sample size of <span class="math inline">\(35\)</span> so the <span class="math inline">\(df  = 70 - 2 = 68\)</span>. Since we don’t have <span class="math inline">\(df = 68\)</span>, round down to <span class="math inline">\(50\)</span> df to be conservative. The critical <span class="math inline">\(t\)</span> value associated with 50 df at <span class="math inline">\(\alpha = 0.05\)</span> for a two-tailed test is <span class="math inline">\(\pm2.009\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9.2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter9_files/figure-html/fig-9.2-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: t-distribution with two-tailed rejection regions
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="step-3-check-assumptions-and-compute-the-test-statistic." class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-3-check-assumptions-and-compute-the-test-statistic.">Step 3: Check assumptions and compute the test statistic. </h3>
<p>The third step has a few parts. First, we verify that our data meet the assumptions required for this method of analysis, and then we calculate the test statistic. The assumptions for an independent-samples t test are:</p>
<ul>
<li><p>Normality: The dependent variable is approximately normally distributed (as before, this requirement is less important if n &gt; 30).</p></li>
<li><p>Random sampling: You are using a random sample of independent observations.</p></li>
<li><p>Independence: The scores are independent of one another.</p></li>
<li><p>Equal variances: The variances of the dependent variable are equal across two groups or populations being compared.</p></li>
</ul>
<p>Equal variance is new, but it is important to keep in mind for this method. Remember earlier in the book when we said means are important and so is standard deviation (or variance, which is the same basic concept)? Here is one place where that comes into play. Imagine you are comparing scores of two groups on the same test. In one group, all scores are tightly clustered near the mean. In the other group, they are completely spread out with a much wider range than compared to the first group. It is harder to make a solid conclusion about the differences between two group means when the distributions are completely different.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9.3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter9_files/figure-html/fig-9.3-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: Normal distributions with equal vs.&nbsp;unequal variances
</figcaption>
</figure>
</div>
</div>
</div>
<p>When analyzing data from two groups, it is essential to compute and evaluate the size of variance for each group. This helps in understanding the spread of the data and determining if the variances are similar or different. Drawing histograms for each group is particularly useful for visually inspecting the data spread and identifying any noticeable differences between two distributions.</p>
<section id="levenes-test-for-assessing-equal-variances" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="levenes-test-for-assessing-equal-variances">Levene’s Test for Assessing Equal Variances</h4>
<p><strong>Levene’s Test</strong> is a statistical procedure used to assess whether the variances of a dependent variable are equal across different groups. This test is typically performed before conducting analyses that assume equal variances, such as t tests or ANOVA, to determine if this assumption holds. We won’t show you how to calculate Levene’s Test by hand because statistical software packages will do this for you.</p>
<p>However, the important thing to remember is that if the result of Levene’s Test is statistically significant <span class="math inline">\((p &lt; .05)\)</span>, your variances are <em>not equal</em>. If your variances are not equal, you should consider using a different test that we will learn later or, at minimum, report the statistical results adjusted for unequal variances between two groups, which is provided by most software packages as well. If your Levene’s Test results are not statistically significant <span class="math inline">\((p &gt; .05)\)</span>, your group variances are considered equal.</p>
</section>
</section>
<section id="step-4a-find-the-p-value." class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-4a-find-the-p-value.">Step 4a: Find the p value. </h3>
<p>Next, we calculate the test statistic. We are going to show you the formula first, but please don’t panic. It is not as bad as it seems.</p>
<p><span class="math display">\[
t = \frac{(\bar{X}_1-\bar{X}_2)-(\mu_1-\mu_2)}{\sqrt{s_p^2(\frac{1}{n_1}+\frac{1}{n_2})}}
\]</span></p>
<p>Let’s take that a little at a time, starting with the numerator. The first part is the difference between group means in your sample. Then we are comparing that to the expected difference between group means in the population (i.e., the mean differences specified in the null hypothesis). Look back at the null hypothesis for this type of test. What is the expected difference between group means in the population? Zero! For practical purposes, the top half of the fraction is just the difference between group means.</p>
<p>Do you remember what was in the denominator of the t statistic for a one-sample t test? It was the standard error, or the sample standard deviation divided by the square root of the sample size. This denominator is more complicated because we have two separate groups. Under the null hypothesis, we assume that both sample groups came from the same population, but most likely the standard errors are not exactly the same. So which sample variance do we use as an estimate for the population variance? The optimal solution is to make full use of the variance estimates from both samples to obtain a more accurate estimate of the population variance.</p>
<p>There is another new value in the denominator, <span class="math inline">\(s_p^2\)</span> ,</p>
<p>which represents the pooled sample variance. The formula for this looks very complicated, but it is just a way of weighting the two sample variances by the sample size. If one group is bigger than the other, their sample variance is weighted more heavily by this formula. If you notice this looks a little different from what you might find elsewhere, that is because we are being more specific about how you get to the degrees of freedom, with n – 1.</p>
<p><span class="math display">\[
s_p^2 = \frac{(n_1 − 1)s_1^2 + (n_2 − 1)s_2^2}{(n_1+ n_2)−2}
\]</span></p>
<p>What does all that mean? You are multiplying the sample variance for group one by the degrees of freedom for group one and adding that to the same thing for group two. Then you are dividing the outcome by the degrees of freedom for the whole test. In our example, the sample size of each group is 35. Thus,</p>
<p><span class="math display">\[
s_p^2 = \frac{(34)s_1^2 + (34)s_2^2}{68}
\]</span></p>
<p>Now you have a measure of sample variance that you can use for the whole combined sample of both groups. If both groups have the same sample size, like our example, there is a much simpler version of the formula you can use.</p>
<p><span class="math display">\[
s_p^2 = \frac{s_1^2 + s_2^2}{2}
\]</span></p>
<p>In our example, <span class="math inline">\(s_1^2 = (44.99)^2\)</span>, and <span class="math inline">\(s_2^2 = (35)^2\)</span>. Let’s plug in these values and compute the <span class="math inline">\(s_p^2\)</span></p>
<p><span class="math display">\[
s_p^2 = \frac{s_1^2 + s_2^2}{2} = \frac{(44.99)^2 + (35)^2}{2} = 1624.55
\]</span></p>
<p>Either way, once you have the value for <span class="math inline">\(s_p^2\)</span>, you bring that back to the <span class="math inline">\(t\)</span> statistic formula and do what we always do: standard deviation divided by the square root of the sample size. It just looks more complicated when we have two separate sample sizes, and because this formula starts with sample variance and then takes the square root, rather than starting with standard deviation, which is already the square root of the variance.</p>
<p><span class="math display">\[
t = \frac{(\bar{X}_1-\bar{X}_2)-(\mu_1-\mu_2)}{\sqrt{s_p^2(\frac{1}{n_1}+\frac{1}{n_2})}}
= \frac{(425.26−440)−0}{\sqrt{1624.55(\frac{1}{35}+\frac{1}{35})}}
= \frac{-14.74}{9.634}
= -1.53
\]</span></p>
<p>If you are completely lost, try not to get too caught up in the math and focus on the concept. We are finding the difference between the two group means and dividing it by the standard error for the difference. It is just more complicated to calculate this version of standard error than it has been for other tests. The good news is that statistical software programs will do the math for you.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9.4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter9_files/figure-html/fig-9.4-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.4: Two-tailed t-test with critical values
</figcaption>
</figure>
</div>
</div>
</div>
<p>The last step in testing a hypothesis is more straightforward: compare the value of the <span class="math inline">\(t\)</span> statistic you just calculated to the critical value you identified in step-two. If the <span class="math inline">\(t\)</span> statistic is larger, meaning farther out from the center of the distribution in either direction, then a significant difference exists between the groups.</p>
<p>In this example, the observed <span class="math inline">\(t\)</span> value is <span class="math inline">\(= -1.53\)</span> which is greater than the lower critical <span class="math inline">\(t\)</span> value of <span class="math inline">\(-2.009\)</span>. Therefore, we fail to reject the null hypothesis. The actual <span class="math inline">\(p\)</span> value for <span class="math inline">\(t = -1.53\)</span> in a two-tail test is <span class="math inline">\(0.131\)</span>.</p>
</section>
<section id="step-4b-draw-a-conclusion-and-report-your-conclusion." class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-4b-draw-a-conclusion-and-report-your-conclusion.">Step 4b: Draw a conclusion and report your conclusion.  </h3>
<p>Since we failed to reject the null hypothesis, which states that there is no difference in population means of the two groups, we conclude that the ELA classroom averages taught by two different teachers are not significantly different. The observed mean difference between two groups is simply by chance due to sampling. Note that we do not calculate the effect size to assess practical significance, as no statistically significant difference was found.</p>
<p>How might we report the result in APA style? An independent-samples t test was conducted to compare ELA classroom averages between students taught by two different teachers. The results indicated that there was no statistically significant difference in classroom averages between the two groups, <span class="math inline">\(t(68) = 1.53, p = .131\)</span>, suggesting that the mean ELA classroom scores for students in these two classrooms are comparable.</p>
</section>
</section>
<section id="effect-size-for-the-independent-samples-t-test" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="effect-size-for-the-independent-samples-t-test"><span class="header-section-number">9.3</span> Effect Size for the Independent-Samples <span class="math inline">\(t\)</span> Test</h2>
<p>If you find a significant difference, you should calculate the effect size. We most commonly report effect size for this method using estimated Cohen’s d.&nbsp;If you remember back to chapter 8, Cohen’s d quantifies the magnitude of the difference between two means relative to the variability in the data. Similarly, we can use Cohen’s d as a standardized measure of practical significance, helping to interpret the importance of the result. However, the formula for Cohen’s d that you use for an independent-sample t test is slightly different from what we have already learned:</p>
<p><span class="math display">\[
d=\frac{M_1-M_2}{\sqrt{s_p^2}}
\]</span></p>
<p>The numerator is just the difference in sample means, and the denominator is the pooled sample standard deviation; you can find the formula earlier in the chapter.</p>
<p>Eta-squared (<span class="math inline">\(\eta^2\)</span>) is another measure of effect size used to quantify the proportion of variance in a dependent variable that is associated with one or more independent variables in an analysis. It provides an estimate of how much of the variability in the dependent variable is explained by the grouping variable. Eta-squared can be calculated using the following formula:</p>
<p><span class="math display">\[
\eta^2=\frac{t^2}{t^2+df}
\]</span></p>
<p>Where:</p>
<ul>
<li><p><span class="math inline">\(t^2\)</span> is the square of the t test statistic.</p></li>
<li><p><span class="math inline">\(df\)</span> is the degrees of freedom for the test.</p></li>
</ul>
<p>Either way, you only report effect size if you find a significant result when conducting your hypothesis test.</p>
</section>
<section id="overview-of-the-related-samples-t-test" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="overview-of-the-related-samples-t-test"><span class="header-section-number">9.4</span> Overview of the Related-Samples <span class="math inline">\(t\)</span> Test</h2>
<p>We have finally arrived at the last type of t test, and to make things extra interesting, it goes by several different names depending on how you are using it.</p>
<p><strong>Related-samples <span class="math inline">\(t\)</span> test</strong> is typically used as a general term for a <span class="math inline">\(t\)</span> test that involves comparisons of related or dependent groups. Additionally, it is used when you have the same participants measured on two dependent variables that use the same or comparable scales, such as math vs reading tests. For example, a researcher may examine whether there is a significant difference between students’ performance on standardized tests in two subjects.</p>
<p>Two specific types of the related-samples <span class="math inline">\(t\)</span> test are often used in research, each corresponding to a particular research design:</p>
<ul>
<li><p><strong>Repeated-measures <span class="math inline">\(t\)</span> test</strong> is used when we measure one group of participants twice on the same or comparative measure at different points in time. In educational research, this test is often applied in pre/post design, where the goal of the analysis is to assess change in scores before and after an intervention, or at the start and end of an academic year. For example, a study might measure students’ reading comprehension before and after a literacy intervention to evaluate its effectiveness.</p></li>
<li><p><strong>Paired-samples <span class="math inline">\(t\)</span> test</strong> is used when individuals or cases are matched in pairs based on key characteristics before comparing their scores. Unlike repeated-measures design, the paired individuals are not the same person measured twice; rather they are two different people who are statistically equivalent as pairs except for the dependent variables. For example, you could statistically match students who experience an intervention with a control group of students who are very similar on key variables. Other times family members (siblings, married couples) are paired, if it is reasonable to assume they are similar in important ways. This type of t test is less common as it often requires more advanced statistical methods or poses logistical challenges in finding well-matched pairs.</p></li>
</ul>
<p>The related-samples t test is actually a special case of the one-sample t test. In a related-samples test, you collect data in pairs, and the difference between each pair is calculated. Then, we compute statistics based on these differences. Your beginning assumption, or null hypothesis, is that there will be no difference between the pairs. You could create a new variable in your dataset that was equivalent to the difference between pairs and use a one-sample t test to compare that difference variable to the expected value of 0.</p>
<p>Let’s assume we are not creating new variables, and we will show you how to directly conduct a related-samples t test. However, keep in mind that you would get the same results either way.</p>
<p>We know it can be hard to understand why a related-samples t test is not the same as an independent-samples t test, since we are interested in the differences between two sets of scores in both cases. It really matters statistically that the same, or similar, people are in both groups in a related-samples study. The short description is that when you have different people in your two groups, it is hard to know for sure if the differences are really due to your grouping factor (e.g., free/reduced lunch status, treatment/control for an intervention), or if you by chance ended up with people who were very different from each other for reasons that had nothing to do with your grouping factor.</p>
<p>With a related-samples t test, we don’t need to worry about any of that. We know there are not random differences between the people in our two groups because the same people are in both groups. From a statistical perspective, this changes two things: we calculate degrees of freedom differently, and our hypotheses and test statistics are based on the difference between scores. Let’s use an example to look at each step of the related-samples t test more closely.</p>
<p>Imagine that you developed a new student learning intervention and piloted it with a sample of nine randomly selected students. You have data on their scores before and after the intervention, and now you want to determine if student scores significantly changed. Your dataset would look like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Pre</th>
<th style="text-align: center;">Post</th>
<th style="text-align: center;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">10</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">11</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">13</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">14</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">15</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">16</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">16</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">17</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">3</td>
</tr>
</tbody>
</table>
<p>If this was an independent-samples t test, you would be thinking about the distribution of <em>pre</em> scores and the distribution of post scores. However, in a related-samples test, the focus shifts to the distribution of <em>difference</em> scores (i.e., post – pre), which in this example ranges from -1 to 5 and has a sample mean of 2.33 with a SD of 1.80. For this example, the research question we will address is whether scores changed significantly between pre and post, which may suggest an effect of the intervention.</p>
<section id="step-1-determine-the-null-and-alternative-hypotheses.-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-1-determine-the-null-and-alternative-hypotheses.-1">Step 1: Determine the null and alternative hypotheses.</h3>
<p>Recall that with an independent-samples t test, there are two separate sample means to consider, so the null hypothesis for a two-tailed test is:</p>
<p><span class="math display">\[
H_0: \mu_1 − \mu_2 = 0
\]</span></p>
<p>With a related-samples t test, our null hypothesis for a two-tailed test is:</p>
<p><span class="math display">\[
H_0: \mu_D = 0
\]</span></p>
<p>The alternative hypothesis for a two-tailed, non-directional test is:</p>
<p><span class="math display">\[
H_A: \mu_D \ne 0
\]</span></p>
<p>The null hypothesis states that the difference between two dependent variables is zero and the alternative is that the difference between dependent variables is not zero. Keep in mind you can also conduct a one-tailed, directional test by making the alternative hypothesis that <span class="math inline">\(\mu_D &lt; 0\)</span> or <span class="math inline">\(\mu_D &gt; 0\)</span></p>
</section>
<section id="step-2-set-the-criteria-for-a-decision.-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-2-set-the-criteria-for-a-decision.-1">Step 2: Set the criteria for a decision.</h3>
<p>The next step in testing the null hypothesis is to set the criteria for a decision: how much of a difference is significant enough that we can conclude it is not a result of chance alone? As usual, we can decide that <span class="math inline">\(\alpha = .05\)</span>. The degrees of freedom for a related-samples t test are simply calculated by taking n – 1, where n refers to the number of pairs. Since each participant contributes one pair of scores (before and after), the number of pairs is equal to the number of participants in the study (with no missing values on both tests). You can use a t table just as before, looking for the intersection between your alpha level and your degrees of freedom to find the critical value. In our example, because n = 9, df = 9 - 1 = 8. If you flip to the Critical Values of t Distribution Table and look at df = 8 and <span class="math inline">\(\alpha = .05\)</span> (two-tailed), you see the critical value for this test is <span class="math inline">\(\pm2.306\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-9.5" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter9_files/figure-html/fig-9.5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.5: Sampling distribution with two-tailed rejection regions
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="step-3-check-assumptions-and-compute-the-test-statistic.-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-3-check-assumptions-and-compute-the-test-statistic.-1">Step 3: Check assumptions and compute the test statistic. </h3>
<p>The third step has a few parts. First, we verify that our data meet the assumptions required for this method of analysis, and then we calculate the test statistic. The assumptions for a related-samples t test are:</p>
<ul>
<li><p>Normality: The distribution of the difference scores is approximately normal. As with other t tests, this assumption is less critical when the sample size is greater than 30 due to the central limit theorem.</p></li>
<li><p>Random sampling: You are using a random sample of independent observations.</p></li>
<li><p>Independence: The scores are independent of one another. Although the two groups in a related-samples t test are obviously dependent on each other – since they consist of paired scores from the same individuals or matched pairs – the scores within each group must still be independent of one another. This means that each participant’s score should not be influenced by another participant’s score within the same group. In other words, the assumption of independence applies to the individual observations within each group, not between groups.</p></li>
</ul>
<p>Notice that we don’t have the equal variances assumption as we did with the independent-samples t test. We have that assumption with independent-samples t tests because we are concerned that major differences in group distributions mean the groups are very different, but as we said before, since we are using the same people this time, we are not as worried about that.</p>
</section>
<section id="step-4a-find-the-p-value.-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-4a-find-the-p-value.-1">Step 4a: Find the p value.</h3>
<p>Next, we calculate the test statistic. You will notice a lot of Ds in the following formula because we are <em>focusing on difference scores</em>, not two separate sample means. Instead of having two distributions of sample means, we have one <em>distribution of sample differences</em>.</p>
<p><span class="math display">\[
t = \frac{\bar{D} - \mu_D}{\frac{S_D}{\sqrt{n}}}
\]</span></p>
<p>Let’s unpack each part of the formula separately to make things easier to digest. The numerator is looking for the difference between the sample mean difference and the expected difference in the population under the assumption that the null hypothesis is true. However, recall that our null hypothesis is that there is no difference in the population, so <span class="math inline">\(\mu_D\)</span> is zero. For our purposes, therefore, the numerator is just the sample mean difference. Where does that come from? It is calculated as the average of the individual difference scores (post – pre) across all pairs in the sample, which is 2.33 in our example.</p>
<p>Now we look at the denominator of the test statistic formula. This should look familiar by now because we see a standard deviation divided by the square root of the sample size (i.e., standard error). The first value is <span class="math inline">\(S_D\)</span>, which is something we have not seen before. That represents the standard deviation of the difference distribution, which in this case is 1.80. Conveniently, our sample size is 9, so the square root of n is 3. Using this, we calculate the standard error of the sampling distribution of difference scores is 0.6. Therefore, we can calculate the test statistic as follows:</p>
<p><span class="math display">\[
t = \frac{2.33 - 0}{\frac{1.80}{3}} = \frac{2.33}{0.6} = 3.883
\]</span></p>
<p>The next step in testing our hypothesis is to compare our observed test statistic with the critical value. Our test statistic is definitely farther out into the tails of the distribution than 2.306, so we can reject the null hypothesis.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-9.6" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter9_files/figure-html/fig-9.6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.6: Sampling distribution with rejection regions and calculated t-value.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The actual <span class="math inline">\(p\)</span> value associated with the observed t statistic of 3.88 with <span class="math inline">\(df = 8\)</span> for a two-tailed test is 0.0047, which is smaller than 0.05.</p>
</section>
<section id="step-4b-draw-a-conclusion-and-report-your-conclusion.-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-4b-draw-a-conclusion-and-report-your-conclusion.-1">Step 4b: Draw a conclusion and report your conclusion.  </h3>
<p>The small <span class="math inline">\(p\)</span> value (<span class="math inline">\(p = 0.0047\)</span>) indicates that, under the assumption that the null hypothesis is true, the probability of observing a difference as extreme as, or more extreme than, the one we found in the sample is 0.47%. Because this is highly unlikely, we reject the null hypothesis and conclude that there is a statistically significant difference in scores between pre and post. Because the observed difference is statistically significant, we now want to know how the difference is practically meaningful by calculating the effect size.</p>
</section>
</section>
<section id="effect-size-for-related-samples-t-tests" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="effect-size-for-related-samples-t-tests"><span class="header-section-number">9.5</span> Effect Size for Related-Samples <span class="math inline">\(t\)</span> Tests</h2>
<p>Once we have found a statistically significant difference, it is useful to examine the practical significance as well. The formula for Cohen’s <span class="math inline">\(d\)</span> for this type of t test is as follows:</p>
<p><span class="math display">\[
d = \frac{M_d}{S_D}
\]</span></p>
<p>That is, we take the mean difference and divide it by the standard deviation of the difference. The effect size for the example is calculated as:</p>
<p><span class="math display">\[
d = \frac{M_d}{S_D} = \frac{2.33}{1.8} = 1.29
\]</span></p>
<p>This means that, on average, scores increased by 1.29 standard deviation units from pre and post, which represents a large effect size. Based on this statistical result, and assuming no other confounding factors, we may conclude that the intervention had a meaningful impact on scores!</p>
<p>Here is how you would report this example using APA style: A repeated-measures t test was conducted to evaluate the effect of the intervention on scores using a random sample of nine students. Results indicated that, on average, students’ scores changed by 2.33 points between pre- and post-tests. The difference was statistically significant, <span class="math inline">\(t(8) = 3.88, \, p &lt; .01\)</span>. Cohen’s <span class="math inline">\(d = 1.29\)</span>, which is a large effect size, indicating substantial improvement in scores following the intervention.</p>
<p>There is one extra wrinkle to consider: <em>what if the expected difference in the population is not zero?</em> For example, K-12 students take standardized tests in math and reading multiple times each year, and their scores are generally expected to improve over time. Testing companies use population data to provide expected growth benchmarks for each grade level.</p>
<p>Suppose third graders are expected to see a 13-point increase in math scores from the beginning to the end of the school year. If you wanted to determine whether students in your school were experiencing growth that was different from the expected population growth, your null and alternative hypotheses would be as follows:</p>
<p><span class="math display">\[
H_0 : \mu_D = 13
\]</span></p>
<p><span class="math display">\[
H_A : \mu_D \ne 13
\]</span></p>
</section>
<section id="comparing-two-groups-with-ordinal-data-nonparametric-tests" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="comparing-two-groups-with-ordinal-data-nonparametric-tests"><span class="header-section-number">9.6</span> Comparing Two Groups with Ordinal Data: Nonparametric Tests</h2>
<p>In hypothesis testing, parametric and nonparametric tests differ primarily in their assumptions about the data. In general, parametric tests, such as t tests, are distinguished by the assumption of normality on the data with a continuous dependent variable. Parametric tests typically use the raw data directly in their calculations and require certain conditions, such as homogeneity of variance and interval or ratio-level measurement of the dependent variable.</p>
<p>In contrast, nonparametric tests are distinguished by the absence of any distributional requirement for the data and are less restrictive in terms of the scales of measurement. These tests are more flexible and can be used with ordinal data or when assumptions for parametric tests are violated. Instead of analyzing raw values, nonparametric methods often involve rank-based transformations of the data before analysis, making them less sensitive to outliers and skewed distributions.</p>
<p>A difference between the two approaches is that parametric tests allow for inferences about population parameters, such as means and standard deviations. However, nonparametric tests do not estimate specific population parameters; they instead assess whether two or more groups share the same distribution. The primary advantage of nonparametric tests is their robustness and fewer assumptions, making them useful alternatives to <span class="math inline">\(t\)</span> tests when data are not normally distributed, have small sample sizes, or contain outliers.</p>
</section>
<section id="choosing-between-parametric-and-nonparametric-tests" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="choosing-between-parametric-and-nonparametric-tests"><span class="header-section-number">9.7</span> Choosing between Parametric and Nonparametric Tests</h2>
<p>In general, we prefer to use the test that is the most efficient compared to others and produces the largest statistical power among all alternatives. For example, consider the two independent samples t test. If the scores are independent and homoscedastic, and follow a normal distribution, this test is optimal in that there is no other test with greater statistical power for a given alternative. On the other hand, failure to satisfy the normality assumption means that the t test may not be optimal. In particular, the power of nonparametric competitors often exceeds that of the t test when the population distribution is symmetric but is flatter (or heavy-tailed), when the distribution is highly skewed, or if the distribution is multimodal and heavy-tailed.</p>
<p>If data assumptions of parametric tests are not adequately satisfied, the actual α of a test (i.e., the probability of having a Type I error) may differ substantially from the user-specified α level (e.g., 0.05), although we never know exactly how much the probability differs. Especially when sample size exceeds 30, there is evidence that many parametric tests, especially those comparing means, maintain control over Type I error rates even when the dependent variable is not normally distributed. If the distribution is skewed and/or multimodal and heavy-tailed, nonparametric tests frequently do a better job of controlling for Type I error rates.</p>
<p>In educational research, nonparametric tests are particularly useful when the outcome variable includes responses on a Likert-type rating scale, because the distribution is often skewed. You may come across research that uses parametric tests, such as a two-independent samples t test, to compare responses on a single Likert scale item between two groups. However, this practice is not generally recommended. Additionally, as we have discussed, outliers can contribute a great deal of error variance in parametric tests, so a nonparametric alternative potentially is more powerful.</p>
<p>The following table shows parametric tests you are already familiar with and nonparametric alternatives. We will describe the Mann-Whitney U test and the Wilcoxon signed rank T test in more detail.</p>
<div class="striped-table">
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Parametric</strong></th>
<th><strong>Nonparametric</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One-sample <em>t</em> test</td>
<td>Sign test</td>
</tr>
<tr class="even">
<td>Independent-samples <em>t</em> test</td>
<td>Mann–Whitney <em>U</em> test</td>
</tr>
<tr class="odd">
<td>Related-samples <em>t</em> test</td>
<td>Wilcoxon signed rank <em>T</em> test</td>
</tr>
<tr class="even">
<td>One-way between-subjects ANOVA</td>
<td>Kruskal–Wallis <em>H</em> test</td>
</tr>
<tr class="odd">
<td>One-way repeated measures ANOVA</td>
<td>Friedman test</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="two-independent-sample-mann-whitney-u-test" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="two-independent-sample-mann-whitney-u-test"><span class="header-section-number">9.8</span> Two Independent-Sample Mann-Whitney <span class="math inline">\(U\)</span> Test</h2>
<p><strong>The Mann-Whitney <span class="math inline">\(U\)</span> test</strong> is a statistical procedure used to determine whether the dispersion of ranks is equal across two independent groups. It is used as a nonparametric alternative to the two independent-samples t test. The test has three assumptions:</p>
<ul>
<li><p>Both samples are randomly drawn from their respective populations.</p></li>
<li><p>In addition to independence within each sample, there is mutual independence between the two samples (no one belongs to both groups).</p></li>
<li><p>The measurement scale is at least ordinal (no categorical variables).</p></li>
</ul>
<p>Let’s walk through an example. Suppose that we give nine children a math achievement test and record their scores. They then receive daily practice on arithmetic problems. At the end of each practice session, their papers are marked by a teacher’s aide, who praises them for the number they got right and states that they might do even better in the next few days. We treat eight other children the same except for the statements made by the teacher’s aide. For these children, they point out the problems they missed and tell them that they should be able to do better than that. At the end of two weeks, we retest all children on a parallel form of the math achievement test and calculate their “gain scores” over the two-week period:</p>
<div class="score-table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Criticism (X)</th>
<th>-3</th>
<th>-2</th>
<th>0</th>
<th>0</th>
<th>2</th>
<th>5</th>
<th>7</th>
<th>9</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Praise (Y)</td>
<td>0</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>10</td>
<td>12</td>
<td>14</td>
<td>19</td>
<td>21</td>
</tr>
</tbody>
</table>
</div>
<p><span class="math display">\[
H_0 \text{: The two groups have identical distributions.}
\]</span> <span class="math display">\[
H_A: \text{The two groups do not have identical distributions.}
\]</span></p>
<p>These data are measured on a continuous scale, so theoretically we could use a two independent-samples t test, but first we should look at the descriptive statistics to see if our data meet the assumptions of that method. You can look at descriptive statistics for each group, but we think the most helpful way to consider the data is by viewing histograms for each group:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-9.7" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="720">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter9_files/figure-html/fig-9.7-1.png" id="fig-9.7" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" width="720">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-9.7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.7
</figcaption>
</figure>
</div>
</div>
</div>
<p>Given the very small sample sizes (8 and 9 cases for Criticism and Praise, respectively) and two distributions not looking normal, we should not use the independent-samples <span class="math inline">\(t\)</span> test. Since this is a very small dataset, let’s calculate the test statistic by hand to illustrate the logic behind the test. In practice, statistical software can perform this analysis.</p>
<p><strong>Step 1:</strong> Label the two groups <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. The smaller group should be labeled <span class="math inline">\(X\)</span>; if sample sizes are equal then it doesn’t matter which group is labeled <span class="math inline">\(X\)</span>.</p>
<p><span class="math inline">\(X\)</span> = Criticism condition</p>
<p><span class="math inline">\(Y\)</span> = Praise condition</p>
<p><strong>Step 2:</strong> Combine all the scores into one distribution of <span class="math inline">\(n_X\)</span> + <span class="math inline">\(n_Y\)</span> cases. Arrange them in order of the dependent variable from lowest to highest and assign ranks.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Condition</strong></th>
<th style="text-align: center;"><strong>Gain Scores</strong></th>
<th style="text-align: center;"><strong>Assigned Rank</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">X</td>
<td style="text-align: center;">-3</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">X</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">X</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">X</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">X</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">6.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">6.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">X</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">X</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="even">
<td style="text-align: center;">X</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="even">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Y</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">17</td>
</tr>
</tbody>
</table>
<p>When assigning ranks in a dataset, ties occur when two or more scores are identical. In such cases, instead of giving each tied score a unique rank, we calculate the average rank they would have occupied.</p>
<p>For example, in the table above, three students had gain scores of 0. These scores would have been ranked 3, 4, and 5 if assigned individually. Instead, we sum these ranks (3 + 4 + 5 = 12) and divide by 3, giving each student a rank of 4. The next score is then assigned the rank that follows the tied ranks, which in this case is 6.5 (the average of the next two ranks, 6 and 7).</p>
<p><strong>Step 3</strong>: Divide the cases back into their original groups.</p>
<div class="rank-table">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 26%">
<col style="width: 21%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Criticism (X)</strong></th>
<th style="text-align: center;"><strong>Assigned Rank</strong></th>
<th style="text-align: center;"><strong>Praise (Y)</strong></th>
<th style="text-align: center;"><strong>Assigned Rank</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">-3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">-2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">6.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">9</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">17</td>
</tr>
</tbody>
</table>
</div>
<p><strong>Step 4</strong>: Sum up the ranks for each group.</p>
<p><span class="math display">\[
\text{Sum of ranks for Group X: }
\sum R_X = 1 +2+4+4+6.5+10+11+12=50.5
\]</span></p>
<p><span class="math display">\[
\text{Sum of ranks for Group Y: }
\sum R_Y=4+6.5+8+9+13+14+15+16+17=102.5
\]</span></p>
<p><strong>Step 5</strong>: Use the summed ranks to calculate the test statistic (i.e., Mann-Whitney <span class="math inline">\(U\)</span> Statistic).</p>
<p><span class="math display">\[
U_x = n_x n_y + \frac{n_x(n_x + 1)}{2} - \sum R_x
= 8 \times 9 + \frac{8(9)}{2} - 50.5
= 57.5
\]</span></p>
<p><span class="math display">\[
U_y = n_x n_y + \frac{n_y(n_y + 1)}{2} - \sum R_y
= 8 \times 9 + \frac{9(10)}{2} - 102.5
= 14.5
\]</span></p>
<ul>
<li><span class="math inline">\(n_X\)</span> and <span class="math inline">\(n_Y\)</span> are the sample sizes of groups X and Y, respectively.</li>
<li><span class="math inline">\(R_X\)</span> and <span class="math inline">\(R_Y\)</span> are the rank sums for each group.</li>
<li>U is the smaller of <span class="math inline">\(U_X\)</span> and <span class="math inline">\(U_Y\)</span>.</li>
</ul>
<p><strong>Step 6</strong>: Evaluate the test statistic using the Critical Values for the Mann-Whitney <span class="math inline">\(U\)</span> Test table in the appendix. We use the value of <span class="math inline">\(U = 14.5\)</span> as the test statistic because it is the smaller of the two U values calculated.</p>
<p>Next, we determine whether we are conducting a one-tailed or two-tailed test. In this case, our test is non-directional (two-tailed), so we divide our alpha level of 0.05 equally between the two tails, resulting in 0.025 in each tail.</p>
<p>We locate the critical value by finding the number of cases in each group along the left side and top of the table. For group sizes of 8 and 9, the critical value is 15. Since our test statistic (<span class="math inline">\(U = 14.5\)</span>) is less than or equal to the critical value (15), we reject the null hypothesis that the two distributions are the same.</p>
<p>Note that, unlike many parametric tests where we compare the test statistic to see if it exceeds the critical value, in the Mann-Whitney <span class="math inline">\(U\)</span> test, we reject the null hypothesis when the test statistic is less than or equal to the critical value.</p>
<p>With this result, we conclude that the distributions of the two groups are statistically different, indicating that the scores between the Criticism and Praise groups differ significantly, <span class="math inline">\(U = 14.5\)</span>, <span class="math inline">\(p = 0.043\)</span>.</p>
</section>
<section id="wilcoxons-matched-pairs-signed-ranks-test" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="wilcoxons-matched-pairs-signed-ranks-test"><span class="header-section-number">9.9</span> Wilcoxon’s Matched-Pairs Signed-Ranks Test</h2>
<p>While the Mann-Whitney <span class="math inline">\(U\)</span> Test is used to compare two independent groups, <strong>Wilcoxon’s Matched-Pairs Signed-Ranks Test</strong> is a nonparametric alternative to the related-samples (or repeated-measures) t test.</p>
<p>Let’s walk through another example to help you learn more about this method. Suppose we are studying the effect of a new instructional strategy on math performance, specifically on the speed and accuracy of solving arithmetic problems. We form 10 pairs of students, matched according to their pre-test score earned on similar math problems, and then randomly assign members of each pair to either the new instructional strategy or the traditional teaching method (control group). After completing a structured learning session, the students take a post-test assessing their arithmetic skills.</p>
<p>Their post-test scores were recorded in the table below as Traditional (control) and New Strategy (treatment). Although different students are assigned to the two groups, the pairing process creates dependence between their scores, as students were first matched by pre-test ability before assignment.</p>
<p>As we are interested in any difference (positive or negative) due to the instructional strategy, we use a two-tailed test. The null and alternative hypotheses for this investigation are:</p>
<p><span class="math inline">\(H_0\)</span>: There is no difference in student performance between two instructional groups.</p>
<p><span class="math inline">\(H_A\)</span>: There is a difference in student performance between two instructional groups.</p>
<p>Rather than create new tables for each of the steps required to calculate the test statistic by hand, we will add a row to the table below showing which columns belong to which step in the process.</p>
<ul>
<li><p><strong>Step 1</strong>. Recode the paired scores in two columns.</p></li>
<li><p><strong>Step 2</strong>. Obtain the difference between members of each pair (X-Y).</p></li>
<li><p><strong>Step 3</strong>. Disregard the sign of the difference obtained and then assign ranks to the absolute magnitude of the difference. This means that a difference of -8 would be a higher rank than a difference of 5. If any difference is zero, disregard it in subsequent calculations. For tied ranks, assign the mid rank as we did in the prior test.</p></li>
<li><p><strong>Step 4</strong>. Reassign the appropriate sign to the rank. This is a weird step but don’t take it literally, e.g., -2 does not mean the rank of -2 (negative 2nd). It simply provides two types of information about the score at once: the rank of the score and the direction of the difference.</p></li>
<li><p><strong>Step 5</strong>. Compute the summed rank for both positive and negative differences. The smaller absolute value summation becomes our test statistic (6.5).</p></li>
</ul>
<div class="wilcoxon-table-header">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Steps</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
</div>
<div class="wilcoxon-table">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Pair</th>
<th style="text-align: center;">Traditional (X)</th>
<th style="text-align: center;">New (Y)</th>
<th style="text-align: center;">Difference (X-Y)</th>
<th style="text-align: center;">Absolute Difference</th>
<th style="text-align: center;">Rank of Absolute Difference</th>
<th style="text-align: center;">Signed rank of X-Y</th>
<th style="text-align: center;">Positive Difference</th>
<th style="text-align: center;">Negative Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">-4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-2</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">-5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">-3.5</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-3.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">-3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-1</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>SUM</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>55</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>48.5</strong></td>
<td style="text-align: center;"><strong>-6.5</strong></td>
</tr>
</tbody>
</table>
</div>
<p>We then use the Critical Values for the Wilcoxon Matched-Pairs Signed-Ranks Test table in the appendix. Since <span class="math inline">\(n = 10\)</span> and we are conducting a two-sided test with an alpha level of .05, the critical value is 8. Our test statistic is 6.5, and similar to the Mann-Whitney U test, we reject the null hypothesis if the test statistic is less than or equal to the critical value. In this case, since 6.5 ≤ 8, we reject the null hypothesis.</p>
<p>Alternatively, statistical software can be used to obtain the associated p value for the test statistic. In this case, the computed <span class="math inline">\(p\)</span> value = 0.037, which is less than 0.05, further supporting the rejection of the null hypothesis. Therefore, we conclude that there is a statistically significant difference in scores between the two instructional strategies. This suggests that the new instructional strategy has an effect. However, it is important to note that the test itself only determines whether a difference exists; it does not indicate the direction of the effect (i.e., whether the new strategy increased or decreased scores).</p>
</section>
</section>
<section id="analyzing-differences-between-two-groups-in-r" class="level1 unnumbered">
<h1 class="unnumbered">Analyzing Differences Between Two Groups in R</h1>
<p>In this section, we demonstrate how to compare <strong>two independent groups</strong> (students who are more motivated vs. not more motivated in math) on <strong>math achievement</strong> (PV1MATH) from the PISA 2022 U.S. dataset using R. We illustrate both parametric (independent-samples t test) and nonparametric (Mann-Whitney U) methods, aligning with the chapter’s discussion of assumptions and alternatives.</p>
<section id="data-exploration" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-exploration">1 Data Exploration</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>MATHMOT <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>MATHMOT, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Not more motivated"</span>, <span class="st">"More motivated"</span>)) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>MATHMOT)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Not more motivated     More motivated 
              3885                125 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize math score distribution by motivation </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(MATHMOT)), <span class="co"># Filter out missing values in MATHMOT  </span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> PV1MATH, <span class="at">fill =</span> <span class="fu">as.factor</span>(MATHMOT))) <span class="sc">+</span> </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Math Scores by Math Motivation"</span>, </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Math Scores (PV1MATH)"</span>, <span class="at">fill =</span> <span class="st">"Math Motivation"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter9_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong>: Among the participants, 125 students reported being more motivated in math, while 3,885 students did not. The density plot above compares the distribution of math scores between two groups of students based on their self-reported math motivation. The score distribution of more motivated students (in cyan) appears slightly shifted to the right, suggesting higher overall performance in math. This visual pattern hints at a potential performance difference related to student motivation toward math, which will be formally tested in the next steps using statistical methods.</p>
</section>
<section id="two-independent-sample-t-test" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="two-independent-sample-t-test">2 Two Independent-Sample t Test</h2>
<section id="define-hypothesis" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="define-hypothesis">2.1 Define Hypothesis</h3>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: The mean math scores are equal between the two groups (<span class="math inline">\(\mu_0=\mu_1\)</span>).</p></li>
<li><p><span class="math inline">\(H_a\)</span>: The mean math scores are different between the two groups (<span class="math inline">\(\mu_0\ne \mu_1\)</span>₁).</p></li>
</ul>
</section>
<section id="conduct-the-test" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="conduct-the-test">2.2 Conduct the Test</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Test for equal variances </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>leveneTest_result <span class="ot">&lt;-</span> <span class="fu">leveneTest</span>(PV1MATH <span class="sc">~</span> <span class="fu">factor</span>(MATHMOT), <span class="at">data =</span> data) </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>leveneTest_result </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
        Df F value  Pr(&gt;F)  
group    1  5.3625 0.02062 *
      4008                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform independent-samples t-test </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(PV1MATH <span class="sc">~</span> MATHMOT, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">FALSE</span>) </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>t_test_result </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  PV1MATH by MATHMOT
t = -1.2416, df = 130.44, p-value = 0.2166
alternative hypothesis: true difference in means between group Not more motivated and group More motivated is not equal to 0
95 percent confidence interval:
 -31.111221   7.118331
sample estimates:
mean in group Not more motivated     mean in group More motivated 
                        466.6617                         478.6582 </code></pre>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<p>Levene’s Test for Equality of Variances yielded a statistically significant result (<span class="math inline">\(F = 5.36, p = .021\)</span>), indicating that the assumption of equal variances is violated. Therefore, we proceeded with Welch’s <span class="math inline">\(t\)</span>-test (by setting var.equal = FALSE in the t.test() function), which adjusts for unequal variances.</p>
<p>The Welch’s <span class="math inline">\(t\)</span>-test revealed no statistically significant difference in average math scores between students who reported being more motivated and those who did not, <span class="math inline">\(t(130.44) = -1.24\)</span>, <span class="math inline">\(p = .217\)</span>. The mean math score for students who were not more motivated was 466.66, compared to 478.66 for students who reported being more motivated. Although more motivated students scored slightly higher on average, the difference is not statistically meaningful, and could plausibly be due to random variation.</p>
</section>
<section id="effect-size-cohens-d" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="effect-size-cohens-d">2.3 Effect Size (Cohen’s <span class="math inline">\(d\)</span>)</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr) <span class="co"># Load the lsr package for effect size calculation </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's d for an independent-samples t-test </span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>d_value <span class="ot">&lt;-</span> <span class="fu">cohensD</span>(PV1MATH <span class="sc">~</span> MATHMOT, <span class="at">data =</span> data) </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>d_value </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1254531</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: The effect size (Cohen’s <span class="math inline">\(d\)</span>) was 0.13, which is considered small by conventional benchmarks. This suggests that the difference in math scores between more motivated and less motivated students is minimal in practical terms.</p>
</section>
</section>
<section id="two-independent-sample-mann-whitney-u-test-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="two-independent-sample-mann-whitney-u-test-1">3 Two Independent-Sample Mann-Whitney U Test</h2>
<p>If the normality assumption is violated or the data are ordinal or highly skewed, the Mann-Whitney <span class="math inline">\(U\)</span> test is appropriate. In R, this test is implemented using the wilcox.test() function. Note this is not the same as the Wilcoxon’s Matched-Pairs Signed-Ranks Test, which is used for paired or related samples.</p>
<p>In our case, the data do not strongly violate normality and are measured on a continuous scale, so using a <span class="math inline">\(t\)</span>-test is justified. However, we demonstrate the Mann-Whitney <span class="math inline">\(U\)</span> test here for educational purposes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Mann-Whitney U test </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mw_result <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(PV1MATH <span class="sc">~</span> MATHMOT, <span class="at">data =</span> data) </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>mw_result </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  PV1MATH by MATHMOT
W = 222444, p-value = 0.1099
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: The Mann-Whitney <span class="math inline">\(U\)</span> test yielded <span class="math inline">\(W = 222,444\)</span>, with a <span class="math inline">\(p\)</span>-value of 0.110. This result suggests that there is no statistically significant difference in the distribution of math scores between students who are more motivated and those who are not. In other words, based on the ranked data, math motivation does not appear to meaningfully shift the overall distribution of scores, aligning with the findings from the Welch’s t-test.</p>
</section>
</section>
<section id="analyzing-differences-between-two-groups-in-spss" class="level1 unnumbered">
<h1 class="unnumbered">Analyzing Differences Between Two Groups in SPSS</h1>
<p>In this section, we demonstrate how to compare two independent groups (students who are more motivated vs. not more motivated in math) on math achievement (PV1MATH) from the PISA 2022 U.S. dataset using SPSS. We illustrate both parametric (independent-samples t test) and nonparametric (Mann-Whitney <span class="math inline">\(U\)</span>) methods, aligning with the chapter’s discussion of assumptions and alternatives.</p>
<section id="data-exploration-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-exploration-1">1 Data Exploration</h2>
<p>We first examine the grouping variable to understand how many students fall into each math motivation group. Follow these steps to check the frequency of MATHMOT, the variable indicating students’ motivation to do well in mathematics:</p>
<ol type="1">
<li><p>Click Analyze &gt; Descriptive Statistics &gt; Frequencies.</p></li>
<li><p>Move MATHMOT into the Variable(s) box.</p></li>
<li><p>Click OK.</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter9/fig9s-1.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 9.s.1</figcaption>
</figure>
</div>
<p><strong>Interpretation:</strong></p>
<p>The results show that, among the 4,010 participants, 125 students reported being more motivated in math, while 3,885 students did not. There are 542 cases with missing values on this variable.</p>
<p>Then we follow the steps below to visualize the distribution of math scores (PV1MATH) between the two groups of students based on their self-reported math motivation:</p>
<ol type="1">
<li><p>Click Graphs &gt; Boxplot.</p></li>
<li><p>In the dialog box, choose Simple and select Summaries for groups of cases, then click Define.</p></li>
<li><p>Move PV1MATH into the Variable field (this is the math score to be plotted).</p></li>
<li><p>Move MATHMOT into the Category Axis field (this defines the two motivation groups).</p></li>
<li><p>Click OK and you will get the following plot.</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter9/fig9s-2.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 9.s.2</figcaption>
</figure>
</div>
<p><strong>Interpretation</strong>:</p>
<p>The boxplot displays the distribution of math scores (PV1MATH) for students who are more motivated versus not more motivated to do well in mathematics. Visually, the more motivated group shows a slightly higher median math score, and the overall distribution appears slightly shifted upward compared to the less motivated group. Both groups exhibit a fairly wide range, and there are several outliers in the “Not more motivated” group. These visual differences suggest a possible group effect, which will be formally tested using statistical methods in the next steps.</p>
</section>
<section id="two-independent-sample-t-test-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="two-independent-sample-t-test-1">2 Two Independent-Sample t Test</h2>
<section id="define-hypothesis-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="define-hypothesis-1">2.1 Define Hypothesis</h3>
<p><span class="math inline">\(H_0\)</span>: The mean math scores are equal between the two groups (<span class="math inline">\(\mu_0 = \mu_1\)</span>).</p>
<p><span class="math inline">\(H_a\)</span>: The mean math scores are different between the two groups (<span class="math inline">\(\mu_0 \ne \mu_1\)</span>).</p>
</section>
<section id="conduct-the-test-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="conduct-the-test-1">2.2 Conduct the Test</h3>
<p>Before conducting the independent-samples t-test, we first verify how the grouping variable is coded. This ensures we know which value corresponds to each group, which is essential for correctly setting up and interpreting the test. To do this, go to the Variable View in SPSS and locate the variable MATHMOT. In the Values column for that row, click the cell to view the assigned labels. You will see that 0 represents “Not more motivated…”, and 1 represents “More motivated…”. This coding information will be used when defining the groups in the upcoming independent-samples t-test.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter9/fig9s-3.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 9.s.3</figcaption>
</figure>
</div>
<p>SPSS provides a convenient one-step procedure for comparing two group means. It simultaneously performs Levene’s Test for Equality of Variances and the independent-samples <span class="math inline">\(t\)</span>-test, reporting results both under the assumption of equal variances (Student’s t-test) and without it (i.e., Welch’s t-test). This allows us to determine which result to interpret based on the outcome of Levene’s Test. SPSS can also output the effect size (e.g., Cohen’s d) as part of the same analysis. Follow these steps to conduct the analysis:</p>
<ol type="1">
<li><p>Click Analyze &gt; Compare Means &gt; Independent-Samples T Test.</p></li>
<li><p>Move PV1MATH into the Test Variable(s) field.</p></li>
<li><p>Move MATHMOT into the Grouping Variable field.</p></li>
<li><p>Click Define Groups, enter 0 for Group 1 and 1 for Group 2.</p>
<p>(These values correspond to students who are not more motivated and students who are more motivated, respectively. Recall that SPSS uses this information to distinguish between the two groups, with 0 representing “Not more motivated” and 1 representing “More motivated.” SPSS calculates the t-statistic as the mean of Group 1 minus the mean of Group 2, that is, the mean of the “Not more motivated” group minus the mean of the “More motivated” group. You may reverse the group coding if preferred, but be sure to adjust the interpretation accordingly to reflect the correct reference group.)</p></li>
<li><p>Click Options to adjust the confidence interval level (e.g., 95%).</p></li>
<li><p>Click Estimate effect sizes</p></li>
<li><p>Click Continue, then click OK to run the test.</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter9/fig9s-4.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Fig 9.s.4</figcaption>
</figure>
</div>
<p><strong>Results:</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter9/fig9s-5.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 9.s.5</figcaption>
</figure>
</div>
<p><strong>Interpretation:</strong></p>
<p>Levene’s Test for Equality of Variances yielded a statistically significant result (<span class="math inline">\(F = 5.865\)</span>, <span class="math inline">\(p = .015\)</span>), indicating that the assumption of equal variances is violated. Therefore, we proceeded with Welch’s <span class="math inline">\(t\)</span>-test (interpreting the second line of the SPSS output labeled “Equal variances not assumed”), which adjusts for unequal variances.</p>
<p>The Welch’s <span class="math inline">\(t\)</span>-test revealed no statistically significant difference in average math scores between students who reported being more motivated and those who did not, <span class="math inline">\(t(130.44) = -1.24\)</span>, <span class="math inline">\(p = .217\)</span>. The mean math score for students who were not more motivated was 466.66, compared to 478.66 for students who reported being more motivated (These two values are in the Table titled “Group Statistics”). Although more motivated students scored slightly higher on average, the difference is not statistically meaningful and could plausibly be due to random variation.</p>
<p>From the table labeled “Independent Samples Effect Sizes,” the effect size (Cohen’s <span class="math inline">\(d\)</span>) was -0.125, which is considered small by conventional benchmarks. This suggests that the difference in math scores between more motivated and less motivated students is minimal in practical terms.</p>
</section>
</section>
<section id="two-independent-sample-mann-whitney-u-test-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="two-independent-sample-mann-whitney-u-test-2">3 Two Independent-Sample Mann-Whitney U Test</h2>
<p>If the normality assumption is violated or the data are ordinal or highly skewed, the Mann-Whitney <span class="math inline">\(U\)</span> test is appropriate. Note this is not the same as the Wilcoxon’s Matched-Pairs Signed-Ranks Test, which is used for paired or related samples.</p>
<p>In our case, the data does not strongly violate normality and are measured on a continuous scale, so using a t-test is justified. However, we demonstrate the Mann-Whitney U test here for educational purposes. Follow these steps to conduct the analysis:</p>
<ol type="1">
<li><p>Click Analyze &gt; Nonparametric Tests &gt; Legacy Dialogs &gt; 2 Independent Samples.</p></li>
<li><p>Move PV1MATH into the Test Variable List box.</p></li>
<li><p>Move MATHMOT into the Grouping Variable box.</p></li>
<li><p>Click Define Groups, and enter 0 and 1 to match the group coding used earlier.</p>
<p>(Here, 0 represents “Not more motivated” and 1 represents “More motivated.”)</p></li>
<li><p>Ensure that Mann-Whitney U is selected under Test Type.</p></li>
<li><p>Click OK to run the analysis.</p></li>
</ol>
<p><strong>Results:</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter9/fig9s-6.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 9.s.6</figcaption>
</figure>
</div>
<p><strong>Interpretation:</strong></p>
<p>The Mann-Whitney <span class="math inline">\(U\)</span> test yielded <span class="math inline">\(W = 222,444\)</span>, with a <span class="math inline">\(p\)</span>-value of 0.110. This result suggests that there is no statistically significant difference in the distribution of math scores between students who are more motivated and those who are not. In other words, based on the ranked data, math motivation does not appear to meaningfully shift the overall distribution of scores, aligning with the findings from the Welch’s <span class="math inline">\(t\)</span>-test.</p>
</section>
</section>
<section id="conclusion" class="level1 unnumbered">
<h1 class="unnumbered">Conclusion</h1>
<p>In chapter 9, we expanded our understanding of hypothesis testing by exploring various methods for comparing two groups. Central topics included the distinctions among the three types of <span class="math inline">\(t\)</span> tests—one-sample, independent-samples, and related-samples—and the assumptions underpinning these methods, such as normality, independence, and equal variances. Additionally, the chapter emphasized the importance of effect size measures, such as Cohen’s <span class="math inline">\(d\)</span> and eta-squared, to evaluate the practical significance of findings beyond mere statistical significance.</p>
<p>The chapter also introduced nonparametric alternatives for scenarios where data do not meet parametric test assumptions. The Mann-Whitney <span class="math inline">\(U\)</span> test, a substitute for the independent-samples t test, evaluates whether two independent groups have equal distributions, making it ideal for ordinal data or when assumptions of normality and equal variance are violated. Similarly, Wilcoxon’s Matched-Pairs Signed-Ranks Test, an alternative to the related-samples <span class="math inline">\(t\)</span> test, is used for paired data to test whether the median differences deviate significantly from zero. These methods are particularly useful for addressing skewed or ordinal data and ensuring robust conclusions when parametric assumptions are not satisfied.</p>
<p>By incorporating both parametric and nonparametric techniques, this chapter equips researchers with a versatile toolkit for hypothesis testing, enabling rigorous analyses of group differences under varied data conditions. These statistical foundations pave the way for more advanced methodologies in subsequent chapters, reinforcing the importance of selecting appropriate tests based on data characteristics and research questions.</p>
<section id="key-takeaways-for-educational-researchers-from-chapter-9" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="key-takeaways-for-educational-researchers-from-chapter-9">Key Takeaways for Educational Researchers from Chapter 9</h2>
<ul>
<li><p>Choosing the right t test matters. The one-sample t test compares a group’s mean to a known population mean (e.g., comparing students’ reading scores to the national average). The independent-samples t test compares means from two separate groups (e.g., evaluating whether students in a new math curriculum perform better than those in a traditional program). The related-samples t test (paired t test) compares the same group at two time points or under different conditions (e.g., pre- and post-intervention reading scores).</p></li>
<li><p>Checking assumptions before running a t test is crucial. Normality, independence, and equal variances should be checked before running parametric tests using histograms, Q-Q plots, and Levene’s test. For example, if two third-grade classrooms have vastly different test score variances, an adjusted t test or a nonparametric alternative should be used.</p></li>
<li><p>Interpreting statistical vs.&nbsp;practical significance is important. A statistically significant result (p &lt; 0.05) does not always mean the difference is meaningful. Effect sizes like Cohen’s d help determine whether the difference is practically important (e.g., does a statistically significant 2-point improvement on a 100-point test really matter in practice?).</p></li>
<li><p>Nonparametric tests are useful for skewed or ordinal data. When working with a single Likert-scale item on a scale or survey (e.g., student engagement ratings: Strongly Agree to Strongly Disagree), normality assumptions may not hold. The Mann-Whitney U test (for independent groups) and the Wilcoxon Matched-Pairs Signed-Ranks Test (for paired data) may be preferred in such cases. If assumptions for an independent t test are violated, the Mann-Whitney U test compares whether two groups have different distributions rather than just mean differences (e.g., Comparing test scores between students who received praise vs.&nbsp;criticism in a classroom setting). When data are dependent (e.g., before vs.&nbsp;after an intervention) but not normally distributed, the Wilcoxon Matched-Pairs Signed-Ranks Test is an alternative to the related-samples t test (e.g., tracking students’ math problem-solving speed before and after using a new instructional strategy).</p></li>
<li><p>Statistical software helps, but understanding the underlying logic is key. Software like IBM SPSS, R, and Python can quickly compute test statistics and p values, but researchers should understand the underlying logic of hypothesis testing. For example, before running an independent t test to compare student GPAs in two different school districts, a researcher should check for normality and equal variances before interpreting results. Also, it is important to interpret statistical results within the context of the study.</p></li>
</ul>
</section>
<section id="key-definitions-from-chapter-9" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="key-definitions-from-chapter-9">Key Definitions from Chapter 9</h2>
<p><strong>Distribution of sample differences</strong> refers to the theoretical distribution that arises when calculating the differences between sample means (in independent-samples t tests) or paired scores (in related-samples t tests) repeatedly under the same sampling conditions.</p>
<p><strong>Equal variance</strong> refers to the assumption that the variance (the measure of variability or spread) in different groups being compared is approximately the same.</p>
<p><strong>Eta-squared (<span class="math inline">\(\eta^2\)</span>)</strong> is a measure of effect size used to quantify the proportion of variance in a dependent variable that is associated with one or more independent variables in an analysis.</p>
<p>An <strong>independent-samples <span class="math inline">\(t\)</span> test</strong> is a statistical method used to compare the means of two independent groups to determine whether there is a statistically significant difference between them.</p>
<p><strong>Levene’s Test</strong> is a statistical procedure used to assess whether the variances of a dependent variable are equal across different groups. It is commonly applied before conducting analyses that assume equal variances, such as t-tests or ANOVA, to determine if this assumption holds.</p>
<p>The <strong>Mann-Whitney <span class="math inline">\(U\)</span> test</strong> is a statistical procedure used to determine whether the dispersion of ranks is equal across two independent groups. It is used as a nonparametric alternative to the two-independent-sample t test.</p>
<p><strong>Paired-samples <span class="math inline">\(t\)</span> test</strong> is used to pair individuals on similar key variables.</p>
<p><strong>Related-samples <span class="math inline">\(t\)</span> test</strong> typically means you have the same participants measured on two dependent variables that use the same scale, such as math vs reading tests, or under a control condition vs under a treatment condition.</p>
<p><strong>Repeated-measures <span class="math inline">\(t\)</span> test</strong> is used to test one group of participants twice on the same measure at different points in time.</p>
<p><strong>Wilcoxon’s Matched-Pairs Signed-Ranks Test</strong> is a nonparametric alternative to the related-samples (or repeated-measures) t test.</p>
</section>
<section id="check-your-understanding" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="check-your-understanding">Check Your Understanding</h2>
<ol type="1">
<li><p><strong>What is the main difference between an independent-samples t test and a related-samples t test?</strong></p>
<ol type="a">
<li><p>Independent-samples <span class="math inline">\(t\)</span> tests compare two separate groups, while related-samples t tests compare two sets of scores from the same group or matched individuals.</p></li>
<li><p>Independent-samples <span class="math inline">\(t\)</span> tests compare means to a population value, while related-samples t tests compare variances.</p></li>
<li><p>Independent-samples <span class="math inline">\(t\)</span> tests require categorical data, while related-samples t tests require continuous data.</p></li>
<li><p>There is no difference; they are used interchangeably.</p></li>
</ol></li>
<li><p><strong>Which assumption is unique to independent-samples t tests but not required for related-samples t tests?</strong></p>
<ol type="a">
<li><p>Normality</p></li>
<li><p>Random sampling</p></li>
<li><p>Equal variances</p></li>
<li><p>Independence of scores within groups</p></li>
</ol></li>
<li><p><strong>When would you use a one-sample t test instead of an independent- or related-samples t test?</strong></p>
<ol type="a">
<li><p>When you have two independent groups to compare.</p></li>
<li><p>When you want to compare a single group to a known population mean.</p></li>
<li><p>When you compare pre- and post-test scores from the same group.</p></li>
<li><p>When you have categorical data.</p></li>
</ol></li>
<li><p><strong>You are conducting a study to compare the effectiveness of two teaching methods on student performance. You have a small sample size of just 16 students (8 students taught by different teachers in different classrooms – there is no reason to suggest they are related) and the scores in your dataset are not normally distributed. Which test should you use to compare these scores?</strong></p>
<ol type="a">
<li><p>Mann-Whitney <span class="math inline">\(U\)</span> test</p></li>
<li><p>Wilcoxon Matched-Pairs Signed-Ranks Test</p></li>
<li><p>Independent-samples <span class="math inline">\(t\)</span> test</p></li>
<li><p>One-sample <span class="math inline">\(t\)</span> test</p></li>
</ol></li>
<li><p><strong>Which effect size measure is commonly reported for independent-samples t tests?</strong></p>
<ol type="a">
<li><p><span class="math inline">\(r^2\)</span></p></li>
<li><p>Phi coefficient</p></li>
<li><p>Cohen’s <span class="math inline">\(d\)</span></p></li>
<li><p>Omega</p></li>
</ol></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter8.html" class="pagination-link" aria-label="Chapter 8">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 8</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter10.html" class="pagination-link" aria-label="Chapter 10">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 10</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>