<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>13&nbsp; Chapter 13 – Stats Textbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter14.html" rel="next">
<link href="./chapter12.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f2c6d6e2b784ddc5de38779acc06f37d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<script>

  window.hypothesisConfig = function () {

    return {

      openSidebar: false,

      showHighlights: true

    };

  };

</script>

<script src="https://hypothes.is/embed.js" async=""></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter13.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 13</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Stats Textbook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Chapter 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 4</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 5</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 6</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 7</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 8</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 9</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 10</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 11</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 12</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter13.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 13</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 14</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./answerkey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Answer Key</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#analyzing-change-and-adjusting-for-covariates" id="toc-analyzing-change-and-adjusting-for-covariates" class="nav-link active" data-scroll-target="#analyzing-change-and-adjusting-for-covariates">Analyzing Change and Adjusting for Covariates</a>
  <ul class="collapse">
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#sources-of-variation-in-the-one-way-repeated-measures-anova" id="toc-sources-of-variation-in-the-one-way-repeated-measures-anova" class="nav-link" data-scroll-target="#sources-of-variation-in-the-one-way-repeated-measures-anova"><span class="header-section-number">13.1</span> Sources of Variation in the One-Way Repeated-Measures ANOVA</a>
  <ul class="collapse">
  <li><a href="#between-groups-variation-treatment-effect" id="toc-between-groups-variation-treatment-effect" class="nav-link" data-scroll-target="#between-groups-variation-treatment-effect"><span class="header-section-number">13.1.1</span> Between-Groups Variation (Treatment Effect)</a></li>
  <li><a href="#within-groups-variation-error-variation" id="toc-within-groups-variation-error-variation" class="nav-link" data-scroll-target="#within-groups-variation-error-variation"><span class="header-section-number">13.1.2</span> Within-Groups Variation (Error Variation)</a></li>
  </ul></li>
  <li><a href="#degrees-of-freedom-in-the-repeated-measures-anova" id="toc-degrees-of-freedom-in-the-repeated-measures-anova" class="nav-link" data-scroll-target="#degrees-of-freedom-in-the-repeated-measures-anova"><span class="header-section-number">13.2</span> Degrees of Freedom in the Repeated-Measures ANOVA</a></li>
  <li><a href="#calculating-a-repeated-measures-anova" id="toc-calculating-a-repeated-measures-anova" class="nav-link" data-scroll-target="#calculating-a-repeated-measures-anova"><span class="header-section-number">13.3</span> Calculating a Repeated-Measures ANOVA</a>
  <ul class="collapse">
  <li><a href="#assumptions-of-a-repeated-measures-anova" id="toc-assumptions-of-a-repeated-measures-anova" class="nav-link" data-scroll-target="#assumptions-of-a-repeated-measures-anova"><span class="header-section-number">13.3.1</span> Assumptions of a Repeated-Measures ANOVA</a></li>
  <li><a href="#conducting-a-repeated-measures-anova" id="toc-conducting-a-repeated-measures-anova" class="nav-link" data-scroll-target="#conducting-a-repeated-measures-anova"><span class="header-section-number">13.3.2</span> Conducting a Repeated-Measures ANOVA</a></li>
  <li><a href="#measuring-effect-size" id="toc-measuring-effect-size" class="nav-link" data-scroll-target="#measuring-effect-size"><span class="header-section-number">13.3.3</span> Measuring Effect Size</a></li>
  </ul></li>
  <li><a href="#post-hoc-comparisons" id="toc-post-hoc-comparisons" class="nav-link" data-scroll-target="#post-hoc-comparisons"><span class="header-section-number">13.4</span> Post Hoc Comparisons</a></li>
  <li><a href="#analysis-of-covariance-ancova" id="toc-analysis-of-covariance-ancova" class="nav-link" data-scroll-target="#analysis-of-covariance-ancova"><span class="header-section-number">13.5</span> Analysis of Covariance (ANCOVA) </a>
  <ul class="collapse">
  <li><a href="#why-use-ancova" id="toc-why-use-ancova" class="nav-link" data-scroll-target="#why-use-ancova"><span class="header-section-number">13.5.1</span> Why use ANCOVA? </a></li>
  <li><a href="#assumptions-for-ancova" id="toc-assumptions-for-ancova" class="nav-link" data-scroll-target="#assumptions-for-ancova"><span class="header-section-number">13.5.2</span> Assumptions for ANCOVA</a></li>
  <li><a href="#another-use-of-ancova-adjusted-means" id="toc-another-use-of-ancova-adjusted-means" class="nav-link" data-scroll-target="#another-use-of-ancova-adjusted-means"><span class="header-section-number">13.5.3</span> Another Use of ANCOVA: Adjusted Means </a></li>
  <li><a href="#homogeneity-of-regression-slopes-1" id="toc-homogeneity-of-regression-slopes-1" class="nav-link" data-scroll-target="#homogeneity-of-regression-slopes-1"><span class="header-section-number">13.5.4</span> Homogeneity of Regression Slopes </a></li>
  <li><a href="#testing-the-interaction" id="toc-testing-the-interaction" class="nav-link" data-scroll-target="#testing-the-interaction"><span class="header-section-number">13.5.5</span> Testing the Interaction </a></li>
  <li><a href="#more-complex-ancovas" id="toc-more-complex-ancovas" class="nav-link" data-scroll-target="#more-complex-ancovas"><span class="header-section-number">13.5.6</span> More Complex ANCOVAS</a></li>
  <li><a href="#grouping-variable-with-2-levels" id="toc-grouping-variable-with-2-levels" class="nav-link" data-scroll-target="#grouping-variable-with-2-levels">Grouping Variable with &gt; 2 Levels</a></li>
  <li><a href="#factorial-ancova" id="toc-factorial-ancova" class="nav-link" data-scroll-target="#factorial-ancova"><span class="header-section-number">13.5.7</span> Factorial ANCOVA</a></li>
  <li><a href="#multiple-covariates" id="toc-multiple-covariates" class="nav-link" data-scroll-target="#multiple-covariates"><span class="header-section-number">13.5.8</span> Multiple Covariates</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">13.6</span> Summary</a></li>
  </ul></li>
  <li><a href="#analyzing-change-and-adjusting-for-covariates-in-r" id="toc-analyzing-change-and-adjusting-for-covariates-in-r" class="nav-link" data-scroll-target="#analyzing-change-and-adjusting-for-covariates-in-r">Analyzing Change and Adjusting for Covariates in R</a>
  <ul class="collapse">
  <li><a href="#repeated-measures-anova" id="toc-repeated-measures-anova" class="nav-link" data-scroll-target="#repeated-measures-anova">1 Repeated-Measures ANOVA</a>
  <ul class="collapse">
  <li><a href="#preparing-the-data" id="toc-preparing-the-data" class="nav-link" data-scroll-target="#preparing-the-data">1.1 Preparing the data</a></li>
  <li><a href="#running-the-repeated-measures-anova" id="toc-running-the-repeated-measures-anova" class="nav-link" data-scroll-target="#running-the-repeated-measures-anova">1.2 Running the repeated-measures ANOVA</a></li>
  <li><a href="#post-hoc-comparisons-1" id="toc-post-hoc-comparisons-1" class="nav-link" data-scroll-target="#post-hoc-comparisons-1">1.3 Post Hoc Comparisons</a></li>
  </ul></li>
  <li><a href="#ancova" id="toc-ancova" class="nav-link" data-scroll-target="#ancova">2 ANCOVA</a>
  <ul class="collapse">
  <li><a href="#running-ancova" id="toc-running-ancova" class="nav-link" data-scroll-target="#running-ancova">2.1 Running ANCOVA</a></li>
  <li><a href="#school-type-effect" id="toc-school-type-effect" class="nav-link" data-scroll-target="#school-type-effect">2.1.1 School Type Effect</a></li>
  <li><a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions">2.2 Checking assumptions</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#analyzing-change-and-adjusting-for-covariates-in-spss" id="toc-analyzing-change-and-adjusting-for-covariates-in-spss" class="nav-link" data-scroll-target="#analyzing-change-and-adjusting-for-covariates-in-spss">Analyzing Change and Adjusting for Covariates in SPSS</a>
  <ul class="collapse">
  <li><a href="#repeated-measures-anova-1" id="toc-repeated-measures-anova-1" class="nav-link" data-scroll-target="#repeated-measures-anova-1">1 Repeated-Measures ANOVA</a>
  <ul class="collapse">
  <li><a href="#running-the-repeated-measures-anova-1" id="toc-running-the-repeated-measures-anova-1" class="nav-link" data-scroll-target="#running-the-repeated-measures-anova-1">1.1 Running the repeated-measures ANOVA</a></li>
  <li><a href="#post-hoc-comparisons-2" id="toc-post-hoc-comparisons-2" class="nav-link" data-scroll-target="#post-hoc-comparisons-2">1.2 Post Hoc Comparisons</a></li>
  </ul></li>
  <li><a href="#ancova-1" id="toc-ancova-1" class="nav-link" data-scroll-target="#ancova-1">2 ANCOVA</a></li>
  <li><a href="#running-ancova-1" id="toc-running-ancova-1" class="nav-link" data-scroll-target="#running-ancova-1">2.1 Running ANCOVA</a>
  <ul class="collapse">
  <li><a href="#checking-assumptions-1" id="toc-checking-assumptions-1" class="nav-link" data-scroll-target="#checking-assumptions-1">2.2 Checking assumptions</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#key-takeaways-for-educational-researchers-from-chapter-13" id="toc-key-takeaways-for-educational-researchers-from-chapter-13" class="nav-link" data-scroll-target="#key-takeaways-for-educational-researchers-from-chapter-13">Key Takeaways for Educational Researchers from Chapter 13</a></li>
  <li><a href="#key-definitions-from-chapter-13" id="toc-key-definitions-from-chapter-13" class="nav-link" data-scroll-target="#key-definitions-from-chapter-13">Key Definitions from Chapter 13</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding">Check Your Understanding</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 13</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="analyzing-change-and-adjusting-for-covariates" class="level1 unnumbered">
<h1 class="unnumbered">Analyzing Change and Adjusting for Covariates</h1>
<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li><p>Explain the fundamentals of repeated-measures ANOVA, including its application in testing differences across multiple conditions or time points for the same participants, and recognize the advantages of within-subjects designs in reducing error variance.</p></li>
<li><p>Identify the assumptions underlying repeated-measures ANOVA, particularly the concept of sphericity, and apply appropriate corrections (e.g., Greenhouse-Geisser or Huynh-Feldt adjustments) when these assumptions are violated to ensure valid statistical conclusions.</p></li>
<li><p>Explain the purpose and application of Analysis of Covariance (ANCOVA), including how it controls for covariates to reduce error variance, and interpret ANCOVA results in the context of experimental and non-experimental research.</p></li>
</ul>
<p>A <strong>repeated-measures ANOVA</strong> is used to determine whether there are significant differences between three or more related groups or measurements taken from the same participants under different conditions, at different time points, or across repeated trials. Similar to how a one-way between-subjects ANOVA extends the independent-samples t test, the one-way repeated-measures ANOVA extends the repeated-measures t test (also known as the related-samples t test or dependent-samples t test).</p>
<p>The term <em>one-way</em> indicates that only one factor is being tested, while within-subjects signifies that the same set of participants is measured across all conditions, eliminating between-subject variability and increasing statistical power.</p>
<p>An example of a longitudinal study would be measuring a group of college students at one point during each of their four undergraduate years to track changes in a dependent variable over time. This design is considered longitudinal because the same individuals are measured repeatedly across different time points. A repeated-measures ANOVA would be appropriate here.</p>
<p>In contrast, if students were only measured once and grouped based on their current year in college (e.g., first-year, sophomore, junior, senior), the study would be classified as a cross-sectional design rather than longitudinal. In this case, a repeated-measures ANOVA would not be appropriate, as each student would only contribute a single measurement rather than repeated observations over time.</p>
<p>Throughout this chapter, we will continue to discuss differences between groups, but it is important to remember that in a one-way repeated-measures ANOVA, we are examining the same individuals measured at different time points or under different conditions. Instead of thinking in terms of distinct groups of people, it is more accurate to consider them as groups of scores on a dependent variable, collected from the same participants. In a one-way repeated-measures ANOVA, there is only one group of individuals, and their responses are analyzed across multiple measurements.</p>
</section>
<section id="sources-of-variation-in-the-one-way-repeated-measures-anova" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="sources-of-variation-in-the-one-way-repeated-measures-anova"><span class="header-section-number">13.1</span> Sources of Variation in the One-Way Repeated-Measures ANOVA</h2>
<p>We already learned how to analyze group mean differences with the one-way between-subjects ANOVA; when data are collected from a different group of participants for each condition. We apply the same idea to test our hypotheses with the one-way within-subjects ANOVA. Either way, the test statistic has the same basic format:</p>
<p><span class="math display">\[
F = \frac{MS_{BG}}{MS_E}
\]</span></p>
<p>In a repeated-measures ANOVA, we analyze the variance associated with group membership, where a ‘group’ represents a point in time or experimental condition. We also examine the variance that is not associated with group membership, known as error variance.</p>
<p>Unlike a one-way between-subjects ANOVA, a repeated-measures ANOVA introduces an additional source of variation: within-subject variability. This requires a slight adjustment in how we calculate degrees of freedom. While the between-groups variation remains the same, the error variance is divided into two components:</p>
<ul>
<li><p>Variance due to individual differences (accounting for variability within participants).</p></li>
<li><p>Residual error variance (remaining unexplained variation).</p></li>
</ul>
<p>This separation allows for a more precise estimation of effects while controlling for individual differences.</p>
<p>We will guide you through understanding each type of variation in a repeated-measures ANOVA, but we will not be performing any manual calculations. If you want to understand how to calculate the test statistics by hand, websites like <a href="https://statistics.laerd.com/statistical-guides/repeated-measures-anova-statistical-guide-2.php">Laerd Statistics</a> provides a clear example.</p>
<section id="between-groups-variation-treatment-effect" class="level3" data-number="13.1.1">
<h3 data-number="13.1.1" class="anchored" data-anchor-id="between-groups-variation-treatment-effect"><span class="header-section-number">13.1.1</span> Between-Groups Variation (Treatment Effect)</h3>
<p>This component represents the variation between different conditions or time points in a repeated-measures ANOVA. You should already be familiar with this concept:</p>
<ul>
<li><p>Calculate the mean for each group (condition or time point).</p></li>
<li><p>Subtract each group mean from the overall grand mean.</p></li>
<li><p>Square each difference and sum them up.</p></li>
</ul>
<p>The resulting value is the sum of squares between groups (<span class="math inline">\(SS_{BG}\)</span>), which quantifies how much variability in the dependent variable is due to differences between conditions rather than random error.</p>
</section>
<section id="within-groups-variation-error-variation" class="level3" data-number="13.1.2">
<h3 data-number="13.1.2" class="anchored" data-anchor-id="within-groups-variation-error-variation"><span class="header-section-number">13.1.2</span> Within-Groups Variation (Error Variation)</h3>
<p>The process of calculating within-groups variation begins similarly to between-groups variation:</p>
<ul>
<li><p>Compute the mean for each group (condition or time point).</p></li>
<li><p>Subtract this mean from each individual’s score.</p></li>
<li><p>Square the differences and sum them up to obtain the sum of squares within groups (<span class="math inline">\(SS_{WG}\)</span>).</p></li>
</ul>
<p>However, in a repeated-measures ANOVA, we go one step further by splitting the error variance into two components, based on the two primary reasons why individual scores may differ within a group:</p>
<ol type="1">
<li><p>Measurement Error</p>
<p>No assessment is perfectly reliable—there may be sampling error, inconsistencies in measurement, or external factors affecting performance (e.g., a participant having a bad day). These random fluctuations introduce noise into the data, contributing to the error term.</p></li>
<li><p>Individual Differences</p>
<p>Some people naturally perform better or worse on a dependent variable, regardless of the time point or condition. These stable individual differences can influence results and complicate interpretations in between-subjects designs.</p></li>
</ol>
<p>The second reason is a common challenge with educational research. If we are assessing the results of an intervention and we have three different classrooms of students, it is hard to know if different outcomes are due to our intervention or if the students are just different. But here is the magic of a repeated-measures ANOVA: this time, they are not different. They are the same people in every condition, or at every time period. Any differences in ability, motivation or anything else are the same across groups. Each person brings the same differences to each point in time or condition. We can quantify those differences and then remove them from the error term.</p>
<p>How do we do that? To remove individual differences from the error term, we calculate the sum of squares between persons (<span class="math inline">\(SS_{BP}\)</span>) using the following steps:</p>
<ul>
<li><p>Calculate each individual’s mean score across all time points or conditions.</p></li>
<li><p>Subtract this individual mean from the overall grand mean (the mean across all participants and conditions).</p></li>
<li><p>Square each difference and sum them up.</p></li>
</ul>
<p>The result is the sum of squares between persons (<span class="math inline">\(SS_{BP}\)</span>), which quantifies variability due to stable individual differences. By accounting for and removing this variation, a repeated-measures ANOVA isolates the true effect of the independent variable, improving statistical power and reducing error.</p>
</section>
</section>
<section id="degrees-of-freedom-in-the-repeated-measures-anova" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="degrees-of-freedom-in-the-repeated-measures-anova"><span class="header-section-number">13.2</span> Degrees of Freedom in the Repeated-Measures ANOVA</h2>
<p>We are going to keep reminding you of this, but everything we do with an ANOVA comes back to the concept of variance, and you should remember that <span class="math inline">\(variance = \frac{sum\,of\,squares}{degrees\,of\,freedom\,(df)}\)</span>. In other words, to get from multiple <em>sum of squares</em> values to actual variance estimates, we need to divide them by the degrees of freedom. With a between-subjects ANOVA we have two separate degrees of freedom but now with repeated-measures ANOVA we have three.</p>
<p>It is easier to understand this with an example. Imagine we have a study with 20 (<span class="math inline">\(n = 20\)</span>) participants being tested at three points in time (<span class="math inline">\(k = 3\)</span>), which means we have 60 total data points.</p>
<p><strong><em>Degrees of Freedom for Example</em></strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 55%">
<col style="width: 30%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Source of variation</th>
<th>Formula</th>
<th>df value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total</td>
<td>k*n − 1</td>
<td>59</td>
</tr>
<tr class="even">
<td><strong>Between groups (Conditions)</strong></td>
<td><strong>k − 1</strong></td>
<td><strong>2</strong></td>
</tr>
<tr class="odd">
<td>Between persons (Participants/Subjects)</td>
<td>n − 1</td>
<td>19</td>
</tr>
<tr class="even">
<td><strong>Within groups (Error)</strong></td>
<td><strong>(k − 1)(n − 1)</strong></td>
<td><strong>38</strong></td>
</tr>
</tbody>
</table>
<p>The two rows in bold in the previous table are the degrees of freedom you use to find the critical value for the F test, and they are the ones you include when reporting results. Please note that the degrees of freedom listed here are only applicable when the sphericity assumption, which we will explain later in the chapter, is satisfied.</p>
</section>
<section id="calculating-a-repeated-measures-anova" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="calculating-a-repeated-measures-anova"><span class="header-section-number">13.3</span> Calculating a Repeated-Measures ANOVA</h2>
<p>It’s time to revisit fractions to understand why a within-subjects ANOVA generally has greater statistical power than a between-subjects ANOVA, and when it does not.</p>
<p>We begin with the familiar formula for the F statistic:</p>
<p><span class="math display">\[
F_{obt} = \frac{MS_{BG}}{MS_E}
\]</span></p>
<p>The following table summarizes how these values are calculated, though it refers to “conditions” rather than “between-groups” for clarity. Understanding these components will help explain why within-subjects designs often result in greater power compared to between-subjects designs—and when that advantage might not hold.</p>
<div class="formula-table">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 3%">
<col style="width: 14%">
<col style="width: 33%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Source of Variation</th>
<th>SS</th>
<th>df*</th>
<th>MS</th>
<th>F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Between Groups (Conditions)</td>
<td></td>
<td><span class="math inline">\(k - 1\)</span></td>
<td><span class="math inline">\(\frac{SS_{BG}}{df_{BG}}\)</span></td>
<td><span class="math inline">\(\frac{MS_{BG}}{MS_E}\)</span></td>
</tr>
<tr class="even">
<td>Between Persons</td>
<td></td>
<td><span class="math inline">\(n - 1\)</span></td>
<td><span class="math inline">\(\frac{SS_{Subjects}}{df_{Subjects}}\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td>Within Groups (Error)</td>
<td></td>
<td><span class="math inline">\((k - 1)(n - 1)\)</span></td>
<td><span class="math inline">\(\frac{SS_E}{df_E}\)</span></td>
<td></td>
</tr>
<tr class="even">
<td>Total</td>
<td></td>
<td><span class="math inline">\(kn - 1\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
<p>Remember that a mean square is the same as a variance. To find <span class="math inline">\(MS_{BG}\)</span>, we find the <span class="math inline">\(SS_{BG}\)</span> and divide by <span class="math inline">\(df_{BG}\)</span>, which is <span class="math inline">\(k – 1\)</span>. This is the value for the numerator of our fraction. The bigger this value is, the more likely we are to get a significant result.</p>
<p><span class="math inline">\(MS_E\)</span> is a little more complicated because we have to divide it into two parts. We first find the total <span class="math inline">\(SS_E\)</span>, and then we figure out how much of that is due to differences between people, which is the <span class="math inline">\(SS_{Subjects}\)</span>. We subtract out the part of the error that is due to people being different, and we are left with the <span class="math inline">\(SS_E\)</span> that we truly consider error. We divide this by the <span class="math inline">\(df_E\)</span>, which is <span class="math inline">\((k – 1)(n – 1)\)</span>, and we have <span class="math inline">\(MS_E\)</span> for the denominator of the fraction. The smaller this value is, the more likely we are to get a significant result.</p>
<p>Here is where we talk about power, and why the repeated measures ANOVA usually has more power than a between-subjects ANOVA. If the <span class="math inline">\(MS_E\)</span> value is smaller, our fraction gets bigger, right? So how are <span class="math inline">\(MS_E\)</span> values different in the two types of ANOVAs?</p>
<ul>
<li><p>The big difference is that with a repeated-measures ANOVA, we can remove a major component of the error variance. All the error that is due to people being different gets removed from the equation altogether. This tends to make the error variance much smaller in a repeated-measures ANOVA, and therefore we have more statistical power.</p></li>
<li><p>The other difference, however, is in the degrees of freedom. In a between-subjects ANOVA, if we had three separate groups of 20 participants each, our total sample size would be 60. The degrees of freedom for error would be calculated as: <span class="math inline">\(df_E=n−k=60−3=57\)</span>. In the example repeated-measures ANOVA, we have a total of 20 participants, and the degrees of freedom for error are calculated as: <span class="math inline">\(df_E=(k−1)(n−1)=38\)</span>. Although the sum of squares for error (<span class="math inline">\(SS_E\)</span>) is smaller in a repeated-measures design—because we remove variance due to individual differences—the <span class="math inline">\(MS_E\)</span> is calculated by dividing <span class="math inline">\(SS_E\)</span> by the smaller degrees of freedom (38 instead of 57). This trade-off slightly offsets the advantage of reducing <span class="math inline">\(SS_E\)</span> but usually does not eliminate the overall gain in power.</p></li>
</ul>
<p>Whether or not we end up with a more powerful test depends on if the reduction in <span class="math inline">\(SS_E\)</span> more than compensates for the reduction in degrees of freedom for the error term. It does most of the time because we can usually take out quite a bit of error.</p>
<p>If participants behave consistently across all time points or conditions, meaning they differ from one another in the same way each time, then a repeated-measures ANOVA allows us to remove a substantial amount of error.</p>
<p>To understand this, recall how we determine how much error can be removed due to between-person differences. We do this by subtracting each individual’s average score across all conditions from the overall grand mean.</p>
<ul>
<li><p>If a participant is <em>consistently above</em> the mean across all conditions, their <em>overall average</em> will also be above the mean, allowing us to partial out that difference completely.</p></li>
<li><p>Conversely, if a participant scores <em>above the mean in one condition, below the mean in another, and close to the mean in a third</em>, their <em>overall average</em> will be very close to the grand mean. In this case, there is little individual variation to remove.</p></li>
</ul>
<p>Thus, the more <em>consistent</em> individuals are in their responses across conditions, the greater the reduction in error variance, increasing the statistical power of the analysis.</p>
<section id="assumptions-of-a-repeated-measures-anova" class="level3" data-number="13.3.1">
<h3 data-number="13.3.1" class="anchored" data-anchor-id="assumptions-of-a-repeated-measures-anova"><span class="header-section-number">13.3.1</span> Assumptions of a Repeated-Measures ANOVA</h3>
<p>Most of the assumptions for repeated-measures ANOVA should look familiar.</p>
<ul>
<li><p><em>Normality</em>: We assume the dependent variable is normally distributed in the population and the sample of individuals in our study. This assumption is particularly important when the sample size is small.</p></li>
<li><p><em>Independence</em> within groups: Within each group, participants are independently observed within the group, and the score of one person will not be related to the score of another person in the group.</p></li>
<li><p><em>Homogeneity of variance</em>: The variance of the dependent variable in each group (time period/condition) is the same.</p></li>
<li><p><em>Homogeneity of covariance</em>: We assume that participants’ scores in each group are related because the same participants are observed across the groups/conditions. We also must assume that the extent to which they are related is consistent from one pair of groups to another. Removing the Between-Persons error from the total error only makes sense if the difference between an individual’s average score and the grand mean is representative of all the groups.</p></li>
</ul>
<p>These last two assumptions are together referred to as sphericity. In short, <strong>sphericity</strong> refers to the condition where the variances of the differences between all combinations of related groups (levels of the independent variable) are equal. Violating the assumption of sphericity artificially increases the value of between-group differences, which makes it more likely that we will commit a Type I error and reject the null when there is no true difference in the population.</p>
</section>
<section id="conducting-a-repeated-measures-anova" class="level3" data-number="13.3.2">
<h3 data-number="13.3.2" class="anchored" data-anchor-id="conducting-a-repeated-measures-anova"><span class="header-section-number">13.3.2</span> Conducting a Repeated-Measures ANOVA</h3>
<p>We will once again use data from the vocabulary recall study examining the effect of learning strategies to walk through an example. However, this time, we will assume that the same group of students (n = 10) experienced <em>all four learning strategies</em>, rather than being assigned to only one. This repeated-measures design allows us to analyze how each student’s recall performance varies across the different strategies while controlling for individual differences.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 43%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Repetition</th>
<th>Visualization</th>
<th>Technology-Aided Learning</th>
<th>Control</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>13</td>
<td>17</td>
<td>17</td>
<td>10</td>
</tr>
<tr class="even">
<td>12</td>
<td>15</td>
<td>18</td>
<td>12</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>6</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td>15</td>
<td>16</td>
<td>9</td>
</tr>
<tr class="odd">
<td>11</td>
<td>17</td>
<td>16</td>
<td>12</td>
</tr>
<tr class="even">
<td>9</td>
<td>18</td>
<td>20</td>
<td>4</td>
</tr>
<tr class="odd">
<td>11</td>
<td>18</td>
<td>21</td>
<td>11</td>
</tr>
<tr class="even">
<td>11</td>
<td>14</td>
<td>18</td>
<td>9</td>
</tr>
<tr class="odd">
<td>14</td>
<td>15</td>
<td>20</td>
<td>8</td>
</tr>
<tr class="even">
<td>13</td>
<td>17</td>
<td>19</td>
<td>9</td>
</tr>
<tr class="odd">
<td>8</td>
<td>18</td>
<td>17</td>
<td>5</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(\bar{X} = 11.4\)</span></strong></td>
<td><strong><span class="math inline">\(\bar{X} = 16.4\)</span></strong></td>
<td><strong><span class="math inline">\(\bar{X} = 18.2\)</span></strong></td>
<td><strong><span class="math inline">\(\bar{X} = 8.9\)</span></strong></td>
</tr>
</tbody>
</table>
<section id="step-1-determine-the-null-and-alternative-hypotheses." class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-1-determine-the-null-and-alternative-hypotheses.">Step 1: Determine the null and alternative hypotheses.</h4>
<p>The hypotheses for a one-way repeated measures ANOVA are the same as those for the one-way ANOVA, which are as follows: </p>
<p>For k groups,</p>
<p><span class="math display">\[
H_0: μ_1 = μ_2 =  … = μ_k \text{(all group means are equal) }
\]</span></p>
<p><span class="math display">\[
H_a: \text{not all the } μ_i \text{ are equal(at least one group means differ from the others)} 
\]</span></p>
<p>In our example, k = 4 and thus,</p>
<p><span class="math display">\[
H_0: μ_1 = μ_2 = μ_3 = μ_4
\]</span></p>
<p>or</p>
<p><span class="math display">\[
H_0: μ_{Repetition} = μ_{Visual} = μ_{TechAid} = μ_{Control}
\]</span></p>
<p><span class="math display">\[
H_a: \text{not all the }μ_i \text{are equal (at least one group mean differs from the others)}
\]</span></p>
</section>
<section id="step-2-set-the-criteria-for-a-decision." class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-2-set-the-criteria-for-a-decision.">Step 2: Set the criteria for a decision. </h4>
<p>Let’s set the alpha level at 0.05. In our example, n = 10 with four conditions, so the sampling distribution of F ratio follows F distribution with <span class="math inline">\(df_{BG}=3\)</span>, <span class="math inline">\(df_E=(k−1)(n−1)=3×9=27\)</span> when the sphericity assumption holds. We reject the null hypothesis when the obtained F statistic is larger than 2.96. Later, we will discuss how the dfs are adjusted for evaluating the F statistic when the sphericity assumption is violated to control the Type I error rate.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Figure 13.1 F-distribution with rejection region</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="step-3-check-assumptions-and-compute-the-test-statistic." class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-3-check-assumptions-and-compute-the-test-statistic.">Step 3: Check assumptions and compute the test statistic.   </h4>
<p>We won’t go through all the data assumptions as you should already be familiar with some of them. Instead, we will focus on evaluating the sphericity assumption. We can begin this evaluation with a descriptive analysis, by examining the variance-covariance matrix.</p>
<p>The following table shows the variance and covariance matrix. The diagonal elements of the matrix, shaded in grey, represent the <em>variances</em> of each condition. If these values are substantially different, it may indicate a violation of sphericity. By looking at these values, we see that the variances among four conditions range from 2.27 to 7.21. The variance for the control condition (7.21) is much larger than the others, suggesting that it may contribute to a potential violation of sphericity.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 28%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Learning Strategy</th>
<th>Repetition</th>
<th>Visualization</th>
<th>Technology-Aided Learning</th>
<th>Control</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Repetition</td>
<td><strong>3.38</strong></td>
<td>-1.4</td>
<td>0.24</td>
<td>2.71</td>
</tr>
<tr class="even">
<td>Visualization</td>
<td>-1.4</td>
<td><strong>2.27</strong></td>
<td>0.58</td>
<td>-1.29</td>
</tr>
<tr class="odd">
<td>Technology-Aided Learning</td>
<td>0.24</td>
<td>0.58</td>
<td><strong>3.07</strong></td>
<td>-0.98</td>
</tr>
<tr class="even">
<td>Control</td>
<td>2.71</td>
<td>-1.29</td>
<td>-0.98</td>
<td><strong>7.21</strong></td>
</tr>
</tbody>
</table>
<p>Now, let’s examine the off-diagonal elements. Since the upper and lower triangles contain identical values, we will focus on the upper triangle. These values represent the covariances between different conditions. If the covariances vary substantially, it may indicate a violation of the sphericity assumption. In this case, the covariances range from -1.4 to 2.70, demonstrating considerable variation, particularly since some are positive while others are negative. This pattern suggests a potential violation of the sphericity assumption.</p>
<p>Next, we can formally test this assumption with Mauchly’s test for sphericity. The null and alternative hypotheses of Mauchly’s tests are as follows:</p>
<p><span class="math inline">\(H_0\)</span>: The variances of the differences between conditions are equal.</p>
<p><span class="math inline">\(H_a\)</span>: The variances of the differences between conditions are not equal. (At least one variance differs from the others.)</p>
<p>To meet this assumption, we aim to fail to reject the null hypothesis. The table below summarizes the result of Mauchly’s test, which can be obtained from common statistical software.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 25%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Mauchly’s W</th>
<th>Approx. <span class="math inline">\(\chi^2\)</span></th>
<th><span class="math inline">\(df\)</span></th>
<th><span class="math inline">\(p\)</span></th>
<th>Greenhouse-Geisser <span class="math inline">\(\epsilon\)</span></th>
<th>Huynh-Feldt <span class="math inline">\(\epsilon\)</span></th>
<th>Lower Bound <span class="math inline">\(\epsilon\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.445</td>
<td>6.247</td>
<td>5</td>
<td>0.286</td>
<td>0.666</td>
<td>0.856</td>
<td>0.333</td>
</tr>
</tbody>
</table>
<p>Using <span class="math inline">\(\alpha = 0.05\)</span>, we fail to reject the null hypothesis. Although we observed some inconsistencies in variances and covariances among the four groups, these inconsistencies are not severe enough to violate the assumption. Therefore, we conclude that the sphericity assumption is satisfied in our example. The second half of the table (on the right side) tells us more about the violation, assuming one exists. The epsilon (<span class="math inline">\(\epsilon\)</span>) values are estimates of the degree of sphericity in the population. If they are close to 1.0 then we expect the sphericity assumption has been met. However, if they are substantially less than 1.0, that indicates that the sphericity assumption is violated. The lower the epsilon value is, the worse the violation.</p>
<p>What happens if we violate the assumption of sphericity and obtain a significant result for Mauchly’s test (<span class="math inline">\(p &lt; 0.05\)</span>)? Fortunately, when this assumption is violated, we can adjust the degrees of freedom for the omnibus F test to compensate.</p>
<p>This adjustment is made using epsilon (<span class="math inline">\(\epsilon\)</span>), which is applied to both the numerator and denominator degrees of freedom by multiplying them by the epsilon value. Since higher degrees of freedom increase statistical power, reducing them (by multiplying by a value less than 1.0) makes it more difficult to detect a significant result.</p>
<p>Conceptually, this adjustment acknowledges that our assumptions have not been fully met, so we apply a more <em>conservative approach</em> before rejecting the null hypothesis. The more severe the violation, the <em>lower the epsilon value</em>, leading to a greater reduction in degrees of freedom, making it even harder to obtain statistical significance.</p>
<p>There are three commonly used methods for calculating epsilon, each based on different criteria, and we must decide which one to use. Similar to how we learned about multiple post hoc test options earlier in the book, the three epsilon values differ in how conservative/careful they are.</p>
<ul>
<li><p>The Huynh-Feldt correction is the least conservative.</p></li>
<li><p>Lower-bound is the most conservative.</p></li>
<li><p>The Greenhouse-Geisser correction is somewhere in between.</p></li>
</ul>
<p>Which one should you use? Typically, when epsilons are smaller than 0.75, we suggest using the Greenhouse-Geisser value. If they are above 0.75, it is safe to use the Huynh-Feldt correction. Fortunately, you do not need to do the math yourself because common statistical software will conduct the calculations for you.</p>
<p><strong><em>Within-Subjects Effects</em></strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 29%">
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Cases</th>
<th>Sphericity Correction</th>
<th>Sum of Squares</th>
<th><span class="math inline">\(df\)</span></th>
<th>Mean Square</th>
<th>F</th>
<th>p</th>
<th><span class="math inline">\(\eta^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RM Factor</td>
<td>None (Sphericity Assumed)</td>
<td>558.675</td>
<td>3</td>
<td>186.225</td>
<td>46.524</td>
<td>&lt;.001</td>
<td>0.838</td>
</tr>
<tr class="even">
<td></td>
<td>Greenhouse-Geisser</td>
<td>558.675</td>
<td>1.998</td>
<td>279.687</td>
<td>46.524</td>
<td>&lt;.001</td>
<td>0.838</td>
</tr>
<tr class="odd">
<td></td>
<td>Huynh-Feldt</td>
<td>558.675</td>
<td>2.567</td>
<td>217.642</td>
<td>46.524</td>
<td>&lt;.001</td>
<td>0.838</td>
</tr>
<tr class="even">
<td></td>
<td>Lower-bound</td>
<td>558.675</td>
<td>1</td>
<td>558.675</td>
<td>46.524</td>
<td>&lt;.001</td>
<td>0.838</td>
</tr>
<tr class="odd">
<td>Residuals</td>
<td>None (Sphericity Assumed)</td>
<td>108.075</td>
<td>27</td>
<td>4.003</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Greenhouse-Geisser</td>
<td>108.075</td>
<td>17.978</td>
<td>6.012</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Huynh-Feldt</td>
<td>108.075</td>
<td>23.102</td>
<td>4.678</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Lower-bound</td>
<td>108.075</td>
<td>9</td>
<td>12.008</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>First, observe the various degrees of freedom in the numerator for the repeated conditions. If sphericity is assumed, we use the standard calculation of k − 1, which in this case equals 3. However, when we apply different epsilon (<span class="math inline">\(\epsilon\)</span>) values to adjust for violations of sphericity, the degrees of freedom decrease. At the lower bound, where ε = 0.333, the adjusted degrees of freedom become 3 × 0.333 = 1.0.</p>
<p>Why does the F statistic remain unchanged? If you refer back to the table at the beginning of the chapter, you’ll see that degrees of freedom are multiplied by the same epsilon value in both the numerator and denominator. This proportional adjustment ensures that the calculated F statistic stays the same and only the degrees of freedom change, affecting the significance threshold.</p>
<p>While statistical software handles these calculations automatically, it is important to understand how and why these adjustments are made when sphericity is violated.</p>
</section>
<section id="step-4-find-the-p-value-and-draw-a-conclusion-and-report-your-conclusion.-.unnumbered" class="level4" data-number="13.3.2.1">
<h4 data-number="13.3.2.1" class="anchored" data-anchor-id="step-4-find-the-p-value-and-draw-a-conclusion-and-report-your-conclusion.-.unnumbered"><span class="header-section-number">13.3.2.1</span> Step 4: Find the p value and draw a conclusion and report your conclusion. {.unnumbered} </h4>
<p>Since the data meet the sphericity assumption, we use the result with no adjustment for degrees of freedom and ignore the rest of the rows. As it turns out, our F statistic is much higher than the critical value of 2.96, so we can reject the null hypothesis. We can conclude there is a significant difference in means across recall conditions, <span class="math inline">\(F (3, 27) = 46.524\)</span>, <span class="math inline">\(p &lt; .001\)</span>.</p>
</section>
</section>
<section id="measuring-effect-size" class="level3" data-number="13.3.3">
<h3 data-number="13.3.3" class="anchored" data-anchor-id="measuring-effect-size"><span class="header-section-number">13.3.3</span> Measuring Effect Size</h3>
<p>Once we have determined that group means vary significantly in the population, we next determine the size of this effect using either <span class="math inline">\(\eta^2\)</span> or <span class="math inline">\(\omega^2\)</span>. In a between-subjects ANOVA, we divided <span class="math inline">\(SS_{BG}\)</span> by <span class="math inline">\(SS_{Total}\)</span> to get <span class="math inline">\(\eta^2\)</span> and then corrected that slightly for <span class="math inline">\(\eta^2\)</span>. But remember, with a repeated-measures (or within-groups) ANOVA, we are partialling out some of the total variation because it is due to between-persons differences that are the same across groups. We distinguish these new measures of effect size from the original <span class="math inline">\(\eta^2\)</span> and <span class="math inline">\(\omega^2\)</span> by referring to them as partial <span class="math inline">\(\eta^2\)</span> and partial <span class="math inline">\(\omega^2\)</span>.</p>
<p>To compute partial eta squared (<span class="math inline">\(\eta^2_p\)</span>), we remove <span class="math inline">\(SS_{Persons}\)</span> from <span class="math inline">\(SS_{Total}\)</span>. There are two ways to do this:</p>
<ol type="1">
<li><p>We can subtract <span class="math inline">\(SS_{between persons}\)</span> from <span class="math inline">\(SS_{Total}\)</span>:</p>
<p><span class="math display">\[
\eta^2_p = \frac{SS_{BG}}{SS_{Total}-SS_{Persons}}
\]</span></p></li>
<li><p>Or, we can add <span class="math inline">\(SS_{between groups}\)</span> to <span class="math inline">\(SS_{error}\)</span>:</p>
<p><span class="math display">\[
\eta^2_p = \frac{SS_{BG}}{SS_{BG}+SS_E}
\]</span></p></li>
</ol>
<p>Remember that the original denominator was <span class="math inline">\(SS_{total}\)</span>. In this type of ANOVA, total variation is made up of variation between groups, variation between persons, and error variation. So, we can take the whole and subtract out the part we don’t want to include (option 1), or we can just add up the other two parts (option 2). You will get to the same place, but which one you choose depends on which values are easier to calculate. If software is doing the math for you, then it doesn’t matter.</p>
<p>In our example, it is easier to use option 2. Plug in the numbers and we get:</p>
<p><span class="math display">\[
\eta_p^2 = \frac{558.675}{558.675 + 108.075} = 0.837
\]</span></p>
<p>So partial eta squared for this analysis is 0.837, meaning that 83.7% of the variance in vocabulary recall can be explained by learning strategies.</p>
<p>We also previously learned that <span class="math inline">\(\eta^2\)</span> tends to overestimate the effect, and the more conservative measure of the effect size is <span class="math inline">\(\omega^2\)</span>. For the repeated measures ANOVA, we use partial omega squared, <span class="math inline">\(\omega^2_p\)</span>. We have the same two basic options for calculating partial omega squared as with eta squared, but we will just use the second one since it is easier with our data:</p>
<p><span class="math display">\[
\omega_p^2 = \frac{SS_{BG} - (df_{BG} \cdot MS_E)}{SS_{BG} + SS_E + MS_E}
\]</span></p>
<p>Notice that when the sphericity assumption is violated, we use <span class="math inline">\(df_{BG}\)</span> in the numerator rather than <span class="math inline">\(k – 1\)</span>. If sphericity is assumed, these two values are the same.</p>
<p><span class="math display">\[
\omega_p^2 = \frac{558.675 - (3 \cdot 4.003)}{558.675 + 108.075 + 4.003} = 0.815
\]</span></p>
<p>We conclude that 81.5% of the variation in vocabulary recall is explained by the learning strategies applied.</p>
</section>
</section>
<section id="post-hoc-comparisons" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="post-hoc-comparisons"><span class="header-section-number">13.4</span> Post Hoc Comparisons</h2>
<p>As we previously learned, post hoc tests are computed following a significant ANOVA to determine which pair, or pairs, of group means significantly differ. Since we have four groups, we need to make multiple pairwise comparisons using a post hoc test to determine which means are significantly different. A good starting point is to examine the means plots in Figure 13.2 to identify any patterns in the mean differences. Visualizing the data in this way can provide an initial sense of trends before conducting post hoc tests.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 13.2 Mean scores with confidence intervals by learning strategy</figcaption>
</figure>
</div>
</div>
</div>
<p>Remember, if we conduct multiple pairwise comparisons using repeated-measures t tests the likelihood of committing a Type I error increases. The Bonferroni procedure is best adapted for use following a significant repeated-measures ANOVA. This adjusts the alpha level for each pairwise comparison by dividing the familywise alpha by the total number of pairwise comparisons. In our case there are 6 unique pairs:</p>
<p><span class="math display">\[
\text{testwise alpha} = \frac{\text{familywise alpha}}{\text{total number of pairwise comparisons}} = \frac{0.05}{6} = 0.0083
\]</span></p>
<p>This means each pairwise comparison is evaluated at <span class="math inline">\(\alpha = 0.0083\)</span>, which is quite conservative. In fact, it would be too conservative if the number of groups were much higher, but we don’t have the same number of options in terms of other post hoc tests with a repeated-measures ANOVA, because they don’t use the related-samples <span class="math inline">\(t\)</span> test.</p>
<p><strong><em>Post Hoc Comparisons - RM Factor 1</em></strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Group 1</th>
<th>Group 2</th>
<th>Mean Difference</th>
<th>Lower (95% CI)</th>
<th>Upper (95% CI)</th>
<th>SE</th>
<th><span class="math inline">\(t\)</span></th>
<th><span class="math inline">\(p_{bonf}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Repetition</td>
<td>Visualization</td>
<td>-5.000</td>
<td>-7.547</td>
<td>-2.453</td>
<td>0.895</td>
<td>-5.588</td>
<td>&lt; .001 ***</td>
</tr>
<tr class="even">
<td></td>
<td>Technology-Aided</td>
<td>-6.800</td>
<td>-9.347</td>
<td>-4.253</td>
<td>0.895</td>
<td>-7.600</td>
<td>&lt; .001 ***</td>
</tr>
<tr class="odd">
<td></td>
<td>Control</td>
<td>2.500</td>
<td>-0.047</td>
<td>5.047</td>
<td>0.895</td>
<td>2.794</td>
<td>0.057</td>
</tr>
<tr class="even">
<td>Visualization</td>
<td>Technology-Aided</td>
<td>-1.800</td>
<td>-4.347</td>
<td>0.747</td>
<td>0.895</td>
<td>-2.012</td>
<td>0.326</td>
</tr>
<tr class="odd">
<td></td>
<td>Control</td>
<td>7.500</td>
<td>4.953</td>
<td>10.047</td>
<td>0.895</td>
<td>8.382</td>
<td>&lt; .001 ***</td>
</tr>
<tr class="even">
<td>Technology-Aided</td>
<td>Control</td>
<td>9.300</td>
<td>6.753</td>
<td>11.847</td>
<td>0.895</td>
<td>10.394</td>
<td>&lt; .001 ***</td>
</tr>
</tbody>
</table>
<p>* p &lt; .05, *** p &lt; .001</p>
<p><em>Note</em>. p value and confidence intervals adjusted for comparing a family of 6 estimates (confidence intervals corrected using the Bonferroni method).</p>
<p>When we run the analysis using statistical software, we find that both the Repetition and Control groups are significantly different from both the Visualization and Technology-aided strategies. However, there is no statistically significant difference between the Repetition and Control groups or between Visualization and Technology-aided strategies.</p>
<p><em>APA sample write-up</em>: A study was conducted to examine the effect of learning strategy on the number of words recalled by 10 participants across four different learning strategies. The assumption of sphericity was assessed using Mauchly’s test, and since the assumption was met, no corrections to degrees of freedom were applied. The results of the one-way repeated measures ANOVA showed a significant main effect of learning strategy, <span class="math inline">\(F(3,27) = 46.52\)</span>, <span class="math inline">\(p &lt; .001\)</span>. <span class="math inline">\(\omega^2 = .815\)</span>, indicating that the number of recalled words differed significantly across the four learning strategies. The partial omega squared value indicated a large effect, suggesting that a substantial proportion of the variance in vocabulary recall can be attributed to differences in learning strategy. Pairwise comparisons using Bonferroni-adjusted t tests revealed that both the Repetition and Control groups were significantly different from both the Visualization and Technology-Aided Learning strategies (<span class="math inline">\(p &lt; .05\)</span>). However, the Repetition and Control groups were not significantly different from each other after Bonferroni adjustment.</p>
</section>
<section id="analysis-of-covariance-ancova" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="analysis-of-covariance-ancova"><span class="header-section-number">13.5</span> Analysis of Covariance (ANCOVA) </h2>
<p><strong>Analysis of Covariance (ANCOVA)</strong> is a statistical technique used to evaluate whether there are significant differences between groups on a dependent variable while statistically controlling for the effects of one or more continuous variables (called covariates). It offers a combination of multiple regression and analysis of variance. We believe the best place to start is to consider the relationship between ANOVA, ANCOVA, and multiple regression as these are all forms of the General Linear Model. The difference has to do with what independent variables you are using. </p>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 22%">
<col style="width: 40%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>ANOVA</th>
<th>ANCOVA</th>
<th>Multiple Regression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DV</td>
<td>Continuous normally distributed variable</td>
<td>Continuous normally distributed variable</td>
<td>Continuous normally distributed variable</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>+ Categorical (grouping) variables</td>
<td></td>
</tr>
<tr class="odd">
<td>IV</td>
<td>Categorical (grouping) variable(s)</td>
<td>Categorical (grouping) variables + Continuous variables (covariates)</td>
<td>Continuous variables (interval or ordinal) + Dummy coded variables</td>
</tr>
</tbody>
</table>
<p>Notice that all three require a dependent variable that is continuous and normally distributed. A traditional ANOVA has categorical grouping variables (e.g., treatment/control, education level) for the independent variable(s). A traditional multiple regression has continuous predictors for independent variables. You can also include categorical variables in regression by using dummy variables, which is a way of turning a categorical variable into something that can be treated like it’s continuous in the regression model.</p>
<p> </p>
<section id="why-use-ancova" class="level3" data-number="13.5.1">
<h3 data-number="13.5.1" class="anchored" data-anchor-id="why-use-ancova"><span class="header-section-number">13.5.1</span> Why use ANCOVA? </h3>
<p>We use ANCOVA if our primary focus is on the categorical grouping variable, but we want to include a continuous variable as a covariate. First, we need to understand what is meant by a “covariate” here. A covariate is a continuous variable that is included in the analysis to account for variability in the dependent variable that is not directly related to the independent variable(s). By controlling for the covariate, ANCOVA provides a clearer understanding of the relationship between the independent variable(s) and the dependent variable. Along with being a continuous variable, an appropriate covariate is: </p>
<ul>
<li><p>correlated with your dependent variable;</p></li>
<li><p>not highly correlated with/predictive of your independent variable; and  </p></li>
<li><p>not something you’re interested in interpreting as part of your analysis.  </p></li>
</ul>
<p>  Remember that with any ANOVA, we are comparing the variance explained by our grouping variable(s) to error variance. Anything we can do to reduce the error variance gives our analysis greater power to detect a significant effect. ANCOVA allows us to subtract out part of the error variation that can be explained by a covariate. You are using the covariate to reduce the noise (error variation), so the differences associated with your actual independent variable(s) are easier to detect. </p>
<p>Now we should think about what would make a covariate an effective noise-reducer, and to do that we need to think about sources of variation. Figure 13.3 represents the total variation in our dependent variable. This is broken into two sources: variation due to our model, which potentially includes both main effects and interactions, and variation due to error.  </p>
<div class="cell" data-layout-align="center" data-fig_cap="Figure 13.3">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>If we include a covariate in the model, we want it to take away from the error variation <em>without also reducing the between groups variation</em>. This is why we want a covariate that is correlated with the dependent variable but not with the independent variable. Figure 13.4 represents our ideal scenario: </p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Figure 13.4</figcaption>
</figure>
</div>
</div>
</div>
<p>In figure 13.4 the covariate is highly correlated with our dependent variable, but not at all with the independent variables. It explains quite a bit of the error variation without removing any of the variation that we could explain with our independent variable. This combination is hard to come by in real life because more often covariates are related to each other, so we end up with something like this:  </p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Figure 13.5</figcaption>
</figure>
</div>
</div>
</div>
<p>In this case, our covariate is associated with both the independent variable and the dependent variable. While we remove some of that noise (error variation), we also remove some of our between-groups variation.  </p>
<p>  Consider two examples. First, imagine an experiment where first-year college students are randomly assigned to either a control group or one of two intervention groups designed to improve study skills. Our goal is to determine whether participation in an intervention group is associated with an increase in first-semester GPA (our dependent variable).</p>
<p>However, other factors may also influence GPA. Even though students were randomly assigned, each group consists of different individuals who may have varying study habits and academic abilities. These pre-existing differences are unrelated to the intervention but add noise to the data, making it harder to detect meaningful effects.</p>
<p>By using ANCOVA (Analysis of Covariance), we can include high school GPA as a covariate. This allows us to control for prior academic achievement, removing any variation in first-semester GPA that can be explained by differences in high school GPA. As a result, the analysis focuses more directly on the impact of the intervention, increasing the likelihood of detecting a true effect.</p>
<p>  Now, consider a different scenario where students were not randomly assigned to the control or intervention groups. Instead, university administrators used a “risk” score to determine placement: students with the highest risk scores were assigned to an intensive intervention, those with moderate risk scores received a less intensive intervention, and students with lower risk scores received no intervention.</p>
<p>In this case, high school GPA likely contributed to the risk score, meaning that including it as a covariate in an ANCOVA would not only reduce error variation but also reduce the variation between groups, which would undermine the analysis. This setup would be inappropriate for ANCOVA, as the covariate (high school GPA) is directly related to how students were assigned to groups rather than being an independent factor.</p>
<p>This example highlights a key requirement for selecting an appropriate covariate: it should be correlated with the dependent variable but not with the independent variable(s).</p>
<p>Now, consider the last bullet point about appropriate covariates. If the goal were to study the relationship between high school GPA and first-semester college GPA, then high school GPA should be treated as an independent variable rather than a covariate. However, in this analysis, we are not interested in explaining that well-established relationship. Instead, high school GPA is included only as a covariate to reduce error variation and increase statistical power when testing for differences in first-semester GPA based on the intervention groups.</p>
<p> </p>
</section>
<section id="assumptions-for-ancova" class="level3" data-number="13.5.2">
<h3 data-number="13.5.2" class="anchored" data-anchor-id="assumptions-for-ancova"><span class="header-section-number">13.5.2</span> Assumptions for ANCOVA</h3>
<p>ANCOVA has the same assumptions as ANOVA: normality, independence, random sampling, and homogeneity of variance/covariance depending on if you’re using between-subjects or within-subjects factors. There are also two new assumptions.  </p>
<section id="independence-of-the-covariate-and-the-treatment-effect" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="independence-of-the-covariate-and-the-treatment-effect">Independence of the Covariate and the Treatment Effect </h4>
<p>In a traditional ANCOVA, the covariate is associated with the dependent variable but not the independent variable. A violation of this assumption is the problem we just described. If your covariate influences the independent variable as well as the dependent variable, it won’t work as designed because it will reduce variation associated with your treatment/independent variable as well as error variation.  </p>
<p>To check this, you can use a <span class="math inline">\(t\)</span> test or a one-way ANOVA, depending on if your independent variable has two or more levels, to see if group membership predicts scores on the covariate. Going back to the prior example where students were randomly assigned to intervention or control groups, if we planned to use high school GPA as a covariate, we could start with a one-way ANOVA where intervention group was the independent variable and high school GPA was the dependent variable. If group membership did not significantly predict high school GPA, then that would be a good sign that the covariate was independent of the independent variable.  </p>
<p>There are exceptions to this assumption depending on why you are using ANCOVA, which we will get to. The next assumption, however, is important. </p>
<p> </p>
</section>
<section id="homogeneity-of-regression-slopes" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="homogeneity-of-regression-slopes">Homogeneity of Regression Slopes </h4>
<p>This assumption is also referred to as a lack of interaction between the effect of the covariate and group membership. It probably sounds similar to the first assumption, but they are actually different. When we use a covariate, we fit a regression line to the entire dataset, ignoring which group an individual belongs to. In our example, we assume that there is a common, constant relationship between high school GPA and first-semester college GPA. If it turns out that the relationship between the covariate and the dependent variable is different depending on group membership, then this overall regression line is inaccurate. </p>
</section>
</section>
<section id="another-use-of-ancova-adjusted-means" class="level3" data-number="13.5.3">
<h3 data-number="13.5.3" class="anchored" data-anchor-id="another-use-of-ancova-adjusted-means"><span class="header-section-number">13.5.3</span> Another Use of ANCOVA: Adjusted Means </h3>
<p>In an ideal scenario, all analyses would be based on randomized controlled trials (RCTs), allowing researchers to make causal claims and use covariates solely to increase statistical power. However, in the real world, education researchers often rely on non-experimental data or conduct correlational and observational studies.</p>
<p>Without random assignment, groups may differ on multiple factors, some of which are related to both the independent variable (IV) and the dependent variable (DV); these are known as confounding variables. One common approach to addressing these differences is to include confounding variables as covariates in an ANCOVA.</p>
<p>However, it is important to recognize the limitations of this method. Since it is impossible to identify, measure, and include all potential confounders, ANCOVA cannot fully substitute for ANOVA with random assignment. It can, however, help approximate the results of an experiment by statistically adjusting for known confounding variables.</p>
<p>When using ANCOVA in non-experimental research, it is crucial to avoid making causal claims, as you cannot definitively conclude that independent variable X causes dependent variable Y. Instead, the results should be interpreted as associational, acknowledging the potential influence of unmeasured confounders.</p>
<p>  So, what would be an example of this kind of research question? Imagine we wanted to examine differences in GPA by gender, but prior research suggests that motivation levels also differ between male and female students. Since motivation could influence GPA, it serves as a potential confounding variable in our analysis.</p>
<p>To account for this, we could include motivation as a covariate in an ANCOVA, allowing us to examine the relationship between gender and GPA while controlling for differences in motivation.</p>
<p>We will explore this concept further using a hypothetical dataset with 12 cases to illustrate how ANCOVA adjusts for confounding variables.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-6.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 13.6</figcaption>
</figure>
</div>
<p>If we only looked at the simple mean difference in GPA by gender, we would overestimate the effect. Instead, we are interested in adjusted mean differences after controlling for the covariate of motivation.</p>
<p>To explore how ANCOVA can be used to find adjusted means and test the homogeneity of regression slopes, it is helpful to think of ANCOVA as a special type of multiple regression. It is considered “special” because our grouping variable (gender) is represented using dummy coding, a technique previously discussed.</p>
<p>Since we only have two levels (male and female), we need only one dummy variable, with males coded as 0 and females coded as 1. This allows us to include gender as a predictor in the regression model while ensuring that differences between groups are appropriately quantified.</p>
<p>  To build on this, we will first examine a simple regression model using gender as the independent variable and GPA as the dependent variable. Our focus will be on interpreting the regression coefficients (B), which are typically provided in statistical software output tables.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Predictor</th>
<th>B</th>
<th>SE</th>
<th>t</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>2.450</td>
<td>0.154</td>
<td>15.95</td>
<td>&lt;0.01</td>
</tr>
<tr class="even">
<td>Gender</td>
<td>0.550</td>
<td>0.217</td>
<td>2.53</td>
<td>0.03</td>
</tr>
</tbody>
</table>
<p>Therefore, our prediction equation is as follows: </p>
<p><span class="math display">\[
\hat{Y}_i = 2.45 + 0.55(x_i)
\]</span></p>
<p>If we want to know the mean GPA for each group, we just substitute the appropriate value for X and solve the equations.  </p>
<p>For male students, X = 0.</p>
<p><span class="math display">\[
Y - male = 2.45 + 0.55(0) = 2.45
\]</span></p>
<p>For female students, X = 1.</p>
<p><span class="math display">\[
Y - female = 2.45 + 0.55(1) = 3.00
\]</span></p>
<p>Now we have the <em>unadjusted</em> mean GPAs for each group. But remember, we have reason to believe that motivation is a confounding variable that is associated with both gender and GPA. We can test whether our covariate (motivation) is independent of our grouping variable (gender) with a simple two-independent samples t test (two-tailed, α = 0.05). We used a statistical software package to run the analysis and confirmed motivation scores are significantly different between male and female students, <span class="math inline">\(t(10) = -4.82\)</span>, <span class="math inline">\(p &lt; .05\)</span>. </p>
<p>If we had randomly assigned students to two groups and were only trying to reduce error variation, then motivation would not be a good covariate to use. However, in this case, we are using ANCOVA to estimate adjusted means rather than to reduce error variation. We know that motivation is associated with our independent variable, and we are using it as a covariate to try to control for the effect of motivation on GPA to get a more accurate estimate of the effect of gender on GPA.   </p>
<p>To examine the relationship between X and Y, controlling for C (our covariate), we use a multiple regression equation using both X and C to predict Y. This is the ANCOVA model (in regression form), which can be written as: <span class="math inline">\(\hat{Y}_I = a+ b_1X_i+ b_2C_i\)</span>.</p>
<p>The table below summarizes the regression coefficients.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Predictor</th>
<th>B</th>
<th>SE</th>
<th>t</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>1.547</td>
<td>0.771</td>
<td>2.006</td>
<td>0.076</td>
</tr>
<tr class="even">
<td>Gender</td>
<td>0.163</td>
<td>0.388</td>
<td>0.420</td>
<td>0.684</td>
</tr>
<tr class="odd">
<td>Motivation</td>
<td>0.097</td>
<td>0.081</td>
<td>1.194</td>
<td>0.263</td>
</tr>
</tbody>
</table>
<p>Therefore, our new prediction equation is as follows: </p>
<p><span class="math display">\[
\hat{Y}_I = 1.55+0.162(X_i)+0.097(C_i)
\]</span></p>
<p>This time, the output tables tell us that neither the overall model nor Gender on its own are significant predictors of GPA. The relationship between X and Y has changed after controlling for C. Controlling for the covariate means that if all students had the same motivation scores, what differences in GPA would we see based on gender? To find the adjusted mean GPA by group, we substitute the grand mean of C (11.33) in the equation along with substituting in the appropriate values of X.  </p>
<p>For male students, X = 0.</p>
<p><span class="math display">\[
\bar{Y}_{male} = 1.55 + 0.163(0) + 0.097(11.33) = 2.65
\]</span></p>
<p>For female students, X = 1.</p>
<p><span class="math display">\[
\bar{Y}_{female} = 1.55 + 0.163(1) + 0.097(11.33) = 2.81
\]</span></p>
<p>You can see that while female students still have higher adjusted mean GPAs than male students, the gap is narrower. This is consistent with the results of the regression analysis showing no significant difference in GPA by gender after controlling for motivation. We are no longer rejecting the null hypothesis, so it is possible there is actually no difference in the population. We will get back to the actual ANCOVA analysis soon, but first a little more about regression so we can investigate the issue of homogenous regression slopes.  </p>
</section>
<section id="homogeneity-of-regression-slopes-1" class="level3" data-number="13.5.4">
<h3 data-number="13.5.4" class="anchored" data-anchor-id="homogeneity-of-regression-slopes-1"><span class="header-section-number">13.5.4</span> Homogeneity of Regression Slopes </h3>
<p>The equations we just created were for adjusted mean values by group, and they used the grand mean for the covariate. It is possible to create separate prediction equations for each group that could include any value of the covariate. If we look back at the general prediction equation, we can substitute in appropriate values for X (either 0 or 1) to get these: </p>
<p> Male students:</p>
<p><span class="math display">\[
\hat{Y}_{male\,i} = 1.55+ 0.097(C_i)
\]</span></p>
<p>Female students:</p>
<p><span class="math display">\[
\hat{female\,i} = 1.71+ 0.097(C_i)  
\]</span></p>
<p>These two equations are different only in the value of the intercept; the slopes are the same. This means the regression lines for the covariate are parallel, but the slope for male students is shifted a little lower on the Y-axis. Figure 13.7 shows the regression lines, where the dotted line represents the equation for female students and the solid line represents the equation for male students.  </p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Figure 13.7</figcaption>
</figure>
</div>
</div>
</div>
<p>This is an example of how we can violate the first ANCOVA assumption but not the second, which is much more important. We deliberately chose a covariate that we knew was associated with our independent variable because we wanted to control for motivation to find adjusted mean GPA by gender. But even though motivation was associated with gender in this dataset, we are still assuming the effect of motivation on GPA is not different based on gender.</p>
<p>What would it look like if we violated this assumption? If there was an interaction between our covariate and our independent variable such that the effect of motivation on GPA varied by gender, then the actual regression lines might look more like those displayed in figure 13.8.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Figure 13.8</figcaption>
</figure>
</div>
</div>
</div>
<p>If higher levels of the covariate led to higher scores on the dependent variable for one group, but lower scores for another group, then this covariate would be meaningless. When this kind of interaction is present, we can’t make a general statement about the effect of the covariate nor about adjusted mean values by group.  </p>
</section>
<section id="testing-the-interaction" class="level3" data-number="13.5.5">
<h3 data-number="13.5.5" class="anchored" data-anchor-id="testing-the-interaction"><span class="header-section-number">13.5.5</span> Testing the Interaction </h3>
<p>To find out if there is an interaction between X (our grouping variable) and C (our covariate) and test the homogeneity of regression slopes, we need to add an interaction term to the regression equation and test it for significance. The interaction term is formed by multiplying the raw scores for the independent variable by the raw scores for the covariate: <span class="math inline">\(X_i \times C_i\)</span>.</p>
<p>This leads to the full model we use to test the interaction term:  </p>
<p><span class="math display">\[
\hat{Y}_I = a + b_1X_i + b_2C_i+ b_3(X_i∗C_i)
\]</span></p>
<p>There are a few things you need to keep in mind about that equation:</p>
<ol type="1">
<li><p>You can’t just test the interaction effect on its own. You need to include both the independent variable and the covariate in the model separately or else the interaction might show up as significant only due to the main effects of the two variables.  </p></li>
<li><p>We hope to find that the interaction is not significant. Our null hypothesis is that β3 = 0.  </p></li>
<li><p>If we do manage to retain the null, we need to re-run the model without the interaction effect, because the other coefficients will change once we remove it.  </p></li>
<li><p>If the interaction term is significant, then we need to keep it in the model. We will no longer have an ANCOVA model, instead we have a multiple regression model with an interaction.  </p></li>
</ol>
</section>
<section id="more-complex-ancovas" class="level3" data-number="13.5.6">
<h3 data-number="13.5.6" class="anchored" data-anchor-id="more-complex-ancovas"><span class="header-section-number">13.5.6</span> More Complex ANCOVAS</h3>
<p>The example we’ve been using is the simplest possible ANCOVA, with only one independent variable that has only two levels. If you are conducting a one-way ANCOVA with a factor that has more than two levels, a factorial ANCOVA with multiple factors, or an ANCOVA with multiple covariates, the fundamental principles remain the same. However, these more complex models require additional steps upfront to thoroughly test assumptions before proceeding with the analysis.</p>
</section>
<section id="grouping-variable-with-2-levels" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="grouping-variable-with-2-levels">Grouping Variable with &gt; 2 Levels</h3>
<p>Imagine if we wanted to use an independent variable with three levels rather than two, such as education level: high school graduates, some college experience, and college graduates. The main difference is that now we must make sure the effect of our covariate is the same across all three groups, which means testing <em>two</em> interaction terms.</p>
<p>Since there are three groups, we need two dummy variables. Let’s use high school graduates as the reference group, which means there is one dummy variable (<span class="math inline">\(X_1\)</span>) to represent “some college,” and a second dummy variable (<span class="math inline">\(X_2\)</span>) to represent “college graduate.” Each dummy variable is coded 0/1, so the following table shows how individuals in each group would be coded on the two variables:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Education Level</th>
<th><span class="math inline">\(X_1\)</span></th>
<th><span class="math inline">\(X_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HS Graduate</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Some College</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>College Graduate</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Our overall prediction model will be:<br>
<span class="math display">\[
\hat{Y}_I = a + b_1X_{1i} + b_2X_{2i}+ b_3C_i
\]</span></p>
<p>where <span class="math inline">\(b_1\)</span> represents the difference in Y between individuals with some college and high school graduates, and <span class="math inline">\(b_2\)</span> represents the difference in <span class="math inline">\(Y\)</span> between college graduates and high school graduates; <span class="math inline">\(a\)</span> indicates the adjusted mean of the high school graduate reference group.</p>
<p>To conduct the ANCOVA analysis, we have to check the homogeneity of regression slopes by testing interaction effects. If there are three categories in the IV and two dummy variables, we also have two interaction terms (i.e., each dummy variable × the covariate), and then test the full model with both interaction terms to see if either one was significant:</p>
<p><span class="math display">\[
\hat{Y}_I = a + b_1X_{1i} + b_2X_{2i}+ b_3C_i + (b_4X_{1i}*C_i) + (b_5X_{2i}*C_i)
\]</span></p>
<p>In this case, the hypotheses we’re testing are:</p>
<p><span class="math display">\[
H_0: \beta_4 = \beta_5 = 0
\]</span></p>
<p><span class="math display">\[
H_A: \text{At least one of the beta coefficients is not zero.}
\]</span></p>
<p>If both interaction terms are not significant, you can use the covariate. The only other difference from our earlier example is that if there are significant group differences, you will need to conduct post hoc tests to find out which groups are significantly different from each other.</p>
</section>
<section id="factorial-ancova" class="level3" data-number="13.5.7">
<h3 data-number="13.5.7" class="anchored" data-anchor-id="factorial-ancova"><span class="header-section-number">13.5.7</span> Factorial ANCOVA</h3>
<p>As your analysis becomes more complex, so does the work required to test assumptions. When conducting an ANCOVA with multiple factors or covariates, you need to address two key considerations:</p>
<ul>
<li><p><em>Correlation Between the Covariate and the Dependent Variable (DV)</em></p>
<p>The covariate must be correlated with the DV within each combination of groups of the independent variables. For example, in a 2×2 ANCOVA, you must check this correlation separately for all four groups (cells).</p></li>
<li><p><em>Testing for Interaction Effects</em></p>
<p>Here, the focus is on whether the covariate interacts with the treatment conditions, not the typical interaction between independent variables (IVs). Just as in cases where a factor has more than two levels, you need to test the interaction between the covariate and each dummy variable for every factor.</p></li>
</ul>
<p>Note that in a 2×2 ANCOVA, even though there are four groups, you only have one dummy variable, meaning there are only two interaction effects to check.</p>
</section>
<section id="multiple-covariates" class="level3" data-number="13.5.8">
<h3 data-number="13.5.8" class="anchored" data-anchor-id="multiple-covariates"><span class="header-section-number">13.5.8</span> Multiple Covariates</h3>
<p>If you include two covariates in your ANCOVA, you must perform all the same assumption tests as you would for a single covariate—but twice (once for each covariate). While adding covariates can help control for additional factors, it is important to be cautious about overfitting the model.</p>
<p>Every additional variable reduces your degrees of freedom, so including a weak covariate—one that does little to reduce error variation—can actually decrease the statistical power of your analysis rather than improve it.</p>
<p>As always, the selection of covariates should be guided by theory and prior research to ensure that they meaningfully contribute to the model rather than simply increasing complexity.</p>
</section>
</section>
<section id="summary" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="summary"><span class="header-section-number">13.6</span> Summary</h2>
<p>You are probably going to have to read this more than once before it all makes sense, so here is a quick summary to reorient yourself before you go back to the start.</p>
<ul>
<li><p>There are two main reasons you would use a covariate.</p>
<ul>
<li><p>If you’re using a classic experimental design with random assignment to groups, you would use ANCOVA to reduce error variance, and therefore have greater power to detect a significant difference.</p></li>
<li><p>If you are using non-experimental data, you might use ANCOVA to adjust group means by controlling for a confounding variable.</p></li>
<li><p>In either case, you are not interested in interpreting the results of the covariate; it’s only there to clarify the relationship between the IV and the DV.</p></li>
</ul></li>
<li><p>There are two new assumptions for ANCOVA.</p>
<ul>
<li><p>Independence of the covariate and the treatment effect: Ideally, your covariate is related to your DV but not to your IV. You test this assumption by using either an independent samples t test (if your IV has two groups) or a one-way ANOVA (if you have more than two groups), with the covariate as your dependent variable. If the result is not significant, you can proceed because your IV does not predict the covariate.</p></li>
<li><p>Homogeneity of regression slopes: We need the covariate to have the same effect on the DV for every level or group of your IV. We test this by computing a new variable to represent the interaction between the IV and the covariate. Then we run a multiple regression model with the IV, the covariate, and the interaction term as predictors of the DV. If the interaction term is not significant, we can proceed.</p></li>
</ul></li>
</ul>
<p>The concept of ANCOVA can sometimes be difficult to understand. If you want another explanation, this <a href="https://www.youtube.com/watch?v=0e8BI2u6DU0">YouTube video</a> by Foltz (2017) has been helpful to our students.</p>
</section>
</section>
<section id="analyzing-change-and-adjusting-for-covariates-in-r" class="level1 unnumbered">
<h1 class="unnumbered">Analyzing Change and Adjusting for Covariates in R</h1>
<p>In this section, we demonstrate how to implement two of the central methods from this Chapter in R: <strong>Repeated-Measures ANOVA</strong> and <strong>Analysis of Covariance (ANCOVA)</strong>. Both approaches help educational researchers make more nuanced conclusions: the first by analyzing within-subject change across multiple measures, the second by adjusting for covariates to clarify between-group differences.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">"chapter13/chapter13data.sav"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="repeated-measures-anova" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="repeated-measures-anova">1 Repeated-Measures ANOVA</h2>
<p>We will examine U.S. students’ math performance across three content areas from PISA:</p>
<ul>
<li><p>PV1MPRE: Reasoning</p></li>
<li><p>PV1MCQN: Quantity</p></li>
<li><p>PV1MCSS: Space &amp; Shape</p></li>
</ul>
<p>These serve as within-subject factors (each student is measured in all three domains). For a between-subjects factor, we will include MATHMOT - Motivation to Do Well in Mathematics, a binary categorical variable. A value of 1 indicates that the student reported being more motivated to do well in mathematics than in other subjects, and 0 indicates they are not.</p>
<section id="preparing-the-data" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="preparing-the-data">1.1 Preparing the data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ez) </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Select variables </span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>rm_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">ID =</span> CNTSTUID, PV1MPRE, PV1MCQN, PV1MCSS, MATHMOT) <span class="co">#CNTSTUID - Student ID </span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape to long format for ezANOVA </span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>rm_long <span class="ot">&lt;-</span> rm_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(PV1MPRE, PV1MCQN, PV1MCSS), </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"ContentArea"</span>, </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"Score"</span>) </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rm_long <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID MATHMOT ContentArea   Score
1 84000041       1     PV1MPRE 557.718
2 84000041       1     PV1MCQN 582.587
3 84000041       1     PV1MCSS 586.034
4 84000231       0     PV1MPRE 476.778
5 84000231       0     PV1MCQN 408.350
6 84000231       0     PV1MCSS 394.714</code></pre>
</div>
</div>
</section>
<section id="running-the-repeated-measures-anova" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="running-the-repeated-measures-anova">1.2 Running the repeated-measures ANOVA</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeated measures ANOVA with MATHMOT as between-subjects factor </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>anova_res <span class="ot">&lt;-</span> <span class="fu">ezANOVA</span>( </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> rm_long, </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">dv =</span> Score,              <span class="co"># dependent variable </span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">wid =</span> ID,                <span class="co"># participant ID </span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">within =</span> .(ContentArea), <span class="co"># within-subject factor </span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">between =</span> .(MATHMOT),    <span class="co"># between-subject factor </span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="dv">3</span>,                <span class="co"># Type III SS, to address unbalanced design </span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">detailed =</span> <span class="cn">TRUE</span>          <span class="co"># returns extra information </span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the ANOVA table from ezANOVA </span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>anova_table <span class="ot">&lt;-</span> anova_res<span class="sc">$</span>ANOVA </span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute partial eta squared for each effect </span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>anova_table<span class="sc">$</span>eta_p2 <span class="ot">&lt;-</span> <span class="fu">with</span>(anova_table, SSn <span class="sc">/</span> (SSn <span class="sc">+</span> SSd)) </span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>anova_table_rounded <span class="ot">&lt;-</span> anova_table <span class="sc">|&gt;</span> </span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) </span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>anova_table_rounded </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Effect DFn  DFd          SSn       SSd         F     p p&lt;.05
1         (Intercept)   1 4008 2.471806e+09 102205168 96932.474 0.000     *
2             MATHMOT   1 4008 1.060816e+05 102205168     4.160 0.041     *
3         ContentArea   2 8016 3.553135e+05  11491923   123.922 0.000     *
4 MATHMOT:ContentArea   2 8016 5.014659e+03  11491923     1.749 0.174      
    ges eta_p2
1 0.956  0.960
2 0.001  0.001
3 0.003  0.030
4 0.000  0.000</code></pre>
</div>
</div>
<section id="between-subjects-factor-mathmot" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="between-subjects-factor-mathmot">1.2.1 Between-Subjects Factor: MATHMOT</h4>
<ul>
<li><p>Students with higher motivation in mathematics (MATHMOT) had significantly different scores across the math content areas overall, <span class="math inline">\(F(1, 4008) = 4.16, \, p = .041\)</span>.</p></li>
<li><p>The partial <span class="math inline">\(\eta^2\)</span> (eta_p2) is .001, indicating that although the effect is statistically significant, the effect size is extremely small (about 0.1% of the variance explained). This reveals that large samples can make very small effects look statistically significant.</p></li>
</ul>
</section>
<section id="within-subjects-factor-contentarea" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="within-subjects-factor-contentarea">1.2.2 Within-Subjects Factor: ContentArea</h4>
<ul>
<li><p>There is a significant effect of Content Area on math scores, <span class="math inline">\(F(2, 8016) = 123.92\)</span>, <span class="math inline">\(p &lt; .001\)</span>, indicating that students’ performance varies across the three content areas.</p></li>
<li><p>The partial <span class="math inline">\(\eta^2\)</span> is .030, suggesting that about 3% of the variance in scores can be attributed to differences between content areas. This is a larger but still modest effect size.</p></li>
</ul>
</section>
<section id="interaction-mathmot-contentarea" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="interaction-mathmot-contentarea">1.2.3 Interaction: MATHMOT × ContentArea</h4>
<p>The interaction between MATHMOT and Content Area is not significant, <span class="math inline">\(F(2, 8016) = 1.75, \, p= .174\)</span>. This means that although motivated students scored differently overall, their relative performance patterns across the three content areas were not significantly different from less motivated peers. In other words, motivation shifts the overall level but not the shape of the profile.</p>
</section>
<section id="assumption-check-sphericity" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-check-sphericity">1.2.4 Assumption Check: Sphericity</h4>
<ul>
<li><p>Mauchly’s Test (<span class="math inline">\(W  = 0.983, \, p &lt; .001\)</span>) is significant. This suggests the assumption of sphericity is formally violated: the variances of the differences between content areas are not perfectly equal. However, with such a large sample (<span class="math inline">\(N &gt; 4000\)</span>), Mauchly’s test is extremely sensitive — even tiny deviations from sphericity can become statistically significant.</p></li>
<li><p>As the chapter explained, we apply corrections. For the effect of content areas: Greenhouse-Geisser (p[GG]) <span class="math inline">\(p &lt; .001\)</span>; Huynh-Feldt (p[HF]) <span class="math inline">\(p &lt; .001\)</span>. Both lead to the same conclusion: the ContentArea effect is robustly significant, even after adjustment.</p></li>
</ul>
</section>
</section>
<section id="post-hoc-comparisons-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="post-hoc-comparisons-1">1.3 Post Hoc Comparisons</h3>
<section id="visualize-the-means" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="visualize-the-means">1.3.1 Visualize the Means</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean plot by ContentArea </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>means_plot <span class="ot">&lt;-</span> rm_long <span class="sc">%&gt;%</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ContentArea) <span class="sc">%&gt;%</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_score =</span> <span class="fu">mean</span>(Score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">se =</span> <span class="fu">sd</span>(Score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">n</span>())) </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>means_plot </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  ContentArea mean_score    se
  &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt;
1 PV1MCQN           458.  1.51
2 PV1MCSS           450.  1.36
3 PV1MPRE           461.  1.41</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean plot (line plot) with error bars </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(means_plot, <span class="fu">aes</span>(<span class="at">x =</span> ContentArea, <span class="at">y =</span> mean_score, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"skyblue"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_score <span class="sc">-</span> se, <span class="at">ymax =</span> mean_score <span class="sc">+</span> se), </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">445</span>, <span class="dv">465</span>)) <span class="sc">+</span>   <span class="co"># adjust y-axis range </span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"PV1MPRE"</span> <span class="ot">=</span> <span class="st">"Reasoning"</span>, </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"PV1MCQN"</span> <span class="ot">=</span> <span class="st">"Quantity"</span>, </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"PV1MCSS"</span> <span class="ot">=</span> <span class="st">"Space &amp; Shape"</span>)) <span class="sc">+</span> </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Mean Math Score"</span>) <span class="sc">+</span> </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Content Area"</span>) <span class="sc">+</span> </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Mean Math Scores Across Content Areas"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter13_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="pairwise-comparisons-repeated-measures-t-tests" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="pairwise-comparisons-repeated-measures-t-tests">1.3.2 Pairwise Comparisons (Repeated-Measures t-tests)</h4>
<p>We use pairwise.t.test() with Bonferroni correction. Since the data are within-subjects, we need to specify paired = TRUE.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise repeated-measures t-tests </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>pairwise_results <span class="ot">&lt;-</span> <span class="fu">pairwise.t.test</span>(rm_long<span class="sc">$</span>Score,  </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                                    rm_long<span class="sc">$</span>ContentArea, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">paired =</span> <span class="cn">TRUE</span>, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>) </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>pairwise_results </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using paired t tests 

data:  rm_long$Score and rm_long$ContentArea 

        PV1MCQN PV1MCSS
PV1MCSS &lt;2e-16  -      
PV1MPRE 0.0032  &lt;2e-16 

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>From the line plot, students scored lowest in Space &amp; Shape (450), higher in Quantity (458), and highest in Reasoning (461). The pairwise t-tests confirm that all three pairwise differences are statistically significant after Bonferroni correction (<span class="math inline">\(p &lt; .001\)</span> for all comparisons), although the largest gap is between Space &amp; Shape and the other two areas.</p>
</section>
</section>
</section>
<section id="ancova" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ancova">2 ANCOVA</h2>
<p>Now we turn to ANCOVA， where the focus is where the focus is comparing the three types of schools on math performance, while controlling for growth mindset:</p>
<ul>
<li><p><strong>DV</strong>: PV1MATH (overall math achievement)</p></li>
<li><p><strong>IV</strong>: SC014Q01TA (School type: 1 - religious, 2 - non-profit, 4 - government)</p></li>
<li><p><strong>Covariate</strong>: GROSAGR (Growth Mindset)</p></li>
</ul>
<section id="running-ancova" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="running-ancova">2.1 Running ANCOVA</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert School Type to factor </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>SchoolType <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>SC014Q01TA, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>), </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Religious"</span>, <span class="st">"Non-profit"</span>, <span class="st">"Government"</span>)) </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>SchoolType <span class="sc">|&gt;</span> <span class="fu">table</span>() <span class="co"># check distribution </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Religious Non-profit Government 
        97        181       4013 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ANCOVA model </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ancova_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(PV1MATH <span class="sc">~</span> SchoolType <span class="sc">+</span> GROSAGR, <span class="at">data =</span> data) </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ancova_model) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df   Sum Sq Mean Sq F value Pr(&gt;F)    
SchoolType     2   712007  356003   41.68 &lt;2e-16 ***
GROSAGR        1  1611370 1611370  188.65 &lt;2e-16 ***
Residuals   3816 32594220    8541                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
732 observations deleted due to missingness</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Post-hoc Comparisons of adjusted means for School Type </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(ancova_model, pairwise <span class="sc">~</span> SchoolType) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 SchoolType emmean    SE   df lower.CL upper.CL
 Religious     473 10.10 3816      453      493
 Non-profit    405  7.20 3816      391      419
 Government    469  1.55 3816      466      472

Confidence level used: 0.95 

$contrasts
 contrast                  estimate    SE   df t.ratio p.value
 Religious - (Non-profit)     68.20 12.40 3816   5.484 &lt;0.0001
 Religious - Government        3.82 10.30 3816   0.372  0.9265
 (Non-profit) - Government   -64.38  7.36 3816  -8.745 &lt;0.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section>
<section id="school-type-effect" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="school-type-effect">2.1.1 School Type Effect</h3>
<ul>
<li><p>After controlling for growth mindset, there are still significant differences in math scores between school types, <span class="math inline">\(F(2,3816)=41.68, \, p&lt;.001\)</span>. This means that even if students had the same level of growth mindset, school type is still associated with different mean math achievement.</p></li>
<li><p>From the post-hoc comparison, after controlling for growth mindset (i.e., adjusted means):</p>
<ul>
<li><p>Religious schools (<span class="math inline">\(M = 473\)</span>) scored significantly higher than Non-profit schools (<span class="math inline">\(M = 405\)</span>), <span class="math inline">\(p &lt; .001\)</span>.</p></li>
<li><p>Government schools (<span class="math inline">\(M = 469\)</span>) also scored significantly higher than Non-profit schools, <span class="math inline">\(p &lt; .001\)</span>.</p></li>
<li><p>There was no significant difference between Religious and Government schools (mean difference <span class="math inline">\(= 3.82, p = .93\)</span>).</p></li>
</ul></li>
</ul>
<p>Check the One-Way ANOVA results from Chapter 10 to see how these comparisons differ before controlling for growth mindset.</p>
<section id="growth-mindset-effect-covariate" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="growth-mindset-effect-covariate">2.1.2 Growth Mindset Effect (Covariate)</h4>
<p>Growth mindset has a significant effect on math achievement, <span class="math inline">\(F(1,3816) = 188.65, \, p &lt; .001\)</span>.</p>
</section>
</section>
<section id="checking-assumptions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="checking-assumptions">2.2 Checking assumptions</h3>
<section id="independence-of-covariate-and-iv" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="independence-of-covariate-and-iv">2.2.1 Independence of covariate and IV</h4>
<p>Recall that one key assumption of ANCOVA is that the covariate (growth mindset) is associated with the dependent variable (math achievement) but not the independent variable (school type). We have shown that growth had a significant effect on math achievement. Now we check whether growth mindset differs by school type.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Does SchoolType predict Growth Mindset? </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>anova_cov <span class="ot">&lt;-</span> <span class="fu">aov</span>(GROSAGR <span class="sc">~</span> SchoolType, <span class="at">data=</span>data) </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_cov) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)
SchoolType     2    2.1  1.0424   1.597  0.203
Residuals   3817 2492.0  0.6529               
732 observations deleted due to missingness</code></pre>
</div>
</div>
<p>The ANOVA showed that growth mindset scores did not significantly differ across school types, <span class="math inline">\(F(2,3817) = 1.60, \, p = .203\)</span>. This indicates that the covariate (growth mindset) is independent of the independent variable (school type), upholding the assumption for ANCOVA.</p>
</section>
<section id="homogeneity-of-regression-slopes-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="homogeneity-of-regression-slopes-2">2.2.2 Homogeneity of regression slopes</h4>
<p>Another assumption of ANCOVA is no interaction between the effect of the covariate and group membership. We test this by adding an interaction term between school type and growth mindset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add interaction term </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(PV1MATH <span class="sc">~</span> SchoolType <span class="sc">*</span> GROSAGR, <span class="at">data=</span>data) </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">#note. including the interaction term automatically includes the main effects </span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(interaction_model) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Df   Sum Sq Mean Sq F value Pr(&gt;F)    
SchoolType            2   712007  356003  41.694 &lt;2e-16 ***
GROSAGR               1  1611370 1611370 188.719 &lt;2e-16 ***
SchoolType:GROSAGR    2    28481   14240   1.668  0.189    
Residuals          3814 32565739    8538                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
732 observations deleted due to missingness</code></pre>
</div>
</div>
<p>The interaction between school type and growth mindset was not significant, <span class="math inline">\(F(2,3814) = 1.67, \, p = .189\)</span>, indicating that the effect of growth mindset on math achievement is consistent across school types. This upholds the homogeneity of regression slopes assumption for ANCOVA.</p>
</section>
</section>
</section>
</section>
<section id="analyzing-change-and-adjusting-for-covariates-in-spss" class="level1 unnumbered">
<h1 class="unnumbered">Analyzing Change and Adjusting for Covariates in SPSS</h1>
<p>In this section, we demonstrate how to implement two of the central methods from this Chapter in R: Repeated-Measures ANOVA and Analysis of Covariance (ANCOVA). Both approaches help educational researchers make more nuanced conclusions: the first by analyzing within-subject change across multiple measures, the second by adjusting for covariates to clarify between-group differences.</p>
<section id="repeated-measures-anova-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="repeated-measures-anova-1">1 Repeated-Measures ANOVA</h2>
<p>We will examine U.S. students’ math performance across three content areas from PISA: - PV1MPRE: Reasoning - PV1MCQN: Quantity - PV1MCSS: Space &amp; Shape</p>
<p>These serve as within-subject factors (each student is measured in all three domains). For a between-subjects factor, we will include MATHMOT - Motivation to Do Well in Mathematics, a binary categorical variable. A value of 1 indicates that the student reported being more motivated to do well in mathematics than in other subjects, and 0 indicates they are not.</p>
<section id="running-the-repeated-measures-anova-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="running-the-repeated-measures-anova-1">1.1 Running the repeated-measures ANOVA</h3>
<p>Step-by-step procedure in SPSS</p>
<ol type="1">
<li><p>Click Analyze → General Linear Model → Repeated Measures</p></li>
<li><p>In the Repeated Measures Define Factor(s) dialog:</p>
<p>In the box labeled Within-Subject Factor Name, type: ContentArea</p>
<p>For Number of Levels, enter: 3</p>
<p>Click Add, then click Define</p></li>
<li><p>Assign the three variables to the ContentArea levels:</p>
<p>In the next dialog (Repeated Measures: Define), move the following into the “Within-Subjects Variables” slots:</p>
<pre><code> PV1MATH_Q → Level 1 

 PV1MATH_S → Level 2 

 PV1MATH_C → Level 3 </code></pre></li>
<li><p>Add the between-subjects variable:</p>
<p>Move MATHMOT into the Between-Subjects Factor(s) box.</p></li>
<li><p>Click the “EM Means…” button (Estimated Marginal Means):</p>
<p>Move ContentArea into the Display Means For box</p>
<p>Check the option Compare main effects</p>
<p>Select Bonferroni for pairwise adjustment</p>
<p>Click Continue</p></li>
<li><p>Click on “Plots…”</p>
<p>Drag ContentArea to the Horizontal Axis box.</p>
<p>Drag MATHMOT to Separate Lines (if you want interaction plot).</p>
<p>Click Add</p>
<p>Select Line Chart as Chart Type</p>
<p>Under Error Bars, select Confidence Interval</p>
<p>Click Continue</p></li>
<li><p><em>(Optional but recommended)</em> Click on Options:</p>
<p>Check: Descriptive statistics/ Estimates of effect size/ Homogeneity tests</p>
<p>Click Continue</p></li>
</ol>
<p>Click OK to run the analysis.</p>
<p><strong><em>Note:</em></strong> The procedure may appear long and complicated, but Steps 1–4 are sufficient to run a basic repeated measures ANOVA and obtain the main and interaction effects. Step 5 is necessary if you wish to view estimated marginal means and conduct pairwise comparisons (e.g., Bonferroni adjustment). Step 6 generates line plots to help visualize interactions or group trends. Step 7 provides additional outputs such as descriptive statistics, effect size estimates, and assumption checks (e.g., Levene’s test).</p>
<section id="assumption-checking" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-checking">1.1.1 Assumption checking</h4>
<p>Before interpreting the results of a repeated-measures ANOVA, it is important to check key statistical assumptions. These assumptions not only ensure the validity of the test results and help control the Type I error rate, but they also determine which version of the results we should report. For example, if the assumption of sphericity is violated, we must use adjusted degrees of freedom rather than reporting the default F-test.</p>
<p><strong><em>Mauchly’s Test of Sphericity</em></strong>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-9.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 13.9</figcaption>
</figure>
</div>
<p>The test was significant, <span class="math inline">\(\chi^2(2) = 69.384, \, p &lt; .001\)</span>, indicating a violation of the sphericity assumption. The variances of the differences between content areas are not perfectly equal. However, with such a large sample ( <span class="math inline">\(N &gt; 4000\)</span>), Mauchly’s test is extremely sensitive — even tiny deviations from sphericity can become statistically significant.</p>
<p>As the chapter explained, we apply corrections. As the <span class="math inline">\(\epsilon\)</span> is above 0.75, the Huynh-Feldt correction is appropriate and will be used in the main analysis.</p>
<p><strong><em>Box’s Test of Equality of Covariance Matrices</em></strong>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-10.png" class="img-fluid figure-img" style="width:20.0%"></p>
<figcaption>Fig 13.10</figcaption>
</figure>
</div>
<p>Box’s <span class="math inline">\(M = 8.050\)</span>, <span class="math inline">\(p = .240\)</span>, suggesting that the assumption of equal covariance matrices across groups is not violated.</p>
</section>
<section id="between-subjects-factor-mathmot-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="between-subjects-factor-mathmot-1">1.1.2 Between-Subjects Factor: MATHMOT</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-11.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 13.11</figcaption>
</figure>
</div>
<ul>
<li>Students with higher motivation in mathematics (MATHMOT) had significantly different scores across the math content areas overall, <span class="math inline">\(F(1, 4008) = 4.16\)</span>, <span class="math inline">\(p = .041\)</span>.</li>
</ul>
<p>The partial <span class="math inline">\(\eta^2\)</span> is .001, indicating that although the effect is statistically significant, the effect size is extremely small (about 0.1% of the variance explained). This reveals that large samples can make very small effects look statistically significant.</p>
</section>
<section id="within-subjects-factor-contentarea-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="within-subjects-factor-contentarea-1">1.1.3 Within-Subjects Factor: ContentArea</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-12.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 13.12</figcaption>
</figure>
</div>
<ul>
<li><p>There is a significant effect of Content Area on math scores, <span class="math inline">\(F(1.968, 7886.516) = 7.884\)</span>, <span class="math inline">\(p  &lt; .001\)</span>, indicating that students’ performance varies across the three content areas.</p></li>
<li><p>The partial <span class="math inline">\(\eta^2\)</span> is .002, suggesting that about only 0.2% of the variance in scores can be attributed to differences between content areas.</p></li>
</ul>
</section>
<section id="interaction-mathmot-contentarea-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="interaction-mathmot-contentarea-1">1.1.4 Interaction: MATHMOT × ContentArea</h4>
<p>The interaction between MATHMOT and Content Area is not significant, <span class="math inline">\(F(1.968, 7886.516) = 1.749\)</span>, <span class="math inline">\(p = .175\)</span>. This means that although motivated students scored differently overall, their relative performance patterns across the three content areas were not significantly different from less motivated peers. In other words, motivation shifts the overall level but not the shape of the profile.</p>
</section>
</section>
<section id="post-hoc-comparisons-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="post-hoc-comparisons-2">1.2 Post Hoc Comparisons</h3>
<section id="visualize-the-means-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="visualize-the-means-1">1.2.1 Visualize the Means</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-13.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 13.13</figcaption>
</figure>
</div>
<p>This plot shows the average math scores across the three content areas: Reasoning (1), Quantity (2), and Space &amp; Shape (3). Students scored highest in Reasoning, slightly lower in Quantity, and lowest in Space &amp; Shape. While these trends are observable, they should be interpreted cautiously - formal statistical tests are necessary to confirm whether these differences are statistically significant. In this case, the main effect of content area was significant, further confirming the differences suggested by the plot.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-14.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 13.14</figcaption>
</figure>
</div>
<p>This plot shows the estimated marginal means for each content area, split by students’ motivation to do well in math. Students who reported being more motivated tended to score higher across all three content areas.</p>
<p>The overall performance pattern (Reasoning &gt; Quantity &gt; Space &amp; Shape) appears similar for both groups, suggesting that the relative differences across content areas are not strongly influenced by motivation. This visual pattern aligns with the non-significant interaction observed in the formal tests, offering further support for that finding.</p>
</section>
<section id="pairwise-comparisons" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="pairwise-comparisons">1.2.2 Pairwise Comparisons</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-15.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 13.15</figcaption>
</figure>
</div>
<p>Bonferroni-adjusted pairwise comparisons showed that students scored significantly higher in Reasoning than in Space &amp; Shape (<span class="math inline">\(p &lt; .001\)</span>) and significantly higher in Quantity than in Space &amp; Shape (<span class="math inline">\(p = .010\)</span>). However, the difference between Reasoning and Quantity was not statistically significant (<span class="math inline">\(p = .930\)</span>). These comparisons suggest that the lowest performance was in the Space &amp; Shape subscale, while performance in Reasoning and Quantity was relatively similar.</p>
<p>Note that these comparisons are based on estimated marginal means, which adjust for the between-subjects factor (math motivation) and use a pooled error term, making them slightly more conservative than raw paired t-tests.</p>
</section>
</section>
</section>
<section id="ancova-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ancova-1">2 ANCOVA</h2>
<p>Now we turn to ANCOVA, where the focus is where the focus is comparing the three types of schools on math performance, while controlling for growth mindset:</p>
<pre><code>**DV**: PV1MATH (overall math achievement) 

**IV**: SC014Q01TA (School type: 1 - religious, 2 - non-profit, 4 - government) 

**Covariate**: GROSAGR (Growth Mindset) </code></pre>
</section>
<section id="running-ancova-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="running-ancova-1">2.1 Running ANCOVA</h2>
<p>Step-by-step procedure in SPSS</p>
<ol type="1">
<li><p>Click Analyze → General Linear Model → Univariate</p></li>
<li><p>In the Univariate dialog:</p>
<p>Move PV1MATH to the Dependent Variable box.</p>
<p>Move SC014Q01TA (school type) to the Fixed Factor(s) box.</p>
<p>Move GROSAGR (growth mindset) to the Covariate(s) box.</p></li>
<li><p>Click the “Post Hoc…” button (optional but recommended):</p>
<p>Select SC014Q01TA</p>
<p>Choose Bonferroni or Tukey for pairwise comparisons</p>
<p>Click Continue</p></li>
<li><p>(Optional) Click the “EM Means…” button (Estimated Marginal Means):</p>
<p>Move SC014Q01TA into the Display Means For box</p>
<p>Check the option Compare main effects</p>
<p>Select Bonferroni for pairwise adjustment</p>
<p>Click Continue</p></li>
<li><p>(Optional) Click on “Plots…”:</p>
<p>Drag SC014Q01TA to the Horizontal Axis box</p>
<p>Click Add</p>
<p>Select Line Chart as Chart Type</p>
<p>Under Error Bars, select Confidence Interval</p>
<p>Click Continue</p></li>
<li><p>(Optional) Click on “Options…”:</p>
<p>Check: Descriptive statistics/ Estimates of effect size/ Homogeneity tests</p>
<p>Click Continue</p></li>
</ol>
<p>Click OK to run the analysis.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-16.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 13.16</figcaption>
</figure>
</div>
<section id="school-type-effect-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="school-type-effect-1">2.1.1 School Type Effect</h4>
<p>After controlling for growth mindset, there are still significant differences in math scores between school types, <span class="math inline">\(F(2,3816)=38.45\)</span>, <span class="math inline">\(p&lt;.001\)</span>. This means that even if students had the same level of growth mindset, school type is still associated with different mean math achievement.</p>
</section>
<section id="growth-mindset-effect-covariate-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="growth-mindset-effect-covariate-1">2.1.2 Growth Mindset Effect (Covariate)</h4>
<p>Growth mindset has a significant effect on math achievement, <span class="math inline">\(F(1,3816)=188.65\)</span>, <span class="math inline">\(p&lt;.001\)</span>.</p>
</section>
<section id="pairwise-comparisons-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="pairwise-comparisons-1">2.1.3 Pairwise Comparisons</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-17.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 13.17</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-18.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 13.18</figcaption>
</figure>
</div>
<ul>
<li><p>From the post-hoc comparison, after controlling for growth mindset (i.e., adjusted means):</p>
<ul>
<li><p>Religious schools (<span class="math inline">\(M = 472.971\)</span>) scored significantly higher than Non-profit schools (<span class="math inline">\(M = 404.772\)</span>), <span class="math inline">\(p &lt; .001\)</span>.</p></li>
<li><p>Government schools (<span class="math inline">\(M = 469.151\)</span>) also scored significantly higher than Non-profit schools, <span class="math inline">\(p &lt; .001\)</span>.</p></li>
<li><p>There was no significant difference between Religious and Government schools (mean difference <span class="math inline">\(= 3.82\)</span>, <span class="math inline">\(p = .93\)</span>).</p></li>
</ul></li>
</ul>
<p>Check the One-Way ANOVA results from Chapter 10 to see how these comparisons differ before controlling for growth mindset.</p>
</section>
<section id="checking-assumptions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="checking-assumptions-1">2.2 Checking assumptions</h3>
<section id="independence-of-covariate-and-iv-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="independence-of-covariate-and-iv-1">2.2.1 Independence of covariate and IV</h4>
<p>Recall that one key assumption of ANCOVA is that the covariate (growth mindset) is associated with the dependent variable (math achievement) but not the independent variable (school type). We have shown that growth had a significant effect on math achievement. Now we check whether growth mindset differs by school type.A table with numbers and letters</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-19.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 13.19</figcaption>
</figure>
</div>
<p>The ANOVA showed that growth mindset scores did not significantly differ across school types, <span class="math inline">\(F(2,3817)=1.597\)</span>, <span class="math inline">\(p=.203\)</span>. This indicates that the covariate (growth mindset) is independent of the independent variable (school type), upholding the assumption for ANCOVA.</p>
</section>
<section id="homogeneity-of-regression-slopes-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="homogeneity-of-regression-slopes-3">2.2.2 Homogeneity of regression slopes</h4>
<p>Another assumption of ANCOVA is no interaction between the effect of the covariate and group membership. We test this by adding an interaction term between school type and growth mindset.</p>
<p><strong><em>Additional Step in SPSS</em></strong></p>
<p>All steps are the same as in the standard ANCOVA procedure described above. The only change is in the Model… dialog:</p>
<ul>
<li><p>After Step 2 (defining the DV, IV, and covariate), click Model…</p></li>
<li><p>Change the setting from Full factorial to Custom</p></li>
<li><p>Add the main effects:</p>
<ul>
<li><p>Select SC014Q01TA → Click Main effects → Click Add</p></li>
<li><p>Select GROSAGR → Click Main effects → Click Add</p></li>
</ul></li>
<li><p>Add the interaction term:</p>
<ul>
<li><p>Ctrl+Click to select both SC014Q01TA and GROSAGR</p></li>
<li><p>Click Interaction → Click Add</p></li>
</ul></li>
</ul>
<p>Click Continue and proceed to run the model as usual</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter13/fig13-20.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Fig 13.20</figcaption>
</figure>
</div>
<p>The interaction between school type and growth mindset was not significant, <span class="math inline">\(F(2 ,3814)=1.668\)</span>, <span class="math inline">\(p=.189\)</span>, indicating that the effect of growth mindset on math achievement is consistent across school types. This upholds the homogeneity of regression slopes assumption for ANCOVA.</p>
</section>
</section>
</section>
</section>
<section id="conclusion" class="level1 unnumbered">
<h1 class="unnumbered">Conclusion</h1>
<p>This chapter explored the foundational concepts and practical applications of repeated-measures ANOVA, a powerful statistical tool for analyzing differences across multiple conditions or time points within the same group of participants. By leveraging the repeated-measures design, researchers can control for individual differences, thereby reducing error variance and increasing statistical power compared to between-subjects designs. Central to the analysis is the ability to partition variance into components attributable to between-groups effects, within-groups error, and between-persons differences, which allows for a more nuanced understanding of the data. Additionally, the chapter highlighted the importance of understanding longitudinal versus cross-sectional designs and emphasized that repeated-measures ANOVA is uniquely suited to studies involving repeated observations on the same individuals over time or under different conditions.</p>
<p>A critical element of this analysis is ensuring that the assumption of sphericity is met or properly addressed. Violations of sphericity, which occur when variances of the differences between all combinations of related groups are unequal, can inflate Type I error rates, leading to invalid conclusions. To address this, researchers are equipped with tools such as Mauchly’s Test of Sphericity and corrections like the Greenhouse-Geisser and Huynh-Feldt adjustments. By understanding these concepts and incorporating them into their analyses, researchers can confidently interpret the results of repeated-measures ANOVA, making it an invaluable method for studies that track changes over time or across experimental conditions. Through statistical software and adherence to methodological rigor, this chapter equips readers with the knowledge to effectively utilize this robust analytical approach.</p>
<p>In addition to repeated-measures ANOVA, this chapter highlighted the role of <em>Analysis of Covariance (ANCOVA)</em>as a valuable statistical tool for controlling confounding variables when analyzing group differences. Unlike standard ANOVA, ANCOVA incorporates covariates—continuous variables that help reduce error variance—allowing for a more precise evaluation of treatment effects. This is particularly useful in educational research, where factors like prior achievement, motivation, or socioeconomic status may influence outcomes. By statistically adjusting for these pre-existing differences, ANCOVA enhances the validity of comparisons, especially in quasi-experimental designs where randomization is not feasible. However, researchers must ensure that covariates meet key assumptions, such as independence from the treatment effect and homogeneity of regression slopes, to avoid misleading conclusions. When used appropriately, ANCOVA strengthens the ability to draw meaningful inferences, making it an essential complement to repeated-measures ANOVA in educational research.</p>
<section id="key-takeaways-for-educational-researchers-from-chapter-13" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="key-takeaways-for-educational-researchers-from-chapter-13">Key Takeaways for Educational Researchers from Chapter 13</h2>
<ul>
<li><p>The use of repeated-measures design in educational research is crucial for examining changes in learning outcomes. Repeated-measures ANOVA is particularly useful in education research because it allows for the study of changes in learning outcomes, student engagement, or skill development over time. For example, a researcher could track the effects of different instructional strategies on student performance across multiple testing periods. By using the same participants in each condition, this design controls for individual differences, making it a powerful tool for assessing interventions and longitudinal trends in educational settings.</p></li>
<li><p>Controlling for individual differences enhances statistical power. A key advantage of repeated-measures ANOVA is its ability to remove variability due to individual differences, leading to increased statistical power. In educational research, where student performance can vary due to prior knowledge, motivation, or learning styles, this method helps isolate the actual effect of a key independent variable from these potential confounding effects. For instance, in a study comparing different teaching techniques, repeated-measures ANOVA ensures that each student’s unique characteristics do not confound the results, allowing for a clearer interpretation of instructional effectiveness.</p></li>
<li><p>When analyzing repeated measures data, ensuring that the assumption of sphericity is met is critical. A violation of sphericity occurs when the variances of the differences between time points or conditions are unequal, which can lead to inflated Type I error rates. Researchers must check for this assumption using Mauchly’s test for sphericity and apply corrections such as Greenhouse-Geisser or Huynh-Feldt adjustments if necessary. For example, if a study is evaluating student progress across multiple semesters, a potential violation of the sphericity assumption may arise when students’ score variances increase over the years (e.g., early semester scores are relatively stable, but later semesters show more fluctuation) or when the variance of score differences between Semester 1 and Semester 2 is significantly smaller than that between Semester 3 and Semester 4.</p></li>
<li><p>ANCOVA enhances comparisons by controlling for covariates. When studying the impact of an intervention, ANCOVA adjusts for pre-existing differences (e.g., prior knowledge, socioeconomic status, or motivation levels) to isolate the true effect of the intervention. This is essential in quasi-experimental designs commonly used in educational research where randomization isn’t feasible.</p></li>
<li><p>Educational researchers should use ANCOVA thoughtfully in non-experimental studies. When analyzing observational or survey data, ANCOVA can help control for confounding variables like student motivation or prior achievement. However, researchers must avoid making causal claims unless random assignment was used—otherwise, differences may reflect pre-existing group characteristics rather than true treatment effects.</p></li>
</ul>
</section>
<section id="key-definitions-from-chapter-13" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="key-definitions-from-chapter-13">Key Definitions from Chapter 13</h2>
<p><strong>Analysis of Covariance (ANCOVA)</strong> is a statistical technique used to evaluate whether there are significant differences between groups on a dependent variable while statistically controlling for the effects of one or more continuous variables (called covariates).</p>
<p>A <strong>covariate</strong> is a continuous variable that is included in the analysis to account for variability in the dependent variable that is not directly related to the independent variable(s). By controlling for the covariate, ANCOVA provides a clearer understanding of the relationship between the independent variable(s) and the dependent variable.</p>
<p>A <strong>repeated-measures ANOVA</strong> is used to determine whether there are significant differences between three or more related groups or measurements taken from the same participants under different conditions, at different time points, or across repeated trials.</p>
<p><strong>Sphericity</strong> refers to the condition where the variances of the differences between all combinations of related groups (levels of the independent variable) are equal.</p>
</section>
<section id="check-your-understanding" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="check-your-understanding">Check Your Understanding</h2>
<ol type="1">
<li><p><strong>What is the key advantage of using a repeated-measures ANOVA?</strong></p>
<ol type="a">
<li><p>It eliminates the need for a dependent variable.</p></li>
<li><p>It reduces error variance by accounting for individual differences.</p></li>
<li><p>It allows for the inclusion of multiple dependent variables.</p></li>
<li><p>It does not require any statistical assumptions.</p></li>
</ol></li>
<li><p><strong>What does the term “sphericity” refer to in the context of repeated-measures ANOVA?</strong></p>
<ol type="a">
<li><p>Equal variances within each group.</p></li>
<li><p>Equal sample sizes across groups.</p></li>
<li><p>Equal variances of differences between all combinations of related groups.</p></li>
<li><p>Equal means across all groups.</p></li>
</ol></li>
<li><p><strong>What is the recommended post hoc procedure for a repeated-measures ANOVA to control for Type I error?</strong></p>
<ol type="a">
<li><p>Tukey’s HSD</p></li>
<li><p>Bonferroni correction</p></li>
<li><p>Fisher’s LSD</p></li>
<li><p>Scheffé test</p></li>
</ol></li>
<li><p><strong>What does a significant result in a repeated-measures ANOVA indicate?</strong></p>
<ol type="a">
<li><p>All group means are equal.</p></li>
<li><p>The dependent variable is unrelated to the conditions tested.</p></li>
<li><p>The assumptions of sphericity have been violated.</p></li>
<li><p>There is a difference in at least one pair of group means.</p></li>
</ol></li>
<li><p><strong>What does “partial eta squared” (<span class="math inline">\(\eta^2_P\)</span>) represent in repeated-measures ANOVA?</strong></p>
<ol type="a">
<li><p>The total variation in the dependent variable.</p></li>
<li><p>The proportion of total variance explained by between-groups effects after accounting for between-persons variance.</p></li>
<li><p>The difference between the group means.</p></li>
<li><p>The degree of correlation between independent and dependent variables.</p></li>
</ol></li>
<li><p><strong>What is the role of a covariate in ANCOVA?</strong></p>
<ol type="a">
<li><p>To control for variability in the dependent variable that is unrelated to the independent variable(s)</p></li>
<li><p>To act as an additional independent variable</p></li>
<li><p>To replace the independent variable in the model</p></li>
<li><p>To reduce between-group variance</p></li>
</ol></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script src="assets/quiz.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter12.html" class="pagination-link" aria-label="Chapter 12">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 12</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter14.html" class="pagination-link" aria-label="Chapter 14">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 14</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>