<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Chapter 5 – Stats Textbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter6.html" rel="next">
<link href="./chapter4.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f2c6d6e2b784ddc5de38779acc06f37d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter5.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 5</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Stats Textbook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Chapter 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 4</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 5</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 6</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 7</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 8</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 9</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 10</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 11</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 12</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 13</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 14</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-normal-distribution" id="toc-the-normal-distribution" class="nav-link active" data-scroll-target="#the-normal-distribution">The Normal Distribution</a>
  <ul class="collapse">
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#what-is-a-normal-distribution" id="toc-what-is-a-normal-distribution" class="nav-link" data-scroll-target="#what-is-a-normal-distribution"><span class="header-section-number">5.1</span> What is a Normal Distribution?</a></li>
  <li><a href="#z-scores-and-the-standard-normal-distribution" id="toc-z-scores-and-the-standard-normal-distribution" class="nav-link" data-scroll-target="#z-scores-and-the-standard-normal-distribution"><span class="header-section-number">5.2</span> <span class="math inline">\(z\)</span> Scores and the Standard Normal Distribution</a>
  <ul class="collapse">
  <li><a href="#finding-areas-under-the-normal-curve" id="toc-finding-areas-under-the-normal-curve" class="nav-link" data-scroll-target="#finding-areas-under-the-normal-curve"><span class="header-section-number">5.2.1</span> Finding Areas Under the Normal Curve</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5.3</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#key-takeaways-for-educational-researchers-from-chapter-5" id="toc-key-takeaways-for-educational-researchers-from-chapter-5" class="nav-link" data-scroll-target="#key-takeaways-for-educational-researchers-from-chapter-5"><span class="header-section-number">5.3.1</span> Key Takeaways for Educational Researchers from Chapter 5 </a></li>
  </ul></li>
  <li><a href="#key-definitions-from-chapter-5" id="toc-key-definitions-from-chapter-5" class="nav-link" data-scroll-target="#key-definitions-from-chapter-5"><span class="header-section-number">5.4</span> Key Definitions from Chapter 5</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">5.5</span> Check Your Understanding</a></li>
  </ul></li>
  <li><a href="#chapter-5-exploring-the-normal-distribution-in-r" id="toc-chapter-5-exploring-the-normal-distribution-in-r" class="nav-link" data-scroll-target="#chapter-5-exploring-the-normal-distribution-in-r">Chapter 5: Exploring the Normal Distribution in R</a>
  <ul class="collapse">
  <li><a href="#visualizing-and-summarizing-the-distribution" id="toc-visualizing-and-summarizing-the-distribution" class="nav-link" data-scroll-target="#visualizing-and-summarizing-the-distribution">1 Visualizing and Summarizing the Distribution</a></li>
  <li><a href="#checking-for-normality" id="toc-checking-for-normality" class="nav-link" data-scroll-target="#checking-for-normality">2 Checking for Normality</a></li>
  <li><a href="#standardizing-scores-calculating-z-scores" id="toc-standardizing-scores-calculating-z-scores" class="nav-link" data-scroll-target="#standardizing-scores-calculating-z-scores">3 Standardizing Scores: Calculating Z-scores</a></li>
  <li><a href="#example-calculating-z-scores-and-probabilities-questions-1-3-.unnumbered" id="toc-example-calculating-z-scores-and-probabilities-questions-1-3-.unnumbered" class="nav-link" data-scroll-target="#example-calculating-z-scores-and-probabilities-questions-1-3-.unnumbered"><span class="header-section-number">5.6</span> 4 Example: Calculating Z-scores and Probabilities (Questions 1-3) {.unnumbered</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 5</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-normal-distribution" class="level1 unnumbered">
<h1 class="unnumbered">The Normal Distribution</h1>
<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li><p>Identify the defining characteristics of a normal distribution.</p></li>
<li><p>Compute z scores from raw data and interpret their meaning in terms of standard deviations from the mean.</p></li>
<li><p>Use the properties of a normal distribution to calculate probabilities and interpret results for real-world scenarios using z tables and statistical software or applets.</p></li>
</ul>
<p>The objectives for this chapter are to learn about the normal distribution, sometimes called the bell curve due to its shape, and to understand the concepts of probability associated with the normal distribution. An understanding of the normal distribution is very important because we use what we know about the normal distribution to make inferences about populations based on samples.</p>
</section>
<section id="what-is-a-normal-distribution" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="what-is-a-normal-distribution"><span class="header-section-number">5.1</span> What is a Normal Distribution?</h2>
<p>A <strong>normal distribution</strong>, or bell-shaped distribution, has the following characteristics:</p>
<ul>
<li><p>The shape is symmetric, unimodal, and bell-shaped.</p></li>
<li><p>The mean, median, and mode are the same—all are right in the center of the distribution.</p></li>
<li><p>Following the empirical rule, approximately 68% of the values in a normal distribution fall within 1 standard deviation of the mean, approximately 95% of the values fall within 2 standard deviations of the mean, and approximately 99.7% of the values fall within 3 standard deviations of the mean.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-empirical-rule-normal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-empirical-rule-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter5_files/figure-html/fig-empirical-rule-normal-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-empirical-rule-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Normal Distribution Showing the Empirical Rule
</figcaption>
</figure>
</div>
</div>
</div>
<p>For example, suppose a class took a science test and their scores were normally distributed. The distribution of student scores had a mean of 50 points (the center of the normal distribution) and a standard deviation of 15 points. Based on the empirical rule, you know that about 68% of the students scored between 35 (1 SD below the mean) and 65 (1 SD above the mean) points.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-empirical-rule-green" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-empirical-rule-green-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter5_files/figure-html/fig-empirical-rule-green-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-empirical-rule-green-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Normal Distribution with Empirical Rule
</figcaption>
</figure>
</div>
</div>
</div>
<p>It is important to understand the characteristics of the normal distribution not only because certain variables (e.g., weight, height, test scores) are likely to have normal distributions, but because many of the statistical techniques used to make inferences about populations rely on the properties of the normal distribution.</p>
<p>This rule is something you can use to interpret results from normally distributed data, but it is also part of what defines a normal distribution. Not all tests that students take are normally distributed. In those cases, the empirical rule would not apply.</p>
<p>Software programs like SPSS® and JASP can provide tests of normality that tell you how close your distribution is to the normal distribution. You can assess how closely your data approximate normality by examining two key statistics: skewness and kurtosis.</p>
<ul>
<li><p>As we learned in chapter 2, <strong>skewness</strong> means the extent to which a curve is pulled to one side or the other. Skewness is about symmetry, or really, the lack of symmetry. In a true normal distribution, half of the data points are above the mean, and half are below. A skewed distribution has more outliers on one side of the mean.</p></li>
<li><p>Kurtosis measures the <em>tailedness</em> of a distribution, or how heavy or light the tails are compared to a normal distribution. The strict definition can be confusing. For now, think about it in terms of how likely it is that there are outliers, or extreme values, in your data. A heavy-tailed distribution will have a higher kurtosis value, and a greater percentage of scores in the distribution will be out in the tails rather than the <em>shoulders</em>.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-kurtosis-compare-true" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kurtosis-compare-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter5_files/figure-html/fig-kurtosis-compare-true-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kurtosis-compare-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Distributions with K&gt;0, K=0, and K&lt;0 (true excess kurtosis), standardized to mean 0 and SD 1
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Positive Kurtosis</strong> (K &gt; 0): The blue plot represents a distribution with a narrow peak and thick tails.</p>
<p><strong>Zero Kurtosis</strong> (K = 0): The green plot represents a standard normal distribution with neither exaggerated tails nor an unusually sharp peak.</p>
<p><strong>Negative Kurtosis</strong> (K &lt; 0): The red plot represents a distribution with a flatter peak and thinner tails</p>
<p>A true normal distribution will have skewness and kurtosis values of 0. The closer the reported values are to 0, the more normal the distribution. A common rule of thumb is that a distribution with skewness and kurtosis values between -1 and 1 can be considered approximately normal.</p>
<p>(fig 5.4 here)</p>
<p>A normal distribution can have any mean and any standard deviation – it is about the shape of the distribution, not the specific numbers. For example, if you are looking at the heights of people, the mean and standard deviation will be quite different depending on whether your sample includes all people in the United States or all kindergarten students in one elementary school. Both height distributions will likely be normal and have the same basic shape, but the average height and variation in heights will probably both be lower if we are just looking at kindergartners.</p>
<p>(fig 5.5)</p>
</section>
<section id="z-scores-and-the-standard-normal-distribution" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="z-scores-and-the-standard-normal-distribution"><span class="header-section-number">5.2</span> <span class="math inline">\(z\)</span> Scores and the Standard Normal Distribution</h2>
<p>We often convert raw data values in a normal distribution to z scores, or standardized scores. A z score is a statistical measure that describes how far a particular data point is from the mean, center, of its distribution. Instead of describing the difference between one score and the mean in terms of points, or inches, or whatever unit was used for the original distribution, we are using standard deviation units. This allows for the comparison of scores from different distributions or scales. We do this because simply knowing the difference between one score and the overall mean doesn’t tell us much. For example, you learn you scored 5 points above the mean. Is your performance a lot better than average? Is your performance barely above average? The answer depends on the standard deviation. If the standard deviation of this distribution were 20, your score of 5 points above the mean would be considered close to average. However, if the standard deviation were only 2, your score would be considered outstanding.</p>
<p>Using the example above, if you scored 5 points above the mean and the standard deviation was 20, your z score would be 0.25. Your score would be a quarter of a standard deviation above the mean. However, if the standard deviation were 2, your z score would be 2.5. In this case, you would have scored 2.5 standard deviations above the mean. Remember this graph from chapter 3? Boxes have been added to illustrate our example to help visualize how far different z scores are from the mean.</p>
<p>(fig 5.6)</p>
<p>If we convert an entire distribution from raw scores to z scores, that means we are standardizing the dataset. The mean of the distribution then becomes 0, the standard deviation becomes 1, and we refer to the distribution as the <strong>standard normal distribution</strong>.</p>
<p>What we have discussed so far are likely the most important concepts for you to understand. The rest of this chapter will mostly involve finding areas under the normal curve by using z scores and the z table. You will also learn how you can get to the same answer using online applets.</p>
<section id="finding-areas-under-the-normal-curve" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="finding-areas-under-the-normal-curve"><span class="header-section-number">5.2.1</span> Finding Areas Under the Normal Curve</h3>
<p>Let’s say we have a continuous random variable: body temperature. Imagine that we have access to the body temperatures of a particular population (e.g., all residents of the United States), and when we graph this data, we see a normal distribution with a mean of 98.2 and a standard deviation of 0.73. Remember that we collected data from individuals who belong to a particular population (i.e., all Americans). So, these numbers (<span class="math inline">\(\mu\)</span> =  98.2 and <span class="math inline">\(\sigma\)</span> =  0.73 ) are not sample statistics, they are population parameters. Our normal distribution is illustrated in figure 5.7.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-mu-sd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-mu-sd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter5_files/figure-html/fig-normal-mu-sd-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-mu-sd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Normal Distribution with Mean and Standard Deviation
</figcaption>
</figure>
</div>
</div>
</div>
<p>We now have three questions we want to answer based on this distribution.</p>
<p><strong>Question #1: <em>What is the probability that a randomly sampled individual from this population has a body temperature of 98.6 degrees or higher?</em></strong></p>
<p>If we let X denote body temperature, we are basically asking what is <em>the probability that X is greater than or equal</em> to 98.6 degrees? We can equivalently express this as follows: <span class="math inline">\(P(X \ge 98.6) = \, ?\)</span> In shorthand, <span class="math inline">\(P\)</span> represents probability.</p>
<p>To answer the question, we first need to turn our random variable X into a z score. We then need to use this z score to find the area under the normal curve.</p>
<p>We convert X to a z score using the <em>z transformation formula</em>. The formula differs for a population of scores versus a sample of scores.</p>
<p><span class="math inline">\(\text{Population of scores: } z = \frac{x - \mu}{\sigma}\)</span></p>
<p><span class="math inline">\(\text{Sample of scores: } z = \frac{x - M}{SD}\)</span></p>
<p>Since we obtained information for the entire population of the United States: <span class="math inline">\(z = \frac{98.6 - 98.2}{.73} = .55\)</span></p>
<p>Our z-score is 0.55. So, we can re-express the above shorthand notation like this: <span class="math inline">\(P(X \ge 98.6) = P(z \ge 0.55) = ?\)</span></p>
<p>Therefore, the probability that we would obtain a temperature that is 98.6 degrees or higher is the same as the probability of obtaining a z score of 0.55 or higher. The probability is the area under the curve, to the right of a z score of 0.55, or to the right of the body temperature of 98.6. Figure 5.8 shows you this area—it is the area to the right of the red line.</p>
<p>(fig 5.8 here… need to figure out how to do the little thought cloud … :/ )</p>
<p>Now, let’s determine the probability of obtaining a body temperature of 98.6 or higher, which corresponds to a z score of 0.55 or above. Here, we want to introduce a <a href="https://homepage.divms.uiowa.edu/~mbognar/applets/normal.html">free applet</a> to help find the probability (Bognar, 2021). Enter the population mean, µ, of 98.2 and the standard deviation, <span class="math inline">\(\sigma\)</span>, of .73 to define the normal distribution as shown in Figure 5.9. You will see that the X-axis has been scaled using the specified mean and standard deviation. This is a good example of how the normal distribution can take on different values for μ and σ without changing shape.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter5/fig5-9.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 5.9: Aplet Demo 1</figcaption>
</figure>
</div>
<p>Next, enter the value of 98.6 in the box for x. Figure 5.10 shows the output.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter5/fig5-10.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 5.10: Aplet Demo 2</figcaption>
</figure>
</div>
<p>According to the applet, the probability of obtaining a temperature of 98.6, or a z score of 0.55, is roughly 0.29. Recall that probabilities range from 0 to 1, with the total area under the normal curve equaling 1 (or 100%). Thus, a probability of 0.29 indicates there is approximately a 29% chance of randomly selecting an individual from this population who has a body temperature of at least 98.6 degrees.</p>
<p>Although it is easy to use an applet to find our answer, let’s learn how to use the Standard Normal Cumulative Probability Table in the back of the book to find the answer. Remember that we are now expressing our question as follows: <span class="math inline">\(P(z \ge 0.55) = ?\)</span></p>
<p>We must go to Standard Normal Cumulative Probability Table in the back of the book and look up our z score of 0.55. The column on the far left indicates the first two values of the z score, so find 0.5. The top row indicates the next two values, so find 0.05. Follow the 0.05 column down to where it intersects the 0.5 column to find a value of .7088. This indicates the cumulative probability up to 0.55 standard deviations above the mean. Since we are interested in the area on the opposite side of 0.55 (a body temperature of at least 98.6), we subtract .7088 from 1 to get .2912 - roughly the same number given by the applet. This means that the probability of selecting an individual at random who has a body temperature of 98.6 degrees or greater is .2912, or 29.12%.</p>
<p><strong>Question #2: <em>What is the probability that a randomly sampled individual from this population has a body temperature of 97.5 degrees or lower?</em></strong></p>
<p>Hopefully, this question will now be easy to answer. In shorthand notation, we are asking: <span class="math inline">\(P(X &lt; 97.5) = ?\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-px-less-97-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-px-less-97-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter5_files/figure-html/fig-px-less-97-5-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-px-less-97-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Figure 5.11 Area representing <span class="math inline">\(P(X &lt; 97.5)\)</span> for a normal distribution with <span class="math inline">\(\mu=98.2\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now, we are looking for the probability of having a body temperature of 97.5 or below, which is represented by the left side of the red line. To answer this question, we first turn 97.5 into a z score:</p>
<p><span class="math display">\[
z=\frac{97.5-98.2}{0.73}=-0.96
\]</span></p>
<p><span class="math display">\[
z=\frac{X-\mu}{\sigma}
\]</span></p>
<p>Let’s use <a href="https://homepage.divms.uiowa.edu/~mbognar/applets/normal.html">the applet</a> to find <span class="math inline">\(P(x\le 97.5) = P(z\le -0.96)\)</span> or the probability of <span class="math inline">\(z\)</span> is less than or equal to -0.96.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="chapter5/fig5-12.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Fig 5.12: Aplet Demo 2</figcaption>
</figure>
</div>
<p>The probability that a randomly selected individual from the population has a body temperature less than 97.5 is 0.1688, or 16.9%.</p>
<p>Now, let’s find this probability using the Standard Normal Cumulative Probability Table. Since our z score is –0.96, find the intersection of the –0.9 row and 0.06 column. The stated value is .1685. Since we are interested in the probability of having a body temperature less than or equal to 97.5 and the table represents cumulative probability up until that point, we can simply report that value. The proportion of temperatures that fall at, or below, 97.5 is about 0.1685, or there is a 16.85% chance we would randomly sample an individual who has a body temperature of 97.5 degrees or less. Again, the value is slightly off from the one obtained from the applet due to rounding differences.</p>
<p><strong>Question #3: <em>What is the probability that a randomly sampled individual from this population has a body temperature between 97.5 and 98.6 degrees?</em></strong></p>
<p>With this final question, we are asking: <span class="math inline">\(P(97.5 \le X \le 98.6) = ?\)</span> Although this might seem like a more difficult question, it is actually the same basic concept. The first step is to convert both values to <span class="math inline">\(z\)</span> scores, which we have already done. We know that 98.6 expressed as a <span class="math inline">\(z\)</span> score is about 0.55, and 97.5 expressed as a <span class="math inline">\(z\)</span> score is about -0.96. We have also already figured out the probability of having a temperature above 98.6, <span class="math inline">\(z\)</span> = 0.55, and the probability of having a temperature below 97.5, <span class="math inline">\(z\)</span> = -0.96. We know that the entire probability under the normal distribution is 1.0, so we can get to the probability of scoring between these two <span class="math inline">\(z\)</span> scores by subtracting the probabilities we already know.</p>
<p>Here’s how the math works out:</p>
<p><span class="math display">\[
P(97.5 \le X \le 98.6)
= 1 - P(X \le 97.5) - P(X \ge 98.6)
= 1 - (0.1685 + 0.2912)
= 1 - 0.4597
= 0.5403
\]</span></p>
<p>This means there is a probability of about 0.54, or 54%, that we would randomly sample an individual from this population who has a body temperature between 97.5 and 98.6 degrees.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-between-97-5-98-6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-between-97-5-98-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter5_files/figure-html/fig-between-97-5-98-6-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-between-97-5-98-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Area representing
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">5.3</span> Conclusion</h2>
<p>Chapter 5 delved into the fundamental concepts of the normal distribution, a cornerstone of statistical analysis. It outlined the key features of this distribution, including its symmetric, bell-shaped curve, unimodal nature, and the alignment of its mean, median, and mode at the center. The chapter revisited the empirical rule (68-95-99.7%), explaining how it provides a framework for interpreting the proportion of data within one, two, or three standard deviations from the mean. Additionally, it emphasized the importance of understanding normal distribution properties for making population inferences and highlighted how skewness and kurtosis helped assess a distribution’s symmetry and the likelihood of outliers.</p>
<p>The chapter also introduced z scores as a way to standardize data, enabling meaningful comparisons across different datasets or scales. It explained how to calculate z scores, interpret their significance as standard deviations from the mean, and apply them in the context of the standard normal distribution, where the mean was 0 and the standard deviation was 1. Key applications, such as using z scores to compute probabilities and find areas under the normal curve, were explored through practical examples involving real-world scenarios like body temperature analysis. Tools like z tables and statistical software were presented as essential for calculating probabilities and interpreting results, building a strong foundation for further statistical methods like sampling distributions. Together, the chapter equipped readers with essential skills for understanding and applying the principles of the normal distribution in various contexts.</p>
<section id="key-takeaways-for-educational-researchers-from-chapter-5" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="key-takeaways-for-educational-researchers-from-chapter-5"><span class="header-section-number">5.3.1</span> Key Takeaways for Educational Researchers from Chapter 5 </h3>
<ul>
<li><p>Understanding the characteristics of a normal distribution (symmetry, unimodal shape, and alignment of mean, median, and mode) is important for interpreting data and essential for assessing its appropriateness for applying statistical analyses you will learn later in this book.</p></li>
<li><p>Skewness and kurtosis are key metrics for assessing the symmetry and <em>tailedness</em> of a distribution, helping researchers evaluate how closely their data approximates a normal distribution. A distribution is generally considered approximately normal when these two statistics fall within the range of -1 to 1.</p></li>
<li><p>The empirical rule (68-95-99.7%) helps researchers interpret the portion of data within standard deviations from the means, making it a critical tool for understanding variability of data in education research contexts.</p></li>
<li><p>Z scores provide a standardized measure of how far a data point deviates from the mean, expressed in terms of standard deviation units. By converting raw scores into z scores—a process known as standardization—we enable meaningful comparisons of relative positions across different datasets, even when the original scores are measured on varying scales. Understanding standardization is essential for cross-study comparisons and evaluating individual performance within a population or reference group.</p></li>
<li><p>Although probabilities are rarely calculated manually using z scores in practice, understanding the process provides researchers with a foundational knowledge of probability, enabling them to make population inferences and conduct hypothesis testing—essential components of quantitative analysis in educational research.  </p></li>
</ul>
</section>
</section>
<section id="key-definitions-from-chapter-5" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="key-definitions-from-chapter-5"><span class="header-section-number">5.4</span> Key Definitions from Chapter 5</h2>
<p><strong>Kurtosis</strong> measures the tailedness of a distribution, or how heavy or light the tails are compared to a normal distribution.</p>
<p><strong>Normal distribution (bell curve)</strong> is a statistical distribution that is symmetric about its mean. All three measures of central tendency (mean, median, and mode) are equal and located at the center of the distribution, and the left and right halves of the curve are mirror images of each other.</p>
<p><strong>Skewness</strong> means the extent to which a curve is pulled to one side or another.</p>
<p>The <strong>standard normal distribution</strong> is a specific type of normal distribution that has been standardized so that the mean is 0, the standard deviation is 1, and the distribution is symmetric.</p>
<p>A <strong>z score</strong> (standardized score) is a statistical measure that describes how far a particular data point is from the mean of its distribution, measured in terms of standard deviations.</p>
</section>
<section id="check-your-understanding" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">5.5</span> Check Your Understanding</h2>
<ol type="1">
<li><p><strong>A distribution with high kurtosis has lighter tails than a normal distribution.</strong></p>
<ol type="a">
<li><p>True</p></li>
<li><p>False</p></li>
</ol></li>
<li><p><strong>Which of the following values for skewness and kurtosis indicates that a distribution is approximately normal?</strong></p>
<ol type="a">
<li><p>Skewness = 0.5, Kurtosis = 2.5</p></li>
<li><p>Skewness = 0.25, Kurtosis = 0.5</p></li>
<li><p>Skewness = 1.0, Kurtosis = 3.5</p></li>
<li><p>Skewness = -2.0, Kurtosis = 4.0</p></li>
</ol></li>
<li><p><strong>What is the probability of a data point falling within 1 standard deviation of the mean in a normal distribution?</strong></p>
<ol type="a">
<li><p>68%</p></li>
<li><p>95%</p></li>
<li><p>99.7%</p></li>
<li><p>50%</p></li>
</ol></li>
<li><p><strong>A standardized test has a mean score of 500 and a standard deviation of 100. What is the probability that a randomly selected student scores higher than 650? Use the z score formula and the standard normal distribution table to find the answer.</strong></p>
<ol type="a">
<li><p>0.1056 (10.56%)</p></li>
<li><p>0.1587 (15.87%)</p></li>
<li><p>0.0668 (6.68%)</p></li>
<li><p>0.0228 (2.28%)</p></li>
</ol></li>
<li><p><strong>What is the purpose of converting raw data to z scores?</strong></p>
<ol type="a">
<li><p>To reduce the range of the data.</p></li>
<li><p>To standardize data for comparison across distributions.</p></li>
<li><p>To eliminate outliers.</p></li>
<li><p>To calculate the mean and median more accurately.</p></li>
</ol></li>
</ol>
</section>
</section>
<section id="chapter-5-exploring-the-normal-distribution-in-r" class="level1 unnumbered">
<h1 class="unnumbered">Chapter 5: Exploring the Normal Distribution in R</h1>
<p>This section demonstrates how to work with the normal distribution in R, including checking for normality, calculating skewness and kurtosis, standardizing scores (z-scores), and computing probabilities using the properties of the normal curve. We use the PV1MATH variable as an example.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required package </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required package </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset </span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">"chapter2/US_Data_22.sav"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="visualizing-and-summarizing-the-distribution" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="visualizing-and-summarizing-the-distribution">1 Visualizing and Summarizing the Distribution</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram and summary </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>PV1MATH, <span class="at">breaks=</span><span class="dv">30</span>, <span class="at">main=</span><span class="st">"Distribution of Math Scores"</span>, <span class="at">xlab=</span><span class="st">"PV1MATH"</span>, <span class="at">col=</span><span class="st">"lightblue"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter5_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>PV1MATH) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  188.4   391.3   457.9   461.9   528.9   819.5 </code></pre>
</div>
</div>
<p>As a recap, the first step in exploring a continuous variable, such as math achievement scores (PV1MATH), is to visualize its distribution and review key summary statistics. As covered in Chapters 2 and 3, these basic descriptive measures and visualizations help us quickly understand the main features of the data before proceeding to more advanced analyses.</p>
</section>
<section id="checking-for-normality" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="checking-for-normality">2 Checking for Normality</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych) </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skew</span>(data<span class="sc">$</span>PV1MATH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1730788</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosi</span>(data<span class="sc">$</span>PV1MATH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.3150574</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: The skewness of PV1MATH is 0.17, indicating a slight right (positive) skew, meaning there are a few more high values than low values. The kurtosis is –0.32, suggesting the distribution is slightly flatter (platykurtic) than a perfectly normal distribution. Both values fall well within the range of –1 to 1, so the math scores are approximately normal, with only minor deviations from perfect symmetry and peakedness.</p>
</section>
<section id="standardizing-scores-calculating-z-scores" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="standardizing-scores-calculating-z-scores">3 Standardizing Scores: Calculating Z-scores</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize PV1MATH to obtain z-scores </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>z_scores <span class="ot">&lt;-</span> <span class="fu">scale</span>(data<span class="sc">$</span>PV1MATH) </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># View summary statistics for the standardized scores </span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(z_scores, <span class="at">na.rm=</span><span class="cn">TRUE</span>)      <span class="co"># Should be 0 </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.350414e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(z_scores, <span class="at">na.rm=</span><span class="cn">TRUE</span>)        <span class="co"># Should be 1 </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>z_PV1MATH <span class="ot">&lt;-</span> z_scores <span class="co"># Add z-scores to the dataset </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data[, <span class="fu">c</span>(<span class="st">"PV1MATH"</span>, <span class="st">"z_PV1MATH"</span>)]) <span class="co">#show first 6 rows of PV1MATH and z_PV1MATH </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  PV1MATH z_PV1MATH[,1]
    &lt;dbl&gt;         &lt;dbl&gt;
1    575.      1.19    
2    442.     -0.209   
3    680.      2.30    
4    462.      0.000270
5    501.      0.414   
6    322.     -1.47    </code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p>To standardize the math scores (PV1MATH), we calculated z-scores for each student. The mean of the z-scores is effectively 0 and the standard deviation is 1, as expected. This confirms that the z-scores represent how many standard deviations each math score is from the mean.</p>
<p>Let’s look at two example students from the first six rows:</p>
<ul>
<li><p>The first student has a raw math score of 573, which corresponds to a z-score of 1.17. This means their math score is 1.17 standard deviations above the mean (with the mean previously reported as about 462).</p></li>
<li><p>The second student has a math score of 440, giving a z-score of –0.23. This means their score is slightly below the mean (about 0.23 standard deviations lower).</p></li>
</ul>
<p>By adding the z-scores to the dataset, it’s easier to compare each student’s performance relative to the whole group, regardless of the scale of the original scores.</p>
</section>
<section id="example-calculating-z-scores-and-probabilities-questions-1-3-.unnumbered" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="example-calculating-z-scores-and-probabilities-questions-1-3-.unnumbered"><span class="header-section-number">5.6</span> 4 Example: Calculating Z-scores and Probabilities (Questions 1-3) {.unnumbered</h2>
<p>Suppose the mean (𝜇) = 98.2 and standard deviation (𝜎) = 0.73, as in the body temperature example.</p>
<p><strong>Q1. Probability that X ≥ 98.6</strong></p>
<p>Here we replicate the example from section Finding Areas Under the Normal Curve, calculating the probability that a randomly selected person has a body temperature of 98.6°F or higher. }</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fl">98.2</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.73</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fl">98.6</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate z </span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>z1 <span class="ot">&lt;-</span> (x1 <span class="sc">-</span> mu) <span class="sc">/</span> sigma </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>z1 <span class="co">#~0.55 </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5479452</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability that X &gt;= 98.6 </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>prob1 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z1, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="co">#lower.tail = FALSE gives the right tail probability </span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>prob1   <span class="co"># ~0.2912 </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2918648</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: About 29.1% of the population have a body temperature of 98.6 or higher.</p>
<p><strong>Q2. Probability that X ≤ 97.5</strong> Now we calculate the probability that a randomly selected person has a body temperature of 97.5°F or lower.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fl">97.5</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>z2 <span class="ot">&lt;-</span> (x2 <span class="sc">-</span> mu) <span class="sc">/</span> sigma </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>z2 <span class="co"># ~-0.96 </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.9589041</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability that X &lt;= 97.5 (left tail) </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>prob2 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z2) <span class="co"># lower.tail = TRUE is the default, so we can omit it to get the left tail probability </span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>prob2   <span class="co"># ~0.1688 </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1688035</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: About 16.9% of the population have a body temperature of 97.5°F or lower.</p>
<p><strong>Q3. Probability between 97.5 and 98.6</strong></p>
<p>Finally, we calculate the probability that a randomly selected person has a body temperature between 97.5°F and 98.6°F.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required package </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability that 97.5 &lt;= X &lt;= 98.6 </span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>prob_between <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span>(prob1<span class="sc">+</span>prob2) <span class="co">#same as in previous section </span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co">#prob_between &lt;- pnorm(z1) - pnorm(z2) #alternative </span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>prob_between  <span class="co"># ~0.54 </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5393317</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: About 53.9% (difference due to rounding) of the population have a body temperature between 97.5°F and 98.6°F.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter4.html" class="pagination-link" aria-label="Chapter 4">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 4</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter6.html" class="pagination-link" aria-label="Chapter 6">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 6</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>